[package]
name = "bid-arbitrator"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
tokio.workspace = true
serde.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
sqlx.workspace = true
redis.workspace = true
redlock.workspace = true
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
async-trait.workspace = true
mongodb.workspace = true
shared.workspace = true
common.workspace = true
models.workspace = true
