CREATE TABLE IF NOT EXISTS chain_config (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    config_id VARCHAR(64) NOT NULL UNIQUE COMMENT '配置ID',
    namespace VARCHAR(64) NOT NULL COMMENT '命名空间',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    parameters TEXT COMMENT '配置参数(JSON)',
    enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用',
    applied_at DATETIME COMMENT '生效时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_namespace (namespace),
    INDEX idx_config_id (config_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='链配置表';

CREATE TABLE IF NOT EXISTS task_run (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    run_id VARCHAR(64) NOT NULL UNIQUE COMMENT '运行实例ID',
    entity_id VARCHAR(64) COMMENT '关联实体ID',
    phase VARCHAR(32) COMMENT '执行阶段',
    progress DECIMAL(5,4) DEFAULT 0 COMMENT '进度0-1',
    started_at DATETIME COMMENT '开始时间',
    completed_at DATETIME COMMENT '完成时间',
    error_detail TEXT COMMENT '错误详情',
    status VARCHAR(32) COMMENT '状态',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_run_id (run_id),
    INDEX idx_entity_id (entity_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务运行表';

CREATE TABLE IF NOT EXISTS metrics_snapshot (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    snapshot_id VARCHAR(64) NOT NULL UNIQUE COMMENT '快照ID',
    timestamp DATETIME NOT NULL COMMENT '快照时间',
    metrics TEXT COMMENT '指标数据(JSON)',
    dimensions TEXT COMMENT '维度数据(JSON)',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_snapshot_id (snapshot_id),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='指标快照表';

CREATE TABLE IF NOT EXISTS chain_transaction (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    tx_id VARCHAR(128) NOT NULL UNIQUE COMMENT '交易ID',
    chain_type VARCHAR(32) NOT NULL COMMENT '链类型',
    chain_id INT COMMENT '链ID',
    from_address VARCHAR(256) COMMENT '发起地址',
    to_address VARCHAR(256) COMMENT '接收地址',
    amount DECIMAL(36,18) COMMENT '交易金额',
    gas_limit BIGINT COMMENT 'Gas限制',
    gas_price DECIMAL(36,18) COMMENT 'Gas价格',
    nonce BIGINT COMMENT 'Nonce',
    tx_data TEXT COMMENT '交易数据',
    signed_tx TEXT COMMENT '签名后交易',
    status VARCHAR(32) COMMENT '状态',
    block_number BIGINT COMMENT '区块号',
    tx_hash VARCHAR(128) COMMENT '交易哈希',
    multisig_wallet_id VARCHAR(64) COMMENT '多签钱包ID',
    multisig_proposal_id VARCHAR(64) COMMENT '多签提案ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_tx_id (tx_id),
    INDEX idx_chain_type (chain_type),
    INDEX idx_status (status),
    INDEX idx_from_address (from_address),
    INDEX idx_block_number (block_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='链上交易表';

CREATE TABLE IF NOT EXISTS multisig_wallet (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    wallet_id VARCHAR(64) NOT NULL UNIQUE COMMENT '钱包ID',
    chain_type VARCHAR(32) NOT NULL COMMENT '链类型',
    wallet_address VARCHAR(256) NOT NULL COMMENT '钱包地址',
    threshold INT NOT NULL COMMENT '签名阈值',
    owners TEXT COMMENT '所有者列表(JSON)',
    name VARCHAR(128) COMMENT '钱包名称',
    description VARCHAR(512) COMMENT '描述',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_wallet_id (wallet_id),
    INDEX idx_chain_type (chain_type),
    INDEX idx_address (wallet_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多签钱包表';

CREATE TABLE IF NOT EXISTS multisig_proposal (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    proposal_id VARCHAR(64) NOT NULL UNIQUE COMMENT '提案ID',
    wallet_id VARCHAR(64) NOT NULL COMMENT '钱包ID',
    proposer VARCHAR(256) COMMENT '提案人',
    title VARCHAR(256) COMMENT '提案标题',
    description TEXT COMMENT '提案描述',
    tx_data TEXT COMMENT '交易数据',
    status VARCHAR(32) COMMENT '状态',
    signatures TEXT COMMENT '签名列表(JSON)',
    signed_count INT DEFAULT 0 COMMENT '已签名数',
    threshold INT COMMENT '执行阈值',
    executed_at DATETIME COMMENT '执行时间',
    tx_hash VARCHAR(128) COMMENT '执行交易哈希',
    expires_at DATETIME COMMENT '过期时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_proposal_id (proposal_id),
    INDEX idx_wallet_id (wallet_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多签提案表';

CREATE TABLE IF NOT EXISTS indexed_block (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    block_id VARCHAR(128) NOT NULL UNIQUE COMMENT '区块唯一标识',
    chain_type VARCHAR(32) NOT NULL COMMENT '链类型',
    chain_id INT COMMENT '链ID',
    block_number BIGINT NOT NULL COMMENT '区块高度',
    block_hash VARCHAR(128) NOT NULL COMMENT '区块哈希',
    parent_hash VARCHAR(128) COMMENT '父区块哈希',
    timestamp BIGINT COMMENT '区块时间戳',
    miner VARCHAR(256) COMMENT '矿工地址',
    difficulty DECIMAL(36,0) COMMENT '难度',
    gas_used BIGINT COMMENT '已用Gas',
    gas_limit BIGINT COMMENT 'Gas限制',
    tx_count INT COMMENT '交易数量',
    raw_data MEDIUMTEXT COMMENT '原始区块数据',
    indexed_at DATETIME COMMENT '索引时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    UNIQUE KEY uk_chain_block (chain_type, block_number),
    INDEX idx_block_hash (block_hash),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='已索引区块表';

CREATE TABLE IF NOT EXISTS indexed_transaction (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    tx_id VARCHAR(128) NOT NULL UNIQUE COMMENT '交易索引ID',
    chain_type VARCHAR(32) NOT NULL COMMENT '链类型',
    block_number BIGINT NOT NULL COMMENT '区块高度',
    tx_hash VARCHAR(128) NOT NULL COMMENT '交易哈希',
    tx_index INT COMMENT '交易在区块中的索引',
    from_address VARCHAR(256) COMMENT '发送地址',
    to_address VARCHAR(256) COMMENT '接收地址',
    value DECIMAL(36,18) COMMENT '转账金额',
    gas_price DECIMAL(36,18) COMMENT 'Gas价格',
    gas_used BIGINT COMMENT 'Gas消耗',
    input_data MEDIUMTEXT COMMENT '输入数据',
    status INT COMMENT '交易状态',
    contract_address VARCHAR(256) COMMENT '合约地址',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_tx_hash (tx_hash),
    INDEX idx_block_number (block_number),
    INDEX idx_from_address (from_address),
    INDEX idx_to_address (to_address),
    INDEX idx_contract_address (contract_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='已索引交易表';

CREATE TABLE IF NOT EXISTS contract_event (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    event_id VARCHAR(128) NOT NULL UNIQUE COMMENT '事件ID',
    chain_type VARCHAR(32) NOT NULL COMMENT '链类型',
    block_number BIGINT NOT NULL COMMENT '区块高度',
    tx_hash VARCHAR(128) NOT NULL COMMENT '交易哈希',
    log_index INT COMMENT '日志索引',
    contract_address VARCHAR(256) NOT NULL COMMENT '合约地址',
    event_signature VARCHAR(256) COMMENT '事件签名',
    event_name VARCHAR(128) COMMENT '事件名称',
    topics TEXT COMMENT '主题列表(JSON)',
    data MEDIUMTEXT COMMENT '事件数据',
    decoded_data TEXT COMMENT '解码后数据(JSON)',
    processed TINYINT(1) DEFAULT 0 COMMENT '是否已处理',
    processed_at DATETIME COMMENT '处理时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_event_id (event_id),
    INDEX idx_contract_address (contract_address),
    INDEX idx_block_number (block_number),
    INDEX idx_tx_hash (tx_hash),
    INDEX idx_processed (processed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合约事件表';

CREATE TABLE IF NOT EXISTS storage_object (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    object_id VARCHAR(128) NOT NULL UNIQUE COMMENT '存储对象ID',
    storage_network VARCHAR(32) NOT NULL COMMENT '存储网络(IPFS/ARWEAVE)',
    cid VARCHAR(256) COMMENT '内容ID',
    content_hash VARCHAR(128) COMMENT '内容哈希',
    content_type VARCHAR(128) COMMENT '内容类型',
    size BIGINT COMMENT '内容大小',
    pin_status VARCHAR(32) COMMENT 'Pin状态',
    pin_location VARCHAR(256) COMMENT 'Pin位置',
    metadata TEXT COMMENT '元数据(JSON)',
    original_url VARCHAR(512) COMMENT '原始访问URL',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_object_id (object_id),
    INDEX idx_cid (cid),
    INDEX idx_storage_network (storage_network),
    INDEX idx_pin_status (pin_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='去中心化存储对象表';

CREATE TABLE IF NOT EXISTS cross_chain_transfer (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    transfer_id VARCHAR(64) NOT NULL UNIQUE COMMENT '跨链转账ID',
    source_chain VARCHAR(32) NOT NULL COMMENT '源链',
    target_chain VARCHAR(32) NOT NULL COMMENT '目标链',
    source_address VARCHAR(256) COMMENT '源地址',
    target_address VARCHAR(256) COMMENT '目标地址',
    token_address VARCHAR(256) COMMENT '代币地址',
    amount DECIMAL(36,18) COMMENT '转账金额',
    fee DECIMAL(36,18) COMMENT '手续费',
    source_tx_hash VARCHAR(128) COMMENT '源链交易哈希',
    target_tx_hash VARCHAR(128) COMMENT '目标链交易哈希',
    status VARCHAR(32) COMMENT '状态',
    message_proof TEXT COMMENT '消息证明',
    lock_transaction_id VARCHAR(64) COMMENT '锁定交易ID',
    mint_transaction_id VARCHAR(64) COMMENT '铸造交易ID',
    confirmed_at DATETIME COMMENT '确认时间',
    expires_at DATETIME COMMENT '过期时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_transfer_id (transfer_id),
    INDEX idx_source_chain (source_chain),
    INDEX idx_target_chain (target_chain),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨链转账表';

CREATE TABLE IF NOT EXISTS zk_proof (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    proof_id VARCHAR(64) NOT NULL UNIQUE COMMENT '证明ID',
    circuit_id VARCHAR(64) COMMENT '电路ID',
    scheme_type VARCHAR(32) COMMENT '证明方案(GROTH16/PLONK)',
    proof_data MEDIUMTEXT COMMENT '证明数据',
    public_inputs TEXT COMMENT '公开输入(JSON)',
    verification_key TEXT COMMENT '验证密钥',
    verified TINYINT(1) DEFAULT 0 COMMENT '是否验证通过',
    verified_at DATETIME COMMENT '验证时间',
    verification_result TEXT COMMENT '验证结果详情',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_proof_id (proof_id),
    INDEX idx_circuit_id (circuit_id),
    INDEX idx_verified (verified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='零知识证明表';

CREATE TABLE IF NOT EXISTS gas_history (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    history_id VARCHAR(64) NOT NULL UNIQUE COMMENT '历史记录ID',
    chain_type VARCHAR(32) NOT NULL COMMENT '链类型',
    block_number BIGINT COMMENT '区块高度',
    avg_gas_price DECIMAL(36,18) COMMENT '平均Gas价格',
    fast_gas_price DECIMAL(36,18) COMMENT '快速Gas价格',
    standard_gas_price DECIMAL(36,18) COMMENT '标准Gas价格',
    slow_gas_price DECIMAL(36,18) COMMENT '慢速Gas价格',
    base_fee DECIMAL(36,18) COMMENT '基础费用',
    priority_fee DECIMAL(36,18) COMMENT '优先费用',
    timestamp BIGINT COMMENT '时间戳',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_history_id (history_id),
    INDEX idx_chain_type (chain_type),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gas历史记录表';

CREATE TABLE IF NOT EXISTS rpc_node (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    node_id VARCHAR(64) NOT NULL UNIQUE COMMENT '节点ID',
    chain_type VARCHAR(32) NOT NULL COMMENT '链类型',
    chain_id INT COMMENT '链ID',
    rpc_url VARCHAR(512) NOT NULL COMMENT 'RPC地址',
    ws_url VARCHAR(512) COMMENT 'WebSocket地址',
    name VARCHAR(128) COMMENT '节点名称',
    priority INT DEFAULT 0 COMMENT '优先级',
    weight INT DEFAULT 100 COMMENT '权重',
    max_retries INT DEFAULT 3 COMMENT '最大重试次数',
    timeout_ms INT DEFAULT 10000 COMMENT '超时时间(ms)',
    enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用',
    health_status VARCHAR(32) COMMENT '健康状态',
    last_health_check DATETIME COMMENT '上次健康检查时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除',
    version_lock INT DEFAULT 0 COMMENT '乐观锁版本',
    INDEX idx_node_id (node_id),
    INDEX idx_chain_type (chain_type),
    INDEX idx_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RPC节点配置表';
