-- V1__Initial_Schema.sql
-- 核心业务表结构

CREATE TABLE IF NOT EXISTS log_config (
    id VARCHAR(32) PRIMARY KEY,
    logger_name VARCHAR(255) NOT NULL,
    level VARCHAR(20) NOT NULL,
    effective_level VARCHAR(20),
    namespace VARCHAR(100) NOT NULL,
    app_name VARCHAR(100),
    instance_id VARCHAR(100),
    dynamic_enabled BOOLEAN DEFAULT true,
    ttl_seconds BIGINT,
    expires_at DATETIME,
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_logger_namespace (logger_name, namespace),
    INDEX idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS task (
    id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50),
    status VARCHAR(30) NOT NULL,
    cron_expression VARCHAR(100),
    fixed_delay_ms BIGINT,
    fixed_rate_ms BIGINT,
    start_time DATETIME,
    end_time DATETIME,
    priority INT DEFAULT 0,
    max_retries INT DEFAULT 3,
    retry_count INT DEFAULT 0,
    timeout_ms BIGINT,
    handler_class VARCHAR(255),
    payload TEXT,
    dependencies TEXT,
    parent_task_id VARCHAR(32),
    run_id VARCHAR(64),
    progress DOUBLE DEFAULT 0,
    error_detail TEXT,
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_status (status),
    INDEX idx_parent_task (parent_task_id),
    INDEX idx_type_status (type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS task_run (
    id VARCHAR(32) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(32) NOT NULL,
    status VARCHAR(30) NOT NULL,
    progress DOUBLE DEFAULT 0,
    started_at DATETIME,
    completed_at DATETIME,
    duration_ms BIGINT,
    result TEXT,
    error_detail TEXT,
    worker_id VARCHAR(100),
    trace_id VARCHAR(64),
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_task_id (task_id),
    INDEX idx_run_id (run_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS offline_data (
    id VARCHAR(32) PRIMARY KEY,
    data_type VARCHAR(100) NOT NULL,
    data_key VARCHAR(255) NOT NULL,
    payload MEDIUMTEXT,
    checksum VARCHAR(64),
    sync_status VARCHAR(30) NOT NULL,
    retry_count INT DEFAULT 0,
    synced_at DATETIME,
    sync_error TEXT,
    source_device VARCHAR(100),
    size_bytes BIGINT,
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_sync_status (sync_status),
    INDEX idx_data_key (data_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `rule` (
    id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    event_type VARCHAR(100) NOT NULL,
    condition_type VARCHAR(30),
    condition_expression TEXT,
    action_type VARCHAR(50),
    action_config TEXT,
    enabled BOOLEAN DEFAULT true,
    priority INT DEFAULT 0,
    tags TEXT,
    namespace VARCHAR(100),
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_event_type (event_type),
    INDEX idx_namespace_enabled (namespace, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS device_shadow (
    id VARCHAR(32) PRIMARY KEY,
    device_id VARCHAR(100) NOT NULL UNIQUE,
    device_name VARCHAR(255),
    device_type VARCHAR(50),
    desired_state JSON,
    reported_state JSON,
    delta_state JSON,
    version INT DEFAULT 0,
    last_reported_at DATETIME,
    last_desired_updated_at DATETIME,
    online BOOLEAN DEFAULT false,
    connection_status VARCHAR(30),
    namespace VARCHAR(100),
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_device_id (device_id),
    INDEX idx_online (online)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS config (
    id VARCHAR(32) PRIMARY KEY,
    config_id VARCHAR(64),
    namespace VARCHAR(100) NOT NULL,
    `group` VARCHAR(100) DEFAULT 'DEFAULT_GROUP',
    data_id VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    parameters JSON,
    content MEDIUMTEXT,
    content_type VARCHAR(50) DEFAULT 'json',
    enabled BOOLEAN DEFAULT true,
    description TEXT,
    applied_by VARCHAR(64),
    applied_at DATETIME,
    rollback_available BOOLEAN DEFAULT true,
    previous_version INT,
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    UNIQUE KEY uk_data_namespace_version (data_id, namespace, version),
    INDEX idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification (
    id VARCHAR(32) PRIMARY KEY,
    template_id VARCHAR(64),
    type VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    recipient VARCHAR(500) NOT NULL,
    subject VARCHAR(500),
    content MEDIUMTEXT,
    variables JSON,
    channel VARCHAR(50),
    priority INT DEFAULT 0,
    max_retries INT DEFAULT 3,
    retry_count INT DEFAULT 0,
    sent_at DATETIME,
    delivered_at DATETIME,
    delivery_receipt TEXT,
    error_message TEXT,
    ttl_seconds BIGINT,
    expires_at DATETIME,
    trace_id VARCHAR(64),
    metadata JSON,
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_status (status),
    INDEX idx_trace_id (trace_id),
    INDEX idx_type_status (type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS metrics_snapshot (
    id VARCHAR(32) PRIMARY KEY,
    snapshot_id VARCHAR(64) NOT NULL,
    timestamp DATETIME NOT NULL,
    metrics JSON,
    dimensions JSON,
    namespace VARCHAR(100),
    window_size_ms BIGINT,
    created_by VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_by VARCHAR(64),
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT false,
    INDEX idx_namespace_time (namespace, timestamp),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
