CREATE TABLE tasks (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id VARCHAR(64) NOT NULL UNIQUE,
    type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    name VARCHAR(255),
    description TEXT,
    config JSON,
    payload TEXT,
    namespace VARCHAR(128),
    queue_name VARCHAR(128),
    max_retries INT DEFAULT 3,
    retry_count INT DEFAULT 0,
    timeout_seconds INT,
    scheduled_at DATETIME,
    started_at DATETIME,
    completed_at DATETIME,
    parent_task_id VARCHAR(64),
    error_message TEXT,
    result_data TEXT,
    labels JSON,
    created_by VARCHAR(128),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_task_status (status),
    INDEX idx_task_namespace (namespace),
    INDEX idx_task_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE task_runs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(64) NOT NULL,
    phase VARCHAR(64),
    progress DOUBLE DEFAULT 0,
    started_at DATETIME,
    completed_at DATETIME,
    status VARCHAR(32),
    worker_id VARCHAR(128),
    node_name VARCHAR(128),
    error_detail TEXT,
    logs TEXT,
    metrics JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_run_task_id (task_id),
    INDEX idx_run_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE config_entries (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    config_id VARCHAR(64) NOT NULL UNIQUE,
    namespace VARCHAR(128) NOT NULL,
    config_key VARCHAR(255) NOT NULL,
    config_value TEXT,
    version INT NOT NULL DEFAULT 1,
    description VARCHAR(512),
    enabled TINYINT(1) DEFAULT 1,
    applied_at DATETIME,
    applied_by VARCHAR(128),
    source VARCHAR(64),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    UNIQUE KEY uk_namespace_key_version (namespace, config_key, version),
    INDEX idx_config_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE models (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    model_id VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    latest_version VARCHAR(64),
    stage VARCHAR(32),
    model_type VARCHAR(64),
    framework VARCHAR(64),
    metadata JSON,
    tags JSON,
    created_by VARCHAR(128),
    archived_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_model_stage (stage)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE model_versions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    version_id VARCHAR(64) NOT NULL UNIQUE,
    model_id VARCHAR(64) NOT NULL,
    version VARCHAR(64) NOT NULL,
    stage VARCHAR(32),
    artifact_path VARCHAR(512),
    checksum VARCHAR(128),
    size_bytes BIGINT,
    metrics JSON,
    training_data TEXT,
    description TEXT,
    created_by VARCHAR(128),
    promoted_at DATETIME,
    archived_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_version_model_id (model_id),
    INDEX idx_version_stage (stage)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE prompt_versions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    prompt_id VARCHAR(64) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    name VARCHAR(255),
    content TEXT NOT NULL,
    template TEXT,
    variables JSON,
    model_id VARCHAR(64),
    temperature DOUBLE DEFAULT 0.7,
    max_tokens INT DEFAULT 2048,
    description TEXT,
    tags JSON,
    created_by VARCHAR(128),
    is_latest TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    UNIQUE KEY uk_prompt_version (prompt_id, version),
    INDEX idx_prompt_id (prompt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE experiments (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    experiment_id VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(64),
    status VARCHAR(32),
    control_prompt_id VARCHAR(64),
    treatment_prompt_ids JSON,
    traffic_split JSON,
    metrics JSON,
    start_time DATETIME,
    end_time DATETIME,
    created_by VARCHAR(128),
    result TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_exp_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE adversarial_samples (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    sample_id VARCHAR(64) NOT NULL UNIQUE,
    attack_type VARCHAR(64),
    original_prompt TEXT,
    adversarial_prompt TEXT,
    target_model VARCHAR(128),
    attack_strategy VARCHAR(64),
    success TINYINT(1),
    confidence_score DOUBLE,
    evaluation_result JSON,
    model_response TEXT,
    metadata JSON,
    created_by VARCHAR(128),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_attack_type (attack_type),
    INDEX idx_target_model (target_model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE documents (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    doc_id VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(512),
    content LONGTEXT,
    file_path VARCHAR(512),
    file_type VARCHAR(64),
    file_size BIGINT,
    checksum VARCHAR(128),
    parse_status VARCHAR(32),
    chunk_count INT DEFAULT 0,
    metadata JSON,
    tags JSON,
    created_by VARCHAR(128),
    processed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_doc_type (file_type),
    INDEX idx_doc_status (parse_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE document_chunks (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    chunk_id VARCHAR(64) NOT NULL UNIQUE,
    doc_id VARCHAR(64) NOT NULL,
    chunk_index INT NOT NULL,
    content TEXT,
    embedding BLOB,
    embedding_model VARCHAR(128),
    vector_dimension INT,
    metadata JSON,
    token_count INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_chunk_doc_id (doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE gpu_resources (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    gpu_id VARCHAR(64) NOT NULL UNIQUE,
    node_name VARCHAR(128) NOT NULL,
    gpu_index INT NOT NULL,
    uuid VARCHAR(128),
    model_name VARCHAR(128),
    total_memory_mb INT,
    used_memory_mb INT DEFAULT 0,
    gpu_utilization DOUBLE DEFAULT 0,
    status VARCHAR(32),
    current_task_id VARCHAR(64),
    labels JSON,
    last_heartbeat DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_gpu_node (node_name),
    INDEX idx_gpu_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE backups (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    backup_id VARCHAR(64) NOT NULL UNIQUE,
    backup_type VARCHAR(64),
    source_path VARCHAR(512),
    target_path VARCHAR(512),
    status VARCHAR(32),
    size_bytes BIGINT,
    checksum VARCHAR(128),
    metadata JSON,
    created_by VARCHAR(128),
    started_at DATETIME,
    completed_at DATETIME,
    error_message TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    INDEX idx_backup_status (status),
    INDEX idx_backup_type (backup_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE schema_migrations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    version VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(255),
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    success TINYINT(1) DEFAULT 1,
    checksum VARCHAR(128),
    execution_time INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
