run:
  timeout: 5m
  skip-dirs:
    - vendor
    - migrations
    - testdata

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - prealloc
    - exportloopref
    - nilerr

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/datateam/loganalyzer
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "G104: Errors unhandled"
