org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true

kafkaVersion=3.7.0
kafkaStreamsVersion=3.7.0
postgresVersion=42.7.3
timescaleVersion=2.14.2
minioVersion=8.5.10
testcontainersVersion=1.19.8
springBootVersion=3.3.0
antlrVersion=4.13.1
