version = "Two"

use_small_heuristics = "Max"
use_field_init_shorthand = true
format_code_in_doc_comments = true
wrap_comments = true
normalize_doc_attributes = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
report_todo = "Always"
report_fixme = "Always"
imports_granularity = "Module"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
edition = "2021"
trailing_comma = "Vertical"
trailing_semicolon = true
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"
brace_style = "SameLine"
