unstable_features = true
version = "Two"
format_strings = true
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2021"
max_width = 120
use_small_heuristics = "Max"
fn_args_layout = "Tall"
struct_lit_width = 40
struct_variant_width = 40
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
hex_literal_case = "Lower"
