spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meshcontrol_dev?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useInformationSchema=true
    username: root
    password: root

  flyway:
    schemas: meshcontrol_dev

logging:
  level:
    com.meshcontrol: DEBUG
