dependencies {
    implementation project(':common')
    implementation project(':storage-index')
    implementation project(':metrics-aggregator')
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'
    implementation 'org.quartz-scheduler:quartz:2.3.2'
    implementation 'com.sun.mail:javax.mail:1.6.2'

    testImplementation project(':test-support')
}
