// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tensor {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "DataType", tag = "2")]
    pub dtype: i32,
    #[prost(int64, repeated, tag = "3")]
    pub shape: ::prost::alloc::vec::Vec<i64>,
    #[prost(bytes = "vec", tag = "4")]
    pub data_bytes: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub inputs: ::prost::alloc::vec::Vec<Tensor>,
    #[prost(map = "string, message", tag = "5")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::super::google::protobuf::Value,
    >,
    #[prost(string, tag = "6")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "8")]
    pub priority: i32,
    #[prost(int64, tag = "9")]
    pub timeout_ms: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub outputs: ::prost::alloc::vec::Vec<Tensor>,
    #[prost(int64, tag = "3")]
    pub latency_ms: i64,
    #[prost(int32, tag = "4")]
    pub gpu_id: i32,
    #[prost(string, tag = "5")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub started_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub completed_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchInferRequest {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<InferRequest>,
    #[prost(int64, tag = "2")]
    pub max_batch_size: i64,
    #[prost(int64, tag = "3")]
    pub max_wait_ms: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchInferResponse {
    #[prost(message, repeated, tag = "1")]
    pub responses: ::prost::alloc::vec::Vec<InferResponse>,
    #[prost(int64, tag = "2")]
    pub total_latency_ms: i64,
    #[prost(int32, tag = "3")]
    pub batch_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelStatusRequest {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelStatusResponse {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelStatus", tag = "3")]
    pub status: i32,
    #[prost(int32, tag = "4")]
    pub active_instances: i32,
    #[prost(int64, tag = "5")]
    pub total_requests: i64,
    #[prost(int64, tag = "6")]
    pub avg_latency_ms: i64,
    #[prost(int64, tag = "7")]
    pub p99_latency_ms: i64,
    #[prost(int64, tag = "8")]
    pub memory_usage_mb: i64,
    #[prost(int32, tag = "9")]
    pub gpu_id: i32,
    #[prost(string, tag = "10")]
    pub error: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "11")]
    pub last_heartbeat: ::core::option::Option<
        super::super::google::protobuf::Timestamp,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadModelRequest {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "RuntimeBackend", tag = "3")]
    pub backend: i32,
    #[prost(string, tag = "4")]
    pub model_path: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub num_instances: i32,
    #[prost(int32, repeated, tag = "6")]
    pub gpu_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(map = "string, message", tag = "7")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::super::google::protobuf::Value,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadModelResponse {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelStatus", tag = "3")]
    pub status: i32,
    #[prost(int64, tag = "4")]
    pub load_time_ms: i64,
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnloadModelRequest {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub force: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnloadModelResponse {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WarmupModelRequest {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub num_iterations: i32,
    #[prost(message, repeated, tag = "4")]
    pub samples: ::prost::alloc::vec::Vec<InferRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WarmupModelResponse {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub iterations_completed: i32,
    #[prost(int64, tag = "4")]
    pub avg_latency_ms: i64,
    #[prost(int64, tag = "5")]
    pub min_latency_ms: i64,
    #[prost(int64, tag = "6")]
    pub max_latency_ms: i64,
    #[prost(string, tag = "7")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelMetadata {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelType", tag = "4")]
    pub model_type: i32,
    #[prost(string, tag = "5")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub author: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "8")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "9")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(string, tag = "11")]
    pub model_uri: ::prost::alloc::string::String,
    #[prost(int64, tag = "12")]
    pub model_size_bytes: i64,
    #[prost(enumeration = "RuntimeBackend", tag = "13")]
    pub preferred_backend: i32,
    #[prost(map = "string, string", tag = "14")]
    pub input_schema: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string", tag = "15")]
    pub output_schema: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int64, tag = "16")]
    pub max_batch_size: i64,
    #[prost(int64, tag = "17")]
    pub max_sequence_length: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterModelRequest {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<ModelMetadata>,
    #[prost(bool, tag = "2")]
    pub overwrite: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterModelResponse {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub registered_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetModelRequest {
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(oneof = "get_model_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<get_model_request::Query>,
}
/// Nested message and enum types in `GetModelRequest`.
pub mod get_model_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Query {
        #[prost(string, tag = "1")]
        ModelId(::prost::alloc::string::String),
        #[prost(string, tag = "2")]
        ModelName(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetModelResponse {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<ModelMetadata>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsRequest {
    #[prost(enumeration = "ModelType", tag = "1")]
    pub model_type: i32,
    #[prost(string, repeated, tag = "2")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "3")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int32, tag = "4")]
    pub page_size: i32,
    #[prost(string, tag = "5")]
    pub page_token: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub include_versions: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<ModelMetadata>,
    #[prost(string, tag = "2")]
    pub next_page_token: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub total_count: i32,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateModelStatusRequest {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelStatus", tag = "4")]
    pub status: i32,
    #[prost(map = "string, message", tag = "5")]
    pub metrics: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::super::google::protobuf::Value,
    >,
    #[prost(string, tag = "6")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateModelStatusResponse {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelStatus", tag = "4")]
    pub status: i32,
    #[prost(message, optional, tag = "5")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(string, tag = "6")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DataType {
    Unspecified = 0,
    Bool = 1,
    Uint8 = 2,
    Uint16 = 3,
    Uint32 = 4,
    Uint64 = 5,
    Int8 = 6,
    Int16 = 7,
    Int32 = 8,
    Int64 = 9,
    Fp16 = 10,
    Fp32 = 11,
    Fp64 = 12,
    Bf16 = 13,
    String = 14,
}
impl DataType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DATA_TYPE_UNSPECIFIED",
            Self::Bool => "DATA_TYPE_BOOL",
            Self::Uint8 => "DATA_TYPE_UINT8",
            Self::Uint16 => "DATA_TYPE_UINT16",
            Self::Uint32 => "DATA_TYPE_UINT32",
            Self::Uint64 => "DATA_TYPE_UINT64",
            Self::Int8 => "DATA_TYPE_INT8",
            Self::Int16 => "DATA_TYPE_INT16",
            Self::Int32 => "DATA_TYPE_INT32",
            Self::Int64 => "DATA_TYPE_INT64",
            Self::Fp16 => "DATA_TYPE_FP16",
            Self::Fp32 => "DATA_TYPE_FP32",
            Self::Fp64 => "DATA_TYPE_FP64",
            Self::Bf16 => "DATA_TYPE_BF16",
            Self::String => "DATA_TYPE_STRING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DATA_TYPE_BOOL" => Some(Self::Bool),
            "DATA_TYPE_UINT8" => Some(Self::Uint8),
            "DATA_TYPE_UINT16" => Some(Self::Uint16),
            "DATA_TYPE_UINT32" => Some(Self::Uint32),
            "DATA_TYPE_UINT64" => Some(Self::Uint64),
            "DATA_TYPE_INT8" => Some(Self::Int8),
            "DATA_TYPE_INT16" => Some(Self::Int16),
            "DATA_TYPE_INT32" => Some(Self::Int32),
            "DATA_TYPE_INT64" => Some(Self::Int64),
            "DATA_TYPE_FP16" => Some(Self::Fp16),
            "DATA_TYPE_FP32" => Some(Self::Fp32),
            "DATA_TYPE_FP64" => Some(Self::Fp64),
            "DATA_TYPE_BF16" => Some(Self::Bf16),
            "DATA_TYPE_STRING" => Some(Self::String),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModelStatus {
    Unspecified = 0,
    Loaded = 1,
    Loading = 2,
    Unloading = 3,
    Unloaded = 4,
    Error = 5,
    WarmingUp = 6,
    Ready = 7,
}
impl ModelStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MODEL_STATUS_UNSPECIFIED",
            Self::Loaded => "MODEL_STATUS_LOADED",
            Self::Loading => "MODEL_STATUS_LOADING",
            Self::Unloading => "MODEL_STATUS_UNLOADING",
            Self::Unloaded => "MODEL_STATUS_UNLOADED",
            Self::Error => "MODEL_STATUS_ERROR",
            Self::WarmingUp => "MODEL_STATUS_WARMING_UP",
            Self::Ready => "MODEL_STATUS_READY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODEL_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MODEL_STATUS_LOADED" => Some(Self::Loaded),
            "MODEL_STATUS_LOADING" => Some(Self::Loading),
            "MODEL_STATUS_UNLOADING" => Some(Self::Unloading),
            "MODEL_STATUS_UNLOADED" => Some(Self::Unloaded),
            "MODEL_STATUS_ERROR" => Some(Self::Error),
            "MODEL_STATUS_WARMING_UP" => Some(Self::WarmingUp),
            "MODEL_STATUS_READY" => Some(Self::Ready),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModelType {
    Unspecified = 0,
    Llm = 1,
    Embedding = 2,
    Cv = 3,
    Audio = 4,
    Multimodal = 5,
    Custom = 6,
}
impl ModelType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MODEL_TYPE_UNSPECIFIED",
            Self::Llm => "MODEL_TYPE_LLM",
            Self::Embedding => "MODEL_TYPE_EMBEDDING",
            Self::Cv => "MODEL_TYPE_CV",
            Self::Audio => "MODEL_TYPE_AUDIO",
            Self::Multimodal => "MODEL_TYPE_MULTIMODAL",
            Self::Custom => "MODEL_TYPE_CUSTOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODEL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MODEL_TYPE_LLM" => Some(Self::Llm),
            "MODEL_TYPE_EMBEDDING" => Some(Self::Embedding),
            "MODEL_TYPE_CV" => Some(Self::Cv),
            "MODEL_TYPE_AUDIO" => Some(Self::Audio),
            "MODEL_TYPE_MULTIMODAL" => Some(Self::Multimodal),
            "MODEL_TYPE_CUSTOM" => Some(Self::Custom),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RuntimeBackend {
    Unspecified = 0,
    Onnxrt = 1,
    Tensorrt = 2,
    Torch = 3,
    Vllm = 4,
    Custom = 5,
}
impl RuntimeBackend {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RUNTIME_BACKEND_UNSPECIFIED",
            Self::Onnxrt => "RUNTIME_BACKEND_ONNXRT",
            Self::Tensorrt => "RUNTIME_BACKEND_TENSORRT",
            Self::Torch => "RUNTIME_BACKEND_TORCH",
            Self::Vllm => "RUNTIME_BACKEND_VLLM",
            Self::Custom => "RUNTIME_BACKEND_CUSTOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RUNTIME_BACKEND_UNSPECIFIED" => Some(Self::Unspecified),
            "RUNTIME_BACKEND_ONNXRT" => Some(Self::Onnxrt),
            "RUNTIME_BACKEND_TENSORRT" => Some(Self::Tensorrt),
            "RUNTIME_BACKEND_TORCH" => Some(Self::Torch),
            "RUNTIME_BACKEND_VLLM" => Some(Self::Vllm),
            "RUNTIME_BACKEND_CUSTOM" => Some(Self::Custom),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod inference_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct InferenceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InferenceServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InferenceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InferenceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InferenceServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn infer(
            &mut self,
            request: impl tonic::IntoRequest<super::InferRequest>,
        ) -> std::result::Result<tonic::Response<super::InferResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.InferenceService/Infer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.InferenceService", "Infer"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stream_infer(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::InferRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::InferResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.InferenceService/StreamInfer",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.InferenceService", "StreamInfer"));
            self.inner.streaming(req, path, codec).await
        }
        pub async fn model_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ModelStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ModelStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.InferenceService/ModelStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.InferenceService", "ModelStatus"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod runtime_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct RuntimeServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RuntimeServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RuntimeServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RuntimeServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RuntimeServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn load_model(
            &mut self,
            request: impl tonic::IntoRequest<super::LoadModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoadModelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RuntimeService/LoadModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.RuntimeService", "LoadModel"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn unload_model(
            &mut self,
            request: impl tonic::IntoRequest<super::UnloadModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnloadModelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RuntimeService/UnloadModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.RuntimeService", "UnloadModel"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn warmup_model(
            &mut self,
            request: impl tonic::IntoRequest<super::WarmupModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WarmupModelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RuntimeService/WarmupModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.RuntimeService", "WarmupModel"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn batch_infer(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchInferRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchInferResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RuntimeService/BatchInfer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.RuntimeService", "BatchInfer"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod registry_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct RegistryServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RegistryServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RegistryServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RegistryServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RegistryServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn register_model(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterModelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RegistryService/RegisterModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("inference.v1.RegistryService", "RegisterModel"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_model(
            &mut self,
            request: impl tonic::IntoRequest<super::GetModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetModelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RegistryService/GetModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.RegistryService", "GetModel"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_models(
            &mut self,
            request: impl tonic::IntoRequest<super::ListModelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListModelsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RegistryService/ListModels",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("inference.v1.RegistryService", "ListModels"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_model_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateModelStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateModelStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/inference.v1.RegistryService/UpdateModelStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("inference.v1.RegistryService", "UpdateModelStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
