from app.utils.constants import (
    InventoryTransactionType,
    WarehouseType,
    SyncType,
    SyncStatus,
    ConflictType,
    ResolutionStrategy,
    ConflictStatus,
    CDCOperation,
    CDCSourceSystem,
    CDCEventType,
    CDCEventStatus,
    FIFOStrategy,
    ConditionOperator,
    ConditionType,
    AUTO_APPROVE_MAX_AMOUNT,
    CO_SIGN_MIN_AMOUNT,
    SyncStrategy,
    DEFAULT_SCHEDULED_SYNC_TIME,
    ImportJobType,
    ImportStatus,
    FileType,
    ImportErrorCode,
    SYNC_DELAY_THRESHOLD_SECONDS,
    INVENTORY_CODE_PREFIX,
    WAREHOUSE_CODE_PREFIX,
    ZONE_CODE_PREFIX,
    SUPPLIER_CODE_PREFIX,
    TRANSACTION_CODE_PREFIX,
    SYNC_CODE_PREFIX,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    INVENTORY_LOCK_TIMEOUT,
    CDC_EVENT_BATCH_SIZE,
    SYNC_RETRY_MAX_ATTEMPTS,
    SYNC_RETRY_DELAY_SECONDS,
    ALERT_LOW_STOCK_THRESHOLD,
    ALERT_OVERSTOCK_THRESHOLD,
    WAREHOUSE_CAPACITY_WARNING_THRESHOLD,
    WAREHOUSE_CAPACITY_DANGER_THRESHOLD,
    EXPIRING_WARNING_DAYS,
    EXPIRING_CRITICAL_DAYS,
    PURCHASE_ORDER_PREFIX,
    DOCUMENT_PREFIX,
)
from app.utils.exceptions import (
    InventoryException,
    NotFoundException,
    ConflictException,
    ValidationException,
    BusinessException,
)
from app.utils.helpers import (
    generate_code,
    generate_order_no,
    generate_batch_no,
    generate_document_no,
    generate_sku_code,
    calculate_available_quantity,
    calculate_safety_stock,
    calculate_reorder_point,
    calculate_eoq,
    parse_date,
    format_date,
    get_date_range,
    days_between,
)
def __getattr__(name):
    _lazy_modules = {
        "CDCCaptureEngine": ("app.utils.sync_engine", "CDCCaptureEngine"),
        "ConflictDetectionEngine": ("app.utils.sync_engine", "ConflictDetectionEngine"),
        "ConflictResolver": ("app.utils.sync_engine", "ConflictResolver"),
        "ConsistencyChecker": ("app.utils.sync_engine", "ConsistencyChecker"),
        "SyncDelayMonitor": ("app.utils.sync_engine", "SyncDelayMonitor"),
        "BatchNumberGenerator": ("app.utils.batch_generator", "BatchNumberGenerator"),
        "TraceEngine": ("app.utils.trace_engine", "TraceEngine"),
    }
    if name in _lazy_modules:
        module_path, attr_name = _lazy_modules[name]
        import importlib
        mod = importlib.import_module(module_path)
        return getattr(mod, attr_name)
    raise AttributeError(f"module 'app.utils' has no attribute '{name}'")

__all__ = [
    "InventoryTransactionType",
    "WarehouseType",
    "SyncType",
    "SyncStatus",
    "ConflictType",
    "ResolutionStrategy",
    "ConflictStatus",
    "CDCOperation",
    "CDCSourceSystem",
    "CDCEventType",
    "CDCEventStatus",
    "FIFOStrategy",
    "ConditionOperator",
    "ConditionType",
    "AUTO_APPROVE_MAX_AMOUNT",
    "CO_SIGN_MIN_AMOUNT",
    "SyncStrategy",
    "DEFAULT_SCHEDULED_SYNC_TIME",
    "ImportJobType",
    "ImportStatus",
    "FileType",
    "ImportErrorCode",
    "SYNC_DELAY_THRESHOLD_SECONDS",
    "INVENTORY_CODE_PREFIX",
    "WAREHOUSE_CODE_PREFIX",
    "ZONE_CODE_PREFIX",
    "SUPPLIER_CODE_PREFIX",
    "TRANSACTION_CODE_PREFIX",
    "SYNC_CODE_PREFIX",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "INVENTORY_LOCK_TIMEOUT",
    "CDC_EVENT_BATCH_SIZE",
    "SYNC_RETRY_MAX_ATTEMPTS",
    "SYNC_RETRY_DELAY_SECONDS",
    "ALERT_LOW_STOCK_THRESHOLD",
    "ALERT_OVERSTOCK_THRESHOLD",
    "WAREHOUSE_CAPACITY_WARNING_THRESHOLD",
    "WAREHOUSE_CAPACITY_DANGER_THRESHOLD",
    "EXPIRING_WARNING_DAYS",
    "EXPIRING_CRITICAL_DAYS",
    "PURCHASE_ORDER_PREFIX",
    "DOCUMENT_PREFIX",
    "InventoryException",
    "NotFoundException",
    "ConflictException",
    "ValidationException",
    "BusinessException",
    "generate_code",
    "generate_order_no",
    "generate_batch_no",
    "generate_document_no",
    "generate_sku_code",
    "calculate_available_quantity",
    "calculate_safety_stock",
    "calculate_reorder_point",
    "calculate_eoq",
    "parse_date",
    "format_date",
    "get_date_range",
    "days_between",
    "CDCCaptureEngine",
    "ConflictDetectionEngine",
    "ConflictResolver",
    "ConsistencyChecker",
    "SyncDelayMonitor",
    "BatchNumberGenerator",
    "TraceEngine",
]
