from enum import Enum


class InventoryTransactionType(str, Enum):
    IN = "IN"
    OUT = "OUT"
    TRANSFER = "TRANSFER"
    ADJUSTMENT = "ADJUSTMENT"
    COUNT = "COUNT"


class WarehouseType(str, Enum):
    MAIN = "MAIN"
    BRANCH = "BRANCH"
    FULFILLMENT = "FULFILLMENT"
    RETURNS = "RETURNS"


class SyncType(str, Enum):
    FULL = "FULL"
    INCREMENTAL = "INCREMENTAL"


class SyncStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ConflictType(str, Enum):
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    COST_MISMATCH = "COST_MISMATCH"
    STATUS_MISMATCH = "STATUS_MISMATCH"


class ResolutionStrategy(str, Enum):
    SOURCE_WINS = "SOURCE_WINS"
    TARGET_WINS = "TARGET_WINS"
    MANUAL = "MANUAL"


class ConflictStatus(str, Enum):
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class CDCOperation(str, Enum):
    INSERT = "INSERT"
    UPDATE = "UPDATE"
    DELETE = "DELETE"


class CDCSourceSystem(str, Enum):
    ERP = "ERP"
    WMS = "WMS"
    OMS = "OMS"


class CDCEventType(str, Enum):
    INVENTORY_CHANGED = "INVENTORY_CHANGED"
    ORDER_CREATED = "ORDER_CREATED"


class CDCEventStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"


class FIFOStrategy(str, Enum):
    FIFO = "FIFO"
    FEFO = "FEFO"
    LIFO = "LIFO"


SYNC_DELAY_THRESHOLD_SECONDS = 300

INVENTORY_CODE_PREFIX = "INV"
WAREHOUSE_CODE_PREFIX = "WH"
ZONE_CODE_PREFIX = "ZN"
SUPPLIER_CODE_PREFIX = "SUP"
TRANSACTION_CODE_PREFIX = "TRX"
SYNC_CODE_PREFIX = "SYNC"

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

INVENTORY_LOCK_TIMEOUT = 30

CDC_EVENT_BATCH_SIZE = 100

SYNC_RETRY_MAX_ATTEMPTS = 3
SYNC_RETRY_DELAY_SECONDS = 60

ALERT_LOW_STOCK_THRESHOLD = 10
ALERT_OVERSTOCK_THRESHOLD = 1000

WAREHOUSE_CAPACITY_WARNING_THRESHOLD = 0.8
WAREHOUSE_CAPACITY_DANGER_THRESHOLD = 0.95

EXPIRING_WARNING_DAYS = 30
EXPIRING_CRITICAL_DAYS = 7
