apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.database.existingSecret }}
  DB_PASSWORD: {{ "postgres" | b64enc | quote }}
  {{- end }}
  {{- if not .Values.redis.existingSecret }}
  REDIS_PASSWORD: {{ "" | b64enc | quote }}
  {{- end }}
  JWT_SECRET_KEY: {{ "change-me-in-production-please-change" | b64enc | quote }}
