[package]
name = "physics-collision"
version = "0.1.0"
edition = "2021"

[dependencies]
physics-math = { path = "../physics-math" }
physics-core = { path = "../physics-core" }
physics-spatial = { path = "../physics-spatial" }
nalgebra = { workspace = true }
serde = { workspace = true }
approx = { workspace = true }
slotmap = { workspace = true }
