apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flow-platform
  namespace: flow-platform
spec:
  podSelector:
    matchLabels:
      app: flow-platform
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app: flow-platform
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 3306
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 6379
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 443
          protocol: TCP
