apiVersion: v1
kind: Service
metadata:
  name: chaoslab
  namespace: chaoslab
  labels:
    app: chaoslab
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 3000
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 3000
      protocol: TCP
  selector:
    app: chaoslab
