CREATE TABLE `t_ticket` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `title` varchar(255) NOT NULL COMMENT '工单标题',
  `description` text COMMENT '工单描述',
  `ticket_type` varchar(64) DEFAULT NULL COMMENT '工单类型',
  `priority` int NOT NULL DEFAULT '1' COMMENT '优先级 0低 1中 2高 3紧急',
  `status` int NOT NULL DEFAULT '0' COMMENT '状态 0待处理 1已分配 2处理中 3已解决 4已关闭 5已升级',
  `assignee_id` bigint DEFAULT NULL COMMENT '处理人ID',
  `assignee_name` varchar(128) DEFAULT NULL COMMENT '处理人姓名',
  `reporter_id` bigint DEFAULT NULL COMMENT '报告人ID',
  `reporter_name` varchar(128) DEFAULT NULL COMMENT '报告人姓名',
  `required_skills` varchar(512) DEFAULT NULL COMMENT '所需技能',
  `sla_id` bigint DEFAULT NULL COMMENT 'SLA ID',
  `approval_id` bigint DEFAULT NULL COMMENT '审批ID',
  `attachments` varchar(1024) DEFAULT NULL COMMENT '附件',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记 0未删除 1已删除',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`),
  KEY `idx_assignee_id` (`assignee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单表';

CREATE TABLE `t_ticket_assignment_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `ticket_id` bigint NOT NULL COMMENT '工单ID',
  `from_assignee_id` bigint DEFAULT NULL COMMENT '原处理人ID',
  `from_assignee_name` varchar(128) DEFAULT NULL COMMENT '原处理人姓名',
  `to_assignee_id` bigint DEFAULT NULL COMMENT '新处理人ID',
  `to_assignee_name` varchar(128) DEFAULT NULL COMMENT '新处理人姓名',
  `match_score` int DEFAULT NULL COMMENT '匹配分数',
  `load_before` int DEFAULT NULL COMMENT '分配前负载',
  `load_after` int DEFAULT NULL COMMENT '分配后负载',
  `reason` varchar(512) DEFAULT NULL COMMENT '分配原因',
  `assigned_at` datetime DEFAULT NULL COMMENT '分配时间',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_ticket_id` (`ticket_id`),
  KEY `idx_to_assignee_id` (`to_assignee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单分配日志表';

CREATE TABLE `t_skill` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `skill_name` varchar(128) NOT NULL COMMENT '技能名称',
  `skill_code` varchar(64) NOT NULL COMMENT '技能编码',
  `parent_id` bigint DEFAULT NULL COMMENT '父技能ID',
  `parent_path` varchar(512) DEFAULT NULL COMMENT '父路径',
  `level` int DEFAULT NULL COMMENT '层级',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `description` varchar(512) DEFAULT NULL COMMENT '描述',
  `category` varchar(64) DEFAULT NULL COMMENT '分类',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_code` (`tenant_id`, `skill_code`),
  KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='技能表';

CREATE TABLE `t_employee` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `employee_no` varchar(64) NOT NULL COMMENT '员工编号',
  `name` varchar(128) NOT NULL COMMENT '姓名',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(32) DEFAULT NULL COMMENT '电话',
  `department` varchar(128) DEFAULT NULL COMMENT '部门',
  `position` varchar(128) DEFAULT NULL COMMENT '职位',
  `level` int DEFAULT NULL COMMENT '职级',
  `current_load` int NOT NULL DEFAULT '0' COMMENT '当前负载',
  `max_load` int NOT NULL DEFAULT '10' COMMENT '最大负载',
  `available` int NOT NULL DEFAULT '1' COMMENT '是否可用',
  `skills` varchar(1024) DEFAULT NULL COMMENT '技能列表',
  `working_hours` varchar(255) DEFAULT NULL COMMENT '工作时间',
  `timezone` varchar(64) DEFAULT NULL COMMENT '时区',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_employee_no` (`tenant_id`, `employee_no`),
  KEY `idx_available` (`available`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工表';

CREATE TABLE `t_employee_skill` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `employee_id` bigint NOT NULL COMMENT '员工ID',
  `employee_name` varchar(128) DEFAULT NULL COMMENT '员工姓名',
  `skill_id` bigint NOT NULL COMMENT '技能ID',
  `skill_name` varchar(128) DEFAULT NULL COMMENT '技能名称',
  `proficiency` int DEFAULT NULL COMMENT '熟练度 1-5',
  `experience_years` int DEFAULT NULL COMMENT '经验年数',
  `certification_level` int DEFAULT NULL COMMENT '认证等级',
  `evaluation_score` varchar(255) DEFAULT NULL COMMENT '评估分数',
  `learning_path` varchar(1024) DEFAULT NULL COMMENT '学习路径',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_employee_skill` (`tenant_id`, `employee_id`, `skill_id`),
  KEY `idx_employee_id` (`employee_id`),
  KEY `idx_skill_id` (`skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工技能表';
