CREATE TABLE `t_approval_process` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `process_code` varchar(64) NOT NULL COMMENT '流程编码',
  `process_name` varchar(128) NOT NULL COMMENT '流程名称',
  `business_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `node_config` text COMMENT '节点配置(JSON)',
  `line_config` text COMMENT '连线配置(JSON)',
  `strategy` int NOT NULL DEFAULT '1' COMMENT '审批策略 1或签 2会签',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '是否启用',
  `version` varchar(32) DEFAULT NULL COMMENT '版本',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_process_code` (`tenant_id`, `process_code`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批流程表';

CREATE TABLE `t_approval_instance` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `process_id` varchar(64) NOT NULL COMMENT '流程ID',
  `process_name` varchar(128) DEFAULT NULL COMMENT '流程名称',
  `business_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `business_id` bigint DEFAULT NULL COMMENT '业务ID',
  `title` varchar(255) DEFAULT NULL COMMENT '标题',
  `content` text COMMENT '内容',
  `initiator_id` bigint DEFAULT NULL COMMENT '发起人ID',
  `initiator_name` varchar(128) DEFAULT NULL COMMENT '发起人姓名',
  `status` int NOT NULL DEFAULT '0' COMMENT '状态 0待审批 1已通过 2已拒绝 3已升级 4已取消',
  `current_node_id` bigint DEFAULT NULL COMMENT '当前节点ID',
  `current_node_name` varchar(128) DEFAULT NULL COMMENT '当前节点名称',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `variables` text COMMENT '变量(JSON)',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_process_id` (`process_id`),
  KEY `idx_business` (`business_type`, `business_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批实例表';

CREATE TABLE `t_approval_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `instance_id` bigint NOT NULL COMMENT '实例ID',
  `node_id` bigint DEFAULT NULL COMMENT '节点ID',
  `node_name` varchar(128) DEFAULT NULL COMMENT '节点名称',
  `approver_id` bigint DEFAULT NULL COMMENT '审批人ID',
  `approver_name` varchar(128) DEFAULT NULL COMMENT '审批人姓名',
  `action` int DEFAULT NULL COMMENT '操作 1同意 2拒绝 3转交',
  `comment` varchar(1024) DEFAULT NULL COMMENT '审批意见',
  `operate_time` datetime DEFAULT NULL COMMENT '操作时间',
  `signature` varchar(512) DEFAULT NULL COMMENT '签名',
  `strategy` int DEFAULT NULL COMMENT '审批策略',
  `approve_order` int DEFAULT NULL COMMENT '审批顺序',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_instance_id` (`instance_id`),
  KEY `idx_approver_id` (`approver_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批记录表';

CREATE TABLE `t_tenant` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_code` varchar(64) NOT NULL COMMENT '租户编码',
  `tenant_name` varchar(128) NOT NULL COMMENT '租户名称',
  `contact_person` varchar(64) DEFAULT NULL COMMENT '联系人',
  `contact_email` varchar(128) DEFAULT NULL COMMENT '联系邮箱',
  `contact_phone` varchar(32) DEFAULT NULL COMMENT '联系电话',
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态 0禁用 1启用',
  `industry` varchar(64) DEFAULT NULL COMMENT '行业',
  `account_balance` decimal(12,2) DEFAULT '0.00' COMMENT '账户余额',
  `billing_cycle` varchar(32) DEFAULT 'MONTHLY' COMMENT '计费周期',
  `config_json` text COMMENT '配置(JSON)',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户表';

CREATE TABLE `t_tenant_config` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `config_key` varchar(128) NOT NULL COMMENT '配置键',
  `config_value` text COMMENT '配置值',
  `config_type` varchar(32) DEFAULT 'STRING' COMMENT '配置类型',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_config` (`tenant_id`, `config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户配置表';

CREATE TABLE `t_tenant_quota` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `resource_type` varchar(64) NOT NULL COMMENT '资源类型',
  `quota_limit` bigint NOT NULL DEFAULT '0' COMMENT '配额上限',
  `used_amount` bigint NOT NULL DEFAULT '0' COMMENT '已用量',
  `warning_threshold` bigint DEFAULT NULL COMMENT '警告阈值',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_quota` (`tenant_id`, `resource_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户配额表';
