CREATE TABLE `t_tenant_usage` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `resource_type` varchar(64) NOT NULL COMMENT '资源类型',
  `usage_amount` bigint NOT NULL DEFAULT '0' COMMENT '用量',
  `quota_limit` bigint DEFAULT NULL COMMENT '配额',
  `unit_price` decimal(12,6) DEFAULT NULL COMMENT '单价',
  `total_cost` decimal(12,2) DEFAULT NULL COMMENT '总费用',
  `period_start` datetime DEFAULT NULL COMMENT '周期开始',
  `period_end` datetime DEFAULT NULL COMMENT '周期结束',
  `dimension` varchar(64) DEFAULT NULL COMMENT '维度',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_resource_type` (`resource_type`),
  KEY `idx_period` (`period_start`, `period_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户用量表';

CREATE TABLE `t_billing_invoice` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `invoice_no` varchar(64) NOT NULL COMMENT '发票号',
  `tenant_name` varchar(128) DEFAULT NULL COMMENT '租户名称',
  `total_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '总金额',
  `paid_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '已付金额',
  `status` int NOT NULL DEFAULT '0' COMMENT '状态 0未支付 1已支付 2已逾期 3已作废',
  `billing_period_start` datetime DEFAULT NULL COMMENT '账期开始',
  `billing_period_end` datetime DEFAULT NULL COMMENT '账期结束',
  `due_date` datetime DEFAULT NULL COMMENT '到期日',
  `paid_at` datetime DEFAULT NULL COMMENT '支付时间',
  `items` text COMMENT '明细项(JSON)',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice_no` (`invoice_no`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='账单表';

CREATE TABLE `t_process_definition` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `process_code` varchar(64) NOT NULL COMMENT '流程编码',
  `process_name` varchar(128) NOT NULL COMMENT '流程名称',
  `process_type` varchar(64) DEFAULT NULL COMMENT '流程类型',
  `nodes` text COMMENT '节点配置(JSON)',
  `lines` text COMMENT '连线配置(JSON)',
  `description` varchar(512) DEFAULT NULL COMMENT '描述',
  `version` int NOT NULL DEFAULT '1' COMMENT '版本',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '是否启用',
  `category` varchar(64) DEFAULT NULL COMMENT '分类',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_process_code` (`tenant_id`, `process_code`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程定义表';

CREATE TABLE `t_process_instance` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `definition_id` bigint DEFAULT NULL COMMENT '定义ID',
  `process_code` varchar(64) DEFAULT NULL COMMENT '流程编码',
  `process_name` varchar(128) DEFAULT NULL COMMENT '流程名称',
  `business_id` bigint DEFAULT NULL COMMENT '业务ID',
  `business_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `status` int NOT NULL DEFAULT '0' COMMENT '状态 0运行中 1已完成 2已终止 3已暂停',
  `current_node_id` bigint DEFAULT NULL COMMENT '当前节点ID',
  `variables` text COMMENT '变量(JSON)',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_definition_id` (`definition_id`),
  KEY `idx_business` (`business_type`, `business_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程实例表';

CREATE TABLE `t_process_node` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `definition_id` bigint DEFAULT NULL COMMENT '定义ID',
  `node_code` varchar(64) DEFAULT NULL COMMENT '节点编码',
  `node_name` varchar(128) DEFAULT NULL COMMENT '节点名称',
  `node_type` int DEFAULT NULL COMMENT '节点类型',
  `node_config` text COMMENT '节点配置(JSON)',
  `form_config` text COMMENT '表单配置(JSON)',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `position` varchar(128) DEFAULT NULL COMMENT '位置坐标',
  `style` varchar(255) DEFAULT NULL COMMENT '样式',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_definition_id` (`definition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程节点表';

CREATE TABLE `t_process_line` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `definition_id` bigint DEFAULT NULL COMMENT '定义ID',
  `line_code` varchar(64) DEFAULT NULL COMMENT '连线编码',
  `from_node_id` bigint DEFAULT NULL COMMENT '起始节点ID',
  `to_node_id` bigint DEFAULT NULL COMMENT '目标节点ID',
  `condition_expression` text COMMENT '条件表达式',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `style` varchar(255) DEFAULT NULL COMMENT '样式',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_definition_id` (`definition_id`),
  KEY `idx_from_node` (`from_node_id`),
  KEY `idx_to_node` (`to_node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程连线表';
