CREATE TABLE `t_document` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `document_no` varchar(64) NOT NULL COMMENT '文档编号',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `version` varchar(32) DEFAULT '1.0' COMMENT '版本',
  `category` varchar(64) DEFAULT NULL COMMENT '分类',
  `content` mediumtext COMMENT '内容',
  `file_type` varchar(32) DEFAULT NULL COMMENT '文件类型',
  `file_url` varchar(512) DEFAULT NULL COMMENT '文件地址',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小',
  `md5` varchar(64) DEFAULT NULL COMMENT 'MD5',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_document_no` (`tenant_id`, `document_no`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档表';

CREATE TABLE `t_document_compare` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `left_document_id` bigint DEFAULT NULL COMMENT '左侧文档ID',
  `left_title` varchar(255) DEFAULT NULL COMMENT '左侧标题',
  `left_version` varchar(32) DEFAULT NULL COMMENT '左侧版本',
  `right_document_id` bigint DEFAULT NULL COMMENT '右侧文档ID',
  `right_title` varchar(255) DEFAULT NULL COMMENT '右侧标题',
  `right_version` varchar(32) DEFAULT NULL COMMENT '右侧版本',
  `diff_result` mediumtext COMMENT '差异结果(JSON)',
  `change_summary` text COMMENT '变更摘要',
  `key_clauses` text COMMENT '关键条款(JSON)',
  `similarity` int DEFAULT NULL COMMENT '相似度 0-100',
  `compared_at` datetime DEFAULT NULL COMMENT '对比时间',
  `compare_options` varchar(1024) DEFAULT NULL COMMENT '对比选项(JSON)',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_left_doc` (`left_document_id`),
  `idx_right_doc` (`right_document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档对比表';

CREATE TABLE `t_sla_policy` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `policy_code` varchar(64) NOT NULL COMMENT '策略编码',
  `policy_name` varchar(128) NOT NULL COMMENT '策略名称',
  `related_type` varchar(64) DEFAULT NULL COMMENT '关联类型',
  `response_time` bigint NOT NULL DEFAULT '3600' COMMENT '响应时间(秒)',
  `resolution_time` bigint NOT NULL DEFAULT '86400' COMMENT '解决时间(秒)',
  `warning_time` bigint DEFAULT NULL COMMENT '预警时间(秒)',
  `escalation_level` int NOT NULL DEFAULT '0' COMMENT '升级级别',
  `escalation_rules` text COMMENT '升级规则(JSON)',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '是否启用',
  `description` varchar(512) DEFAULT NULL COMMENT '描述',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_policy_code` (`tenant_id`, `policy_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SLA策略表';

CREATE TABLE `t_sla_tracking` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `policy_id` bigint DEFAULT NULL COMMENT '策略ID',
  `policy_name` varchar(128) DEFAULT NULL COMMENT '策略名称',
  `related_id` bigint DEFAULT NULL COMMENT '关联ID',
  `related_type` varchar(64) DEFAULT NULL COMMENT '关联类型',
  `sla_status` int NOT NULL DEFAULT '0' COMMENT 'SLA状态 0正常 1预警 2超时',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `deadline` datetime DEFAULT NULL COMMENT '截止时间',
  `warning_time` datetime DEFAULT NULL COMMENT '预警时间',
  `remaining_time` bigint DEFAULT NULL COMMENT '剩余时间(秒)',
  `escalation_level` int NOT NULL DEFAULT '0' COMMENT '当前升级级别',
  `last_escalated_at` datetime DEFAULT NULL COMMENT '最后升级时间',
  `escalation_history` text COMMENT '升级历史(JSON)',
  `related_data` text COMMENT '关联数据(JSON)',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_related` (`related_type`, `related_id`),
  KEY `idx_sla_status` (`sla_status`),
  KEY `idx_deadline` (`deadline`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SLA追踪表';

CREATE TABLE `t_sla_notification` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `tracking_id` bigint DEFAULT NULL COMMENT '追踪ID',
  `related_id` bigint DEFAULT NULL COMMENT '关联ID',
  `related_type` varchar(64) DEFAULT NULL COMMENT '关联类型',
  `notification_type` int DEFAULT NULL COMMENT '通知类型 1预警 2超时 3升级',
  `recipient_id` bigint DEFAULT NULL COMMENT '接收人ID',
  `recipient_name` varchar(128) DEFAULT NULL COMMENT '接收人姓名',
  `content` text COMMENT '通知内容',
  `status` int NOT NULL DEFAULT '0' COMMENT '状态 0未发送 1已发送 2发送失败',
  `sent_at` datetime DEFAULT NULL COMMENT '发送时间',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_tracking_id` (`tracking_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SLA通知表';
