export const IPC_CHANNELS = {
  FILE: {
    READ: 'file:read',
    WRITE: 'file:write',
    DELETE: 'file:delete',
    LIST: 'file:list',
    WATCH: 'file:watch',
    RENAME: 'file:rename',
    EXISTS: 'file:exists',
    CHANGED: 'file:changed',
  },
  DOCUMENT: {
    CREATE: 'document:create',
    GET: 'document:get',
    LIST: 'document:list',
    UPDATE: 'document:update',
    DELETE: 'document:delete',
  },
  TAG: {
    LIST: 'tag:list',
  },
  GIT: {
    INIT: 'git:init',
    STATUS: 'git:status',
    COMMIT: 'git:commit',
    PUSH: 'git:push',
    PULL: 'git:pull',
    LOG: 'git:log',
    DIFF: 'git:diff',
    CLONE: 'git:clone',
    CONFIG_GET: 'git:config:get',
    CONFIG_SET: 'git:config:set',
    REMOTE_SET: 'git:remote:set',
    COMMITTED: 'git:committed',
  },
  DB: {
    DOCUMENT_UPSERT: 'db:document:upsert',
    DOCUMENT_GET: 'db:document:get',
    DOCUMENT_GET_BY_PATH: 'db:document:getByPath',
    DOCUMENT_LIST: 'db:document:list',
    DOCUMENT_DELETE: 'db:document:delete',
    DOCUMENT_SEARCH: 'db:document:search',
    TAG_LIST: 'db:tag:list',
    TAG_GET_DOCUMENTS: 'db:tag:getDocuments',
    BACKLINK_GET: 'db:backlink:get',
    BACKLINK_GET_TO: 'db:backlink:getTo',
    STATS_GET: 'db:stats:get',
  },
  SEARCH: {
    QUERY: 'search:query',
    REINDEX: 'search:reindex',
    INDEX_DOCUMENT: 'search:index:document',
    REMOVE_DOCUMENT: 'search:remove:document',
  },
  TEMPLATE: {
    LIST: 'template:list',
    GET: 'template:get',
    GET_VARIABLES: 'template:getVariables',
    RENDER: 'template:render',
    CREATE: 'template:create',
    SAVE: 'template:save',
    DELETE: 'template:delete',
  },
  IMPORT: {
    FROM_ZIP: 'import:fromZip',
    FROM_DIR: 'import:fromDir',
    SELECT_FILE: 'import:selectFile',
    SELECT_DIR: 'import:selectDir',
  },
  PLUGIN: {
    LIST: 'plugin:list',
    INSTALL: 'plugin:install',
    UNINSTALL: 'plugin:uninstall',
    ENABLE: 'plugin:enable',
    DISABLE: 'plugin:disable',
    GET_SETTINGS: 'plugin:settings:get',
    SET_SETTINGS: 'plugin:settings:set',
  },
  SETTINGS: {
    GET: 'settings:get',
    SET: 'settings:set',
  },
  EXPORT: {
    STATIC_SITE: 'export:staticSite',
    MARKDOWN: 'export:markdown',
  },
  APP: {
    GET_SETTINGS: 'app:settings:get',
    SET_SETTINGS: 'app:settings:set',
    GET_INITIALIZED: 'app:initialized',
    INITIALIZE: 'app:initialize',
    OPEN_EXTERNAL: 'app:openExternal',
    SHOW_ITEM_IN_FOLDER: 'app:showItemInFolder',
  },
} as const;

export type IPCChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS][keyof typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS]];
