const Document = require('../models/Document');
const Version = require('../models/Version');
const puppeteer = require('puppeteer');
const path = require('path');
const fs = require('fs');
const _ = require('lodash');

class ExportService {
  constructor() {
    this.browser = null;
    this.tempDir = path.join(process.cwd(), 'temp');
  }

  async init() {
    try {
      if (!fs.existsSync(this.tempDir)) {
        fs.mkdirSync(this.tempDir, { recursive: true });
      }
      
      this.browser = await puppeteer.launch({
        headless: 'new',
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu'
        ]
      });
      
      console.log('Puppeteer browser initialized');
    } catch (error) {
      console.warn('Puppeteer initialization failed, PDF export may not work:', error.message);
      this.browser = null;
    }
  }

  async getBrowser() {
    if (!this.browser) {
      await this.init();
    }
    return this.browser;
  }

  async exportToHTML(doc_id, options = {}) {
    const { version_number, include_comments = false, include_toc = true } = options;
    
    let doc;
    if (version_number) {
      const version = await Version.findOne({ doc_id, version_number });
      if (!version) {
        throw new Error(`Version ${version_number} not found for document ${doc_id}`);
      }
      doc = {
        title: version.title_snapshot,
        content: version.content_snapshot,
        doc_id
      };
    } else {
      doc = await Document.findOne({ doc_id });
      if (!doc) {
        throw new Error(`Document not found: ${doc_id}`);
      }
    }
    
    const htmlContent = this.generateHTML(doc, { include_comments, include_toc });
    
    const tempFile = path.join(this.tempDir, `${doc_id}_${Date.now()}.html`);
    fs.writeFileSync(tempFile, htmlContent, 'utf-8');
    
    return {
      format: 'html',
      filename: `${doc.title}.html`,
      content: htmlContent,
      temp_file: tempFile,
      size: Buffer.byteLength(htmlContent, 'utf-8')
    };
  }

  async exportToPDF(doc_id, options = {}) {
    const { 
      version_number, 
      include_comments = false, 
      include_toc = true,
      format = 'A4',
      orientation = 'portrait',
      margin = { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' }
    } = options;
    
    const htmlResult = await this.exportToHTML(doc_id, { 
      version_number, 
      include_comments, 
      include_toc 
    });
    
    const browser = await this.getBrowser();
    
    if (!browser) {
      throw new Error('Puppeteer not available, cannot export to PDF');
    }
    
    const page = await browser.newPage();
    
    try {
      await page.setContent(htmlResult.content, {
        waitUntil: 'networkidle0'
      });
      
      const pdfBuffer = await page.pdf({
        format,
        landscape: orientation === 'landscape',
        margin,
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: `
          <div style="font-size: 10px; padding: 5px 20px; width: 100%; border-bottom: 1px solid #ccc;">
            <span class="title" style="float: left;">${htmlResult.filename.replace('.html', '')}</span>
            <span style="float: right;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          </div>
        `,
        footerTemplate: `
          <div style="font-size: 10px; padding: 5px 20px; width: 100%; border-top: 1px solid #ccc;">
            <span style="float: left;">Generated by WikiHub</span>
            <span style="float: right;">${new Date().toLocaleDateString()}</span>
          </div>
        `
      });
      
      const tempFile = path.join(this.tempDir, `${doc_id}_${Date.now()}.pdf`);
      fs.writeFileSync(tempFile, pdfBuffer);
      
      return {
        format: 'pdf',
        filename: `${htmlResult.filename.replace('.html', '')}.pdf`,
        content: pdfBuffer,
        temp_file: tempFile,
        size: pdfBuffer.length,
        options: { format, orientation, margin }
      };
    } finally {
      await page.close();
    }
  }

  generateHTML(doc, options = {}) {
    const { include_toc = true } = options;
    const title = doc.title || 'Untitled Document';
    
    const styledContent = this.markdownToHTML(doc.content || '');
    const toc = include_toc ? this.generateTOC(doc.content || '') : '';
    
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - WikiHub Export</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      padding: 40px;
      max-width: 900px;
      margin: 0 auto;
    }
    
    h1 {
      font-size: 2.5em;
      margin-bottom: 0.5em;
      color: #1a1a1a;
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 0.3em;
    }
    
    h2 {
      font-size: 1.8em;
      margin-top: 1.5em;
      margin-bottom: 0.8em;
      color: #2c3e50;
      border-bottom: 1px solid #e0e0e0;
      padding-bottom: 0.2em;
    }
    
    h3 {
      font-size: 1.4em;
      margin-top: 1.2em;
      margin-bottom: 0.6em;
      color: #34495e;
    }
    
    h4, h5, h6 {
      font-size: 1.1em;
      margin-top: 1em;
      margin-bottom: 0.5em;
      color: #555;
    }
    
    p {
      margin-bottom: 1em;
      text-align: justify;
    }
    
    ul, ol {
      margin-bottom: 1em;
      padding-left: 2em;
    }
    
    li {
      margin-bottom: 0.3em;
    }
    
    blockquote {
      border-left: 4px solid #3b82f6;
      padding-left: 1em;
      margin: 1em 0;
      color: #666;
      background: #f8f9fa;
      padding: 1em;
      border-radius: 0 4px 4px 0;
    }
    
    pre {
      background: #1e1e1e;
      color: #d4d4d4;
      padding: 1em;
      border-radius: 4px;
      overflow-x: auto;
      margin: 1em 0;
    }
    
    code {
      font-family: 'Fira Code', 'Consolas', monospace;
      font-size: 0.9em;
    }
    
    p > code, li > code {
      background: #f1f3f5;
      padding: 0.2em 0.4em;
      border-radius: 3px;
      color: #e74c3c;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1em 0;
    }
    
    th, td {
      border: 1px solid #ddd;
      padding: 0.8em;
      text-align: left;
    }
    
    th {
      background: #f8f9fa;
      font-weight: 600;
    }
    
    tr:nth-child(even) {
      background: #f8f9fa;
    }
    
    tr:hover {
      background: #e9ecef;
    }
    
    hr {
      border: none;
      border-top: 1px solid #e0e0e0;
      margin: 2em 0;
    }
    
    a {
      color: #3b82f6;
      text-decoration: none;
    }
    
    a:hover {
      text-decoration: underline;
    }
    
    img {
      max-width: 100%;
      height: auto;
      display: block;
      margin: 1em auto;
      border-radius: 4px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    
    .toc {
      background: #f8f9fa;
      border: 1px solid #e0e0e0;
      border-radius: 4px;
      padding: 1.5em;
      margin: 2em 0;
    }
    
    .toc-title {
      font-weight: 600;
      font-size: 1.1em;
      margin-bottom: 1em;
      color: #2c3e50;
    }
    
    .toc ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }
    
    .toc li {
      margin: 0.3em 0;
    }
    
    .toc li a {
      display: block;
      padding: 0.2em 0;
    }
    
    .toc-level-1 { padding-left: 0; }
    .toc-level-2 { padding-left: 1.5em; }
    .toc-level-3 { padding-left: 3em; }
    
    em {
      font-style: italic;
    }
    
    strong {
      font-weight: 600;
    }
    
    del {
      text-decoration: line-through;
      color: #999;
    }
    
    @media print {
      body {
        padding: 0;
        font-size: 12px;
      }
      
      h1 {
        font-size: 2em;
      }
      
      h2 {
        font-size: 1.5em;
      }
      
      .page-break {
        page-break-before: always;
      }
    }
  </style>
</head>
<body>
  <h1>${this.escapeHTML(title)}</h1>
  
  ${toc}
  
  <div class="content">
    ${styledContent}
  </div>
  
  <hr>
  <p style="text-align: center; color: #999; font-size: 0.9em;">
    Generated by WikiHub Knowledge Base Platform
  </p>
</body>
</html>
`;

    return html;
  }

  markdownToHTML(markdown) {
    if (!markdown) return '';
    
    let html = markdown;
    
    html = html.replace(/^```(\w+)?\n([\s\S]*?)^```$/gm, (match, lang, code) => {
      const langClass = lang ? ` class="language-${lang}"` : '';
      return `<pre><code${langClass}>${this.escapeHTML(code.trim())}</code></pre>`;
    });
    
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
    
    html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
    html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
    html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
    
    html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
    html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
    html = html.replace(/___(.+?)___/g, '<strong><em>$1</em></strong>');
    html = html.replace(/__(.+?)__/g, '<strong>$1</strong>');
    html = html.replace(/_(.+?)_/g, '<em>$1</em>');
    
    html = html.replace(/~~(.+?)~~/g, '<del>$1</del>');
    
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
    html = html.replace(/<([^>]+)>/g, '<a href="$1">$1</a>');
    
    html = html.replace(/^!\[([^\]]*)\]\(([^)]+)\)(?:\s*"([^"]+)")?$/gm, 
      '<img src="$2" alt="$1" title="$3">');
    
    const lines = html.split('\n');
    const result = [];
    let inList = false;
    let listType = null;
    
    for (let i = 0; i < lines.length; i++) {
      let line = lines[i];
      
      if (line.match(/^\d+\.\s/)) {
        if (!inList || listType !== 'ol') {
          if (inList) result.push(`</${listType}>`);
          result.push('<ol>');
          inList = true;
          listType = 'ol';
        }
        line = '<li>' + line.replace(/^\d+\.\s*/, '') + '</li>';
      } else if (line.match(/^[-*+]\s/)) {
        if (!inList || listType !== 'ul') {
          if (inList) result.push(`</${listType}>`);
          result.push('<ul>');
          inList = true;
          listType = 'ul';
        }
        line = '<li>' + line.replace(/^[-*+]\s*/, '') + '</li>';
      } else if (line.match(/^>\s/)) {
        if (inList) {
          result.push(`</${listType}>`);
          inList = false;
        }
        line = '<blockquote>' + line.replace(/^>\s*/, '') + '</blockquote>';
      } else if (line.match(/^\|.+\|$/)) {
        if (inList) {
          result.push(`</${listType}>`);
          inList = false;
        }
        const tableLines = [line];
        let j = i + 1;
        while (j < lines.length && lines[j].match(/^\|.+\|$/)) {
          tableLines.push(lines[j]);
          j++;
        }
        i = j - 1;
        const tableHTML = this.parseTable(tableLines);
        result.push(tableHTML);
        continue;
      } else if (line.trim() === '') {
        if (inList) {
          result.push(`</${listType}>`);
          inList = false;
        }
        line = '';
      } else if (!line.startsWith('<')) {
        if (inList) {
          result.push(`</${listType}>`);
          inList = false;
        }
        line = '<p>' + line + '</p>';
      }
      
      if (line) result.push(line);
    }
    
    if (inList) result.push(`</${listType}>`);
    
    return result.join('\n');
  }

  parseTable(lines) {
    if (lines.length < 2) return '';
    
    const headers = lines[0].split('|').filter(h => h.trim() !== '');
    const separator = lines[1].split('|').filter(s => s.trim() !== '');
    
    const alignments = separator.map(s => {
      if (s.match(/^:.*:$/)) return 'center';
      if (s.match(/^:.*/)) return 'left';
      if (s.match(/.*:$/)) return 'right';
      return 'left';
    });
    
    const rows = [];
    for (let i = 2; i < lines.length; i++) {
      const cells = lines[i].split('|').filter(c => c.trim() !== '');
      if (cells.length > 0) {
        rows.push(cells);
      }
    }
    
    let html = '<table><thead><tr>';
    headers.forEach((h, i) => {
      const align = alignments[i] ? ` style="text-align: ${alignments[i]}"` : '';
      html += `<th${align}>${h.trim()}</th>`;
    });
    html += '</tr></thead><tbody>';
    
    rows.forEach(row => {
      html += '<tr>';
      row.forEach((cell, i) => {
        const align = alignments[i] ? ` style="text-align: ${alignments[i]}"` : '';
        html += `<td${align}>${cell.trim()}</td>`;
      });
      html += '</tr>';
    });
    
    html += '</tbody></table>';
    return html;
  }

  generateTOC(content) {
    const headings = [];
    const regex = /^(#{1,6})\s+(.+)$/gm;
    let match;
    
    while ((match = regex.exec(content)) !== null) {
      const level = match[1].length;
      const text = match[2];
      headings.push({ level, text });
    }
    
    if (headings.length === 0) return '';
    
    let toc = '<div class="toc"><div class="toc-title">Table of Contents</div><ul>';
    
    headings.forEach((h, index) => {
      toc += `<li class="toc-level-${h.level}"><a href="#section-${index}">${this.escapeHTML(h.text)}</a></li>`;
    });
    
    toc += '</ul></div>';
    return toc;
  }

  escapeHTML(text) {
    if (!text) return '';
    const replacements = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;'
    };
    return text.replace(/[&<>"']/g, char => replacements[char]);
  }

  async batchExport(doc_ids, format = 'html', options = {}) {
    const results = [];
    
    for (const doc_id of doc_ids) {
      try {
        let result;
        if (format === 'pdf') {
          result = await this.exportToPDF(doc_id, options);
        } else {
          result = await this.exportToHTML(doc_id, options);
        }
        results.push({
          doc_id,
          success: true,
          ...result
        });
      } catch (error) {
        results.push({
          doc_id,
          success: false,
          error: error.message
        });
      }
    }
    
    return results;
  }

  cleanupTempFiles() {
    try {
      if (fs.existsSync(this.tempDir)) {
        const files = fs.readdirSync(this.tempDir);
        const now = Date.now();
        const maxAge = 24 * 60 * 60 * 1000;
        
        for (const file of files) {
          const filePath = path.join(this.tempDir, file);
          const stats = fs.statSync(filePath);
          
          if (now - stats.mtimeMs > maxAge) {
            fs.unlinkSync(filePath);
            console.log(`Deleted temp file: ${file}`);
          }
        }
      }
    } catch (error) {
      console.error('Cleanup temp files failed:', error.message);
    }
  }

  async close() {
    if (this.browser) {
      await this.browser.close();
      this.browser = null;
      console.log('Puppeteer browser closed');
    }
  }
}

module.exports = new ExportService();
