app = "auction-frontend-prod"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile.frontend"

[deploy]
  strategy = "bluegreen"

[env]
  API_BASE_URL = "https://auction-api-prod.fly.dev/api/v1"

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 200
    soft_limit = 100
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.vm]]
    size = "shared-cpu-1x"
    memory = "256mb"
