CREATE TABLE IF NOT EXISTS `task_execution` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` VARCHAR(64) NOT NULL COMMENT '任务ID',
    `task_type` VARCHAR(32) NOT NULL COMMENT '任务类型',
    `status` VARCHAR(32) NOT NULL COMMENT '任务状态',
    `input_data` TEXT COMMENT '输入数据',
    `output_data` TEXT COMMENT '输出数据',
    `error_message` TEXT COMMENT '错误信息',
    `retry_count` INT DEFAULT 0 COMMENT '重试次数',
    `priority` INT DEFAULT 0 COMMENT '优先级',
    `scheduled_time` DATETIME COMMENT '调度时间',
    `start_time` DATETIME COMMENT '开始时间',
    `end_time` DATETIME COMMENT '结束时间',
    `created_by` VARCHAR(64) COMMENT '创建人',
    `updated_by` VARCHAR(64) COMMENT '更新人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `version` INT DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_id` (`task_id`),
    KEY `idx_status` (`status`),
    KEY `idx_task_type` (`task_type`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务执行表';

CREATE TABLE IF NOT EXISTS `gas_estimation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `network` VARCHAR(32) NOT NULL COMMENT '网络名称',
    `gas_price_low` DECIMAL(30, 0) COMMENT '低Gas价格',
    `gas_price_medium` DECIMAL(30, 0) COMMENT '中Gas价格',
    `gas_price_high` DECIMAL(30, 0) COMMENT '高Gas价格',
    `base_fee` DECIMAL(30, 0) COMMENT '基础费用',
    `priority_fee_low` DECIMAL(30, 0) COMMENT '低优先级费用',
    `priority_fee_medium` DECIMAL(30, 0) COMMENT '中优先级费用',
    `priority_fee_high` DECIMAL(30, 0) COMMENT '高优先级费用',
    `pending_transactions` INT COMMENT '待处理交易数',
    `block_gas_used` BIGINT COMMENT '区块Gas使用量',
    `block_gas_limit` BIGINT COMMENT '区块Gas限制',
    `latest_block` BIGINT COMMENT '最新区块号',
    `timestamp` BIGINT NOT NULL COMMENT '时间戳',
    `signature` VARCHAR(256) COMMENT '签名',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    KEY `idx_chain_id` (`chain_id`),
    KEY `idx_timestamp` (`timestamp`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gas预估表';

CREATE TABLE IF NOT EXISTS `gas_history` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `block_number` BIGINT NOT NULL COMMENT '区块号',
    `gas_price` DECIMAL(30, 0) NOT NULL COMMENT 'Gas价格',
    `base_fee` DECIMAL(30, 0) COMMENT '基础费用',
    `priority_fee` DECIMAL(30, 0) COMMENT '优先级费用',
    `gas_used` BIGINT COMMENT 'Gas使用量',
    `gas_limit` BIGINT COMMENT 'Gas限制',
    `transaction_count` INT COMMENT '交易数量',
    `block_time` DATETIME COMMENT '区块时间',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_chain_block` (`chain_id`, `block_number`),
    KEY `idx_block_time` (`block_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gas历史数据表';

CREATE TABLE IF NOT EXISTS `storage_content` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `content_id` VARCHAR(128) NOT NULL COMMENT '内容ID(CID)',
    `content_hash` VARCHAR(128) COMMENT '内容哈希',
    `storage_type` VARCHAR(32) NOT NULL COMMENT '存储类型:IPFS/ARWEAVE/FILECOIN',
    `network` VARCHAR(32) NOT NULL COMMENT '网络',
    `size` BIGINT COMMENT '内容大小',
    `mime_type` VARCHAR(128) COMMENT 'MIME类型',
    `pin_status` VARCHAR(32) COMMENT 'Pin状态',
    `pin_location` VARCHAR(256) COMMENT 'Pin位置',
    `replication_count` INT DEFAULT 0 COMMENT '复制数量',
    `expire_time` DATETIME COMMENT '过期时间',
    `metadata` TEXT COMMENT '元数据(JSON)',
    `created_by` VARCHAR(64) COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_content_id` (`content_id`),
    KEY `idx_storage_type` (`storage_type`),
    KEY `idx_pin_status` (`pin_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='存储内容表';

CREATE TABLE IF NOT EXISTS `transaction_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tx_hash` VARCHAR(128) NOT NULL COMMENT '交易哈希',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `from_address` VARCHAR(128) COMMENT '发送地址',
    `to_address` VARCHAR(128) COMMENT '接收地址',
    `value` DECIMAL(50, 0) COMMENT '交易金额',
    `gas_limit` BIGINT COMMENT 'Gas限制',
    `gas_price` DECIMAL(30, 0) COMMENT 'Gas价格',
    `gas_used` BIGINT COMMENT '使用的Gas',
    `nonce` BIGINT COMMENT 'Nonce',
    `data` TEXT COMMENT '交易数据',
    `status` VARCHAR(32) NOT NULL COMMENT '交易状态',
    `block_number` BIGINT COMMENT '区块号',
    `block_hash` VARCHAR(128) COMMENT '区块哈希',
    `transaction_index` INT COMMENT '交易索引',
    `signature` VARCHAR(512) COMMENT '签名',
    `signers` TEXT COMMENT '签名者列表(JSON)',
    `multisig_strategy` VARCHAR(32) COMMENT '多签策略',
    `error_message` TEXT COMMENT '错误信息',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tx_hash` (`tx_hash`),
    KEY `idx_chain_id` (`chain_id`),
    KEY `idx_from_address` (`from_address`),
    KEY `idx_status` (`status`),
    KEY `idx_block_number` (`block_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易记录表';

CREATE TABLE IF NOT EXISTS `rpc_node` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `node_id` VARCHAR(64) NOT NULL COMMENT '节点ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `network` VARCHAR(32) NOT NULL COMMENT '网络',
    `name` VARCHAR(128) COMMENT '节点名称',
    `url` VARCHAR(512) NOT NULL COMMENT 'RPC URL',
    `ws_url` VARCHAR(512) COMMENT 'WebSocket URL',
    `node_type` VARCHAR(32) COMMENT '节点类型:ARCHIVE/FULL/LIGHT',
    `priority` INT DEFAULT 0 COMMENT '优先级',
    `weight` INT DEFAULT 1 COMMENT '权重',
    `health_status` VARCHAR(32) COMMENT '健康状态',
    `latency` BIGINT COMMENT '延迟(ms)',
    `last_checked` DATETIME COMMENT '最后检查时间',
    `failure_count` INT DEFAULT 0 COMMENT '失败次数',
    `api_key` VARCHAR(256) COMMENT 'API Key',
    `max_requests_per_second` INT COMMENT '每秒最大请求数',
    `is_default` TINYINT DEFAULT 0 COMMENT '是否默认节点',
    `is_enabled` TINYINT DEFAULT 1 COMMENT '是否启用',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_node_id` (`node_id`),
    KEY `idx_chain_id` (`chain_id`),
    KEY `idx_health_status` (`health_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RPC节点表';

CREATE TABLE IF NOT EXISTS `block_data` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `block_number` BIGINT NOT NULL COMMENT '区块号',
    `block_hash` VARCHAR(128) NOT NULL COMMENT '区块哈希',
    `parent_hash` VARCHAR(128) COMMENT '父区块哈希',
    `timestamp` BIGINT NOT NULL COMMENT '区块时间戳',
    `miner` VARCHAR(128) COMMENT '矿工',
    `difficulty` VARCHAR(64) COMMENT '难度',
    `total_difficulty` VARCHAR(64) COMMENT '总难度',
    `gas_used` BIGINT COMMENT '使用的Gas',
    `gas_limit` BIGINT COMMENT 'Gas限制',
    `size` BIGINT COMMENT '区块大小',
    `transaction_count` INT COMMENT '交易数量',
    `base_fee_per_gas` DECIMAL(30, 0) COMMENT '基础费用',
    `extra_data` TEXT COMMENT '额外数据',
    `raw_data` TEXT COMMENT '原始数据(JSON)',
    `index_status` VARCHAR(32) COMMENT '索引状态',
    `indexed_at` DATETIME COMMENT '索引时间',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_chain_block` (`chain_id`, `block_number`),
    UNIQUE KEY `uk_block_hash` (`block_hash`),
    KEY `idx_timestamp` (`timestamp`),
    KEY `idx_index_status` (`index_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='区块数据表';

CREATE TABLE IF NOT EXISTS `transaction_index` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `tx_hash` VARCHAR(128) NOT NULL COMMENT '交易哈希',
    `block_number` BIGINT NOT NULL COMMENT '区块号',
    `block_hash` VARCHAR(128) NOT NULL COMMENT '区块哈希',
    `transaction_index` INT NOT NULL COMMENT '交易索引',
    `from_address` VARCHAR(128) COMMENT '发送地址',
    `to_address` VARCHAR(128) COMMENT '接收地址',
    `contract_address` VARCHAR(128) COMMENT '合约地址',
    `tx_type` VARCHAR(32) COMMENT '交易类型',
    `value` DECIMAL(50, 0) COMMENT '交易金额',
    `gas_price` DECIMAL(30, 0) COMMENT 'Gas价格',
    `gas_limit` BIGINT COMMENT 'Gas限制',
    `gas_used` BIGINT COMMENT '使用的Gas',
    `fee` DECIMAL(50, 0) COMMENT '手续费',
    `status` VARCHAR(32) COMMENT '状态',
    `method_id` VARCHAR(16) COMMENT '方法ID',
    `method_name` VARCHAR(64) COMMENT '方法名称',
    `timestamp` BIGINT NOT NULL COMMENT '时间戳',
    `input_data` TEXT COMMENT '输入数据',
    `events` TEXT COMMENT '事件列表(JSON)',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tx_hash` (`tx_hash`),
    KEY `idx_chain_id` (`chain_id`),
    KEY `idx_from_address` (`from_address`),
    KEY `idx_to_address` (`to_address`),
    KEY `idx_contract_address` (`contract_address`),
    KEY `idx_block_number` (`block_number`),
    KEY `idx_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易索引表';

CREATE TABLE IF NOT EXISTS `event_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `contract_address` VARCHAR(128) NOT NULL COMMENT '合约地址',
    `event_name` VARCHAR(64) COMMENT '事件名称',
    `event_signature` VARCHAR(128) COMMENT '事件签名',
    `topic0` VARCHAR(128) COMMENT '主题0',
    `topic1` VARCHAR(128) COMMENT '主题1',
    `topic2` VARCHAR(128) COMMENT '主题2',
    `topic3` VARCHAR(128) COMMENT '主题3',
    `data` TEXT COMMENT '事件数据',
    `decoded_data` TEXT COMMENT '解码后的数据(JSON)',
    `tx_hash` VARCHAR(128) NOT NULL COMMENT '交易哈希',
    `block_number` BIGINT NOT NULL COMMENT '区块号',
    `block_hash` VARCHAR(128) NOT NULL COMMENT '区块哈希',
    `log_index` INT NOT NULL COMMENT '日志索引',
    `transaction_index` INT COMMENT '交易索引',
    `timestamp` BIGINT NOT NULL COMMENT '时间戳',
    `processed` TINYINT DEFAULT 0 COMMENT '是否已处理',
    `processed_at` DATETIME COMMENT '处理时间',
    `callback_status` VARCHAR(32) COMMENT '回调状态',
    `callback_error` TEXT COMMENT '回调错误信息',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_chain_tx_log` (`chain_id`, `tx_hash`, `log_index`),
    KEY `idx_contract_address` (`contract_address`),
    KEY `idx_event_signature` (`event_signature`),
    KEY `idx_block_number` (`block_number`),
    KEY `idx_processed` (`processed`),
    KEY `idx_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='事件日志表';

CREATE TABLE IF NOT EXISTS `zkp_proof` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `proof_id` VARCHAR(64) NOT NULL COMMENT '证明ID',
    `proof_type` VARCHAR(32) NOT NULL COMMENT '证明类型:GROTH16/PLONK/FFLONK',
    `circuit_id` VARCHAR(64) COMMENT '电路ID',
    `circuit_version` VARCHAR(32) COMMENT '电路版本',
    `public_inputs` TEXT COMMENT '公开输入(JSON)',
    `proof_data` TEXT NOT NULL COMMENT '证明数据(JSON)',
    `verification_key` TEXT COMMENT '验证密钥(JSON)',
    `verification_result` TINYINT COMMENT '验证结果',
    `verification_time` BIGINT COMMENT '验证时间(ms)',
    `verification_error` TEXT COMMENT '验证错误信息',
    `verifier` VARCHAR(128) COMMENT '验证者',
    `verified_at` DATETIME COMMENT '验证时间',
    `chain_verified` TINYINT DEFAULT 0 COMMENT '是否链上验证',
    `tx_hash` VARCHAR(128) COMMENT '链上验证交易哈希',
    `metadata` TEXT COMMENT '元数据(JSON)',
    `created_by` VARCHAR(64) COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_proof_id` (`proof_id`),
    KEY `idx_proof_type` (`proof_type`),
    KEY `idx_verification_result` (`verification_result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZKP证明表';

CREATE TABLE IF NOT EXISTS `multisig_wallet` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `wallet_id` VARCHAR(64) NOT NULL COMMENT '钱包ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `wallet_address` VARCHAR(128) NOT NULL COMMENT '钱包地址',
    `wallet_type` VARCHAR(32) NOT NULL COMMENT '钱包类型:GNOSIS_SAFE/SAFE_MULTISIG',
    `name` VARCHAR(128) COMMENT '钱包名称',
    `threshold` INT NOT NULL COMMENT '签名阈值',
    `owners` TEXT NOT NULL COMMENT '所有者列表(JSON)',
    `owner_count` INT NOT NULL COMMENT '所有者数量',
    `version` VARCHAR(32) COMMENT '版本',
    `nonce` BIGINT DEFAULT 0 COMMENT '当前Nonce',
    `creation_tx_hash` VARCHAR(128) COMMENT '创建交易哈希',
    `creation_block` BIGINT COMMENT '创建区块',
    `status` VARCHAR(32) COMMENT '状态',
    `metadata` TEXT COMMENT '元数据(JSON)',
    `created_by` VARCHAR(64) COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_wallet_id` (`wallet_id`),
    UNIQUE KEY `uk_chain_address` (`chain_id`, `wallet_address`),
    KEY `idx_wallet_type` (`wallet_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多签钱包表';

CREATE TABLE IF NOT EXISTS `multisig_proposal` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `proposal_id` VARCHAR(64) NOT NULL COMMENT '提案ID',
    `wallet_id` VARCHAR(64) NOT NULL COMMENT '钱包ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `proposal_type` VARCHAR(32) NOT NULL COMMENT '提案类型',
    `title` VARCHAR(256) COMMENT '标题',
    `description` TEXT COMMENT '描述',
    `to_address` VARCHAR(128) NOT NULL COMMENT '目标地址',
    `value` DECIMAL(50, 0) DEFAULT 0 COMMENT '转账金额',
    `data` TEXT COMMENT '交易数据',
    `operation` INT DEFAULT 0 COMMENT '操作类型',
    `safe_tx_gas` BIGINT COMMENT 'Safe交易Gas',
    `base_gas` BIGINT COMMENT '基础Gas',
    `gas_price` DECIMAL(30, 0) COMMENT 'Gas价格',
    `gas_token` VARCHAR(128) COMMENT 'Gas代币',
    `refund_receiver` VARCHAR(128) COMMENT '退款接收者',
    `nonce` BIGINT NOT NULL COMMENT 'Nonce',
    `safe_tx_hash` VARCHAR(128) COMMENT 'Safe交易哈希',
    `signatures` TEXT COMMENT '签名列表(JSON)',
    `signature_count` INT DEFAULT 0 COMMENT '签名数量',
    `threshold` INT NOT NULL COMMENT '签名阈值',
    `status` VARCHAR(32) NOT NULL COMMENT '状态',
    `tx_hash` VARCHAR(128) COMMENT '执行交易哈希',
    `executed_at` DATETIME COMMENT '执行时间',
    `expire_time` DATETIME COMMENT '过期时间',
    `created_by` VARCHAR(128) COMMENT '创建者',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_proposal_id` (`proposal_id`),
    KEY `idx_wallet_id` (`wallet_id`),
    KEY `idx_status` (`status`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多签提案表';

CREATE TABLE IF NOT EXISTS `hd_wallet` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `wallet_id` VARCHAR(64) NOT NULL COMMENT '钱包ID',
    `name` VARCHAR(128) COMMENT '钱包名称',
    `mnemonic_encrypted` TEXT COMMENT '加密的助记词',
    `seed_encrypted` TEXT COMMENT '加密的种子',
    `passphrase_protected` TINYINT DEFAULT 0 COMMENT '是否有密码保护',
    `derivation_path` VARCHAR(128) COMMENT '派生路径',
    `curve_type` VARCHAR(32) DEFAULT 'SECP256K1' COMMENT '曲线类型',
    `address_count` INT DEFAULT 0 COMMENT '地址数量',
    `last_derived_index` INT DEFAULT 0 COMMENT '最后派生索引',
    `metadata` TEXT COMMENT '元数据(JSON)',
    `created_by` VARCHAR(64) COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_wallet_id` (`wallet_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='HD钱包表';

CREATE TABLE IF NOT EXISTS `wallet_address` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `address_id` VARCHAR(64) NOT NULL COMMENT '地址ID',
    `wallet_id` VARCHAR(64) NOT NULL COMMENT '钱包ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `address` VARCHAR(128) NOT NULL COMMENT '地址',
    `address_format` VARCHAR(32) COMMENT '地址格式',
    `derivation_path` VARCHAR(128) COMMENT '派生路径',
    `derivation_index` INT COMMENT '派生索引',
    `change` TINYINT DEFAULT 0 COMMENT '是否找零地址',
    `public_key` VARCHAR(256) COMMENT '公钥',
    `name` VARCHAR(128) COMMENT '名称',
    `labels` TEXT COMMENT '标签列表(JSON)',
    `is_receive` TINYINT DEFAULT 1 COMMENT '是否收款地址',
    `is_archived` TINYINT DEFAULT 0 COMMENT '是否归档',
    `balance` DECIMAL(50, 0) DEFAULT 0 COMMENT '余额',
    `balance_updated_at` DATETIME COMMENT '余额更新时间',
    `metadata` TEXT COMMENT '元数据(JSON)',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_address_id` (`address_id`),
    UNIQUE KEY `uk_chain_address` (`chain_id`, `address`),
    KEY `idx_wallet_id` (`wallet_id`),
    KEY `idx_chain_id` (`chain_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='钱包地址表';

CREATE TABLE IF NOT EXISTS `address_book` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `entry_id` VARCHAR(64) NOT NULL COMMENT '条目ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `address` VARCHAR(128) NOT NULL COMMENT '地址',
    `name` VARCHAR(128) NOT NULL COMMENT '名称',
    `description` TEXT COMMENT '描述',
    `labels` TEXT COMMENT '标签列表(JSON)',
    `address_type` VARCHAR(32) COMMENT '地址类型:EOA/CONTRACT/EXCHANGE',
    `verified` TINYINT DEFAULT 0 COMMENT '是否已验证',
    `risk_level` VARCHAR(32) COMMENT '风险等级',
    `metadata` TEXT COMMENT '元数据(JSON)',
    `created_by` VARCHAR(64) COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_entry_id` (`entry_id`),
    UNIQUE KEY `uk_chain_address` (`chain_id`, `address`),
    KEY `idx_name` (`name`),
    KEY `idx_address_type` (`address_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='地址簿表';

CREATE TABLE IF NOT EXISTS `event_listener_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `listener_id` VARCHAR(64) NOT NULL COMMENT '监听器ID',
    `chain_id` VARCHAR(32) NOT NULL COMMENT '链ID',
    `name` VARCHAR(128) NOT NULL COMMENT '监听器名称',
    `contract_address` VARCHAR(128) NOT NULL COMMENT '合约地址',
    `contract_abi` TEXT COMMENT '合约ABI(JSON)',
    `event_names` TEXT COMMENT '监听的事件名称列表(JSON)',
    `topic_filters` TEXT COMMENT '主题过滤器(JSON)',
    `start_block` BIGINT COMMENT '起始区块',
    `current_block` BIGINT COMMENT '当前处理区块',
    `callback_url` VARCHAR(512) COMMENT '回调URL',
    `callback_type` VARCHAR(32) COMMENT '回调类型:HTTP/WEBHOOK/INTERNAL',
    `callback_headers` TEXT COMMENT '回调头(JSON)',
    `retry_strategy` VARCHAR(32) COMMENT '重试策略',
    `max_retries` INT DEFAULT 3 COMMENT '最大重试次数',
    `retry_interval` INT DEFAULT 5000 COMMENT '重试间隔(ms)',
    `batch_size` INT DEFAULT 100 COMMENT '批处理大小',
    `is_enabled` TINYINT DEFAULT 1 COMMENT '是否启用',
    `status` VARCHAR(32) COMMENT '状态',
    `last_error` TEXT COMMENT '最后错误信息',
    `last_error_at` DATETIME COMMENT '最后错误时间',
    `metadata` TEXT COMMENT '元数据(JSON)',
    `created_by` VARCHAR(64) COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_listener_id` (`listener_id`),
    KEY `idx_chain_id` (`chain_id`),
    KEY `idx_contract_address` (`contract_address`),
    KEY `idx_is_enabled` (`is_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='事件监听器配置表';
