apiVersion: v1
kind: Secret
metadata:
  name: exam-secrets
  namespace: exam-platform
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=
  MQ_USERNAME: cmFiYml0bXE=
  MQ_PASSWORD: cmFiYml0bXEtcGFzc3dvcmQ=
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: Y2hhbmdlLW1pbmlvLXNlY3JldA==
  JWT_SECRET: Y2hhbmdlLWp3dC1zZWNyZXQtaW4tcHJvZHVjdGlvbg==
