package com.company.dbstudio.sql.highlight;

import java.util.Set;

public class SqlServerLexer extends BaseLexer {

    private static final Set<String> SQLSERVER_KEYWORDS = Set.of(
            "SELECT", "FROM", "WHERE", "AND", "OR", "NOT", "IN", "LIKE", "BETWEEN", "IS", "NULL",
            "ORDER", "BY", "ASC", "DESC", "GROUP", "HAVING", "JOIN", "LEFT", "RIGHT", "INNER",
            "OUTER", "FULL", "ON", "UNION", "ALL", "DISTINCT", "TOP", "AS", "INSERT", "INTO",
            "VALUES", "UPDATE", "SET", "DELETE", "CREATE", "TABLE", "COLUMN", "INDEX", "PRIMARY",
            "FOREIGN", "UNIQUE", "DEFAULT", "REFERENCES", "ALTER", "DROP", "TRUNCATE", "RENAME",
            "VIEW", "PROCEDURE", "FUNCTION", "TRIGGER", "SCHEMA", "DATABASE", "USE", "GRANT",
            "REVOKE", "COMMIT", "ROLLBACK", "BEGIN", "TRANSACTION", "EXPLAIN", "SHOW", "DESCRIBE",
            "SET", "IF", "WHILE", "FOR", "LOOP", "RETURN", "DECLARE", "CASE", "WHEN", "THEN",
            "ELSE", "END", "EXISTS", "WITH", "TRUE", "FALSE", "DUPLICATE", "KEY", "ENGINE",
            "CHARSET", "COLLATE", "COMMENT", "IDENTITY", "AUTO_INCREMENT", "SEED", "INCREMENT",
            "INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT", "BIT", "DECIMAL", "NUMERIC",
            "MONEY", "SMALLMONEY", "FLOAT", "REAL", "CHAR", "VARCHAR", "TEXT", "NCHAR",
            "NVARCHAR", "NTEXT", "BINARY", "VARBINARY", "IMAGE", "DATE", "TIME", "DATETIME",
            "DATETIME2", "SMALLDATETIME", "DATETIMEOFFSET", "TIMESTAMP", "UNIQUEIDENTIFIER",
            "ROWVERSION", "HIERARCHYID", "GEOMETRY", "GEOGRAPHY", "XML", "SQL_VARIANT",
            "TABLE", "PRIMARY", "KEY", "FOREIGN", "KEY", "UNIQUE", "DEFAULT", "CHECK",
            "CONSTRAINT", "INDEX", "CLUSTERED", "NONCLUSTERED", "UNIQUE", "WITH", "ON",
            "FILEGROUP", "TEXTIMAGE_ON", "PARTITION", "SCHEME", "COLUMNSTORE", "COLUMNSTORE_ARCHIVE",
            "HEAP", "DATA_COMPRESSION", "NONE", "ROW", "PAGE", "COLUMNSTORE", "COLUMNSTORE_ARCHIVE",
            "SPARSE", "FILESTREAM", "NOT", "FOR", "REPLICATION", "NOT", "FOR", "REPLICATION",
            "ROWGUIDCOL", "PERSISTED", "NOT", "NULL", "NULL", "COLLATE", "CASCADE", "NO", "ACTION",
            "SET", "NULL", "SET", "DEFAULT", "ON", "DELETE", "ON", "UPDATE", "WITH", "CHECK",
            "WITH", "NOCHECK", "ENABLE", "DISABLE", "TRIGGER", "SCHEMABINDING", "ENCRYPTION",
            "EXECUTE", "AS", "CALLER", "SELF", "OWNER", "'user_name'", "NATIVE",
            "COMPILE", "OPTION", "RECOMPILE", "MAXRECURSION", "USE", "HINT", "QUERYTRACEON",
            "QUOTED_IDENTIFIER", "ANSI_NULLS", "ANSI_PADDING", "ANSI_WARNINGS", "ARITHABORT",
            "CONCAT_NULL_YIELDS_NULL", "NUMERIC_ROUNDABORT", "NOCOUNT", "XACT_ABORT",
            "TRANSACTION", "ISOLATION", "LEVEL", "READ", "UNCOMMITTED", "READ", "COMMITTED",
            "REPEATABLE", "READ", "SERIALIZABLE", "SNAPSHOT", "READ", "COMMITTED", "SNAPSHOT",
            "ALLOW_SNAPSHOT_ISOLATION", "READ_COMMITTED_SNAPSHOT", "AUTO_CLOSE", "AUTO_SHRINK",
            "AUTO_CREATE_STATISTICS", "AUTO_UPDATE_STATISTICS", "AUTO_UPDATE_STATISTICS_ASYNC",
            "PAGE_VERIFY", "CHECKSUM", "TORN_PAGE_DETECTION", "NONE", "RECOVERY", "FULL",
            "BULK-LOGGED", "SIMPLE", "CONTAINMENT", "NONE", "PARTIAL", "COMPATIBILITY_LEVEL",
            "MULTI_USER", "SINGLE_USER", "RESTRICTED_USER", "DB_CHAINING", "TRUSTWORTHY",
            "ENCRYPTION", "FILESTREAM", "DIRECTORY_NAME", "NON_TRANSACTED_ACCESS", "OFF",
            "READ_ONLY", "READ_WRITE", "ONLINE", "OFFLINE", "EMERGENCY", "COLLATE",
            "FILEGROUP", "PRIMARY", "LOG", "ON", "NAME", "FILENAME", "SIZE", "MAXSIZE",
            "FILEGROWTH", "UNLIMITED", "GB", "MB", "KB", "TB", "FILE", "LOGFILE",
            "REMOVE", "MODIFY", "NAME", "NEWNAME", "FILENAME", "SIZE", "MAXSIZE", "FILEGROWTH",
            "ADD", "FILE", "TO", "FILEGROUP", "REMOVE", "FILE", "EMPTYFILE", "OFFLINE",
            "ONLINE", "READ_ONLY", "READ_WRITE", "DEFAULT", "XML_SCHEMA_COLLECTION",
            "SCHEMA", "OWNER", "AUTHORIZATION", "ROLE", "USER", "LOGIN", "CERTIFICATE",
            "ASYMMETRIC", "KEY", "SYMMETRIC", "KEY", "CREDENTIAL", "PROXY", "LOGIN",
            "PASSWORD", "HASHED", "MUST_CHANGE", "CHECK_EXPIRATION", "CHECK_POLICY",
            "DEFAULT_DATABASE", "DEFAULT_LANGUAGE", "SID", "DENY", "GRANT", "REVOKE",
            "WITH", "GRANT", "OPTION", "CONTROL", "ALTER", "TAKE", "OWNERSHIP",
            "VIEW", "DEFINITION", "VIEW", "CHANGE", "TRACKING", "VIEW", "SERVER", "STATE",
            "CREATE", "ALTER", "DROP", "BACKUP", "RESTORE", "SHUTDOWN", "BULK", "INSERT",
            "IMPERSONATE", "CREATE", "ANY", "DATABASE", "ALTER", "ANY", "CONNECTION",
            "CONNECT", "SQL", "ENDPOINT", "MIRROR", "BROKER", "SERVICE", "QUEUE",
            "CONTRACT", "MESSAGE", "TYPE", "ROUTE", "REMOTE", "SERVICE", "BINDING",
            "FULLTEXT", "CATALOG", "STOPLIST", "SEARCH", "PROPERTY", "LIST", "STOPWORD",
            "THESAURUS", "DICTIONARY", "FILETABLE", "DIRECTORY", "FILENAME", "COLLATE",
            "ENABLE", "DISABLE", "CHANGE_TRACKING", "CHANGE", "TRACKING", "AUTO_CLEANUP",
            "RETENTION", "PERIOD", "SYSTEM_TIME", "GENERATED", "ALWAYS", "AS", "ROW_START",
            "ROW_END", "HIDDEN", "TEMPORAL", "SYSTEM_VERSIONING", "ON", "OFF", "HISTORY_TABLE",
            "DATA_CONSISTENCY_CHECK", "SCHEMA", "ONLY", "SECURITY", "POLICY", "FILTER",
            "PREDICATE", "BLOCK", "PREDICATE", "FORCE", "CONTEXT", "CONNECTION", "SIGNATURE",
            "CERTIFICATE", "ASYMMETRIC", "KEY", "SYMMETRIC", "KEY", "PASSWORD", "ENCRYPTION",
            "DECRYPTION", "SIGN", "VERIFY", "HASHBYTES", "ENCRYPTBYPASSPHRASE",
            "DECRYPTBYPASSPHRASE", "ENCRYPTBYKEY", "DECRYPTBYKEY", "ENCRYPTBYCERT",
            "DECRYPTBYCERT", "ENCRYPTBYASYMKEY", "DECRYPTBYASYMKEY", "KEY_GUID",
            "KEY_ID", "CERT_ID", "ASYMKEY_ID", "SYMKEY_ID", "OPEN", "SYMMETRIC", "KEY",
            "CLOSE", "SYMMETRIC", "KEY", "ALL", "OPEN", "MASTER", "KEY", "CLOSE",
            "MASTER", "KEY", "BACKUP", "MASTER", "KEY", "RESTORE", "MASTER", "KEY",
            "CREATE", "CERTIFICATE", "ALTER", "CERTIFICATE", "DROP", "CERTIFICATE",
            "BACKUP", "CERTIFICATE", "CREATE", "ASYMMETRIC", "KEY", "ALTER", "ASYMMETRIC",
            "KEY", "DROP", "ASYMMETRIC", "KEY", "CREATE", "SYMMETRIC", "KEY", "ALTER",
            "SYMMETRIC", "KEY", "DROP", "SYMMETRIC", "KEY", "CREATE", "CREDENTIAL",
            "ALTER", "CREDENTIAL", "DROP", "CREDENTIAL", "CREATE", "PROXY", "ALTER",
            "PROXY", "DROP", "PROXY", "LOGIN", "USER", "ROLE", "APPLICATION", "ROLE",
            "DATABASE", "ROLE", "SERVER", "ROLE", "SCHEMA", "ASSEMBLY", "TYPE",
            "AGGREGATE", "DEFAULT", "RULE", "DEFAULT", "BINDING", "RULE", "BINDING",
            "UNBIND", "DEFAULT", "RULE", "SPATIAL", "INDEX", "HILBERT", "GEOMETRY",
            "GEOGRAPHY", "GRIDS", "LEVEL_1", "LEVEL_2", "LEVEL_3", "LEVEL_4", "LOW",
            "MEDIUM", "HIGH", "CELLS_PER_OBJECT", "BUCKET_COUNT", "MEMORY_OPTIMIZED",
            "DURABILITY", "SCHEMA_ONLY", "SCHEMA_AND_DATA", "DELAYED_DURABILITY",
            "DISABLED", "ALLOWED", "FORCED", "MEMORY_OPTIMIZED_DATA", "FILEGROUP",
            "CONTAINMENT", "FILESTREAM", "BUCKET_COUNT", "HASH", "INDEX", "NONCLUSTERED",
            "HASH", "WITH", "BUCKET_COUNT", "DELAYED_DURABILITY", "NATIVE_COMPILATION",
            "SCHEMABINDING", "BEGIN", "ATOMIC", "WITH", "TRANSACTION", "ISOLATION",
            "LEVEL", "SNAPSHOT", "LANGUAGE", "DATEFORMAT", "DATEFIRST", "DELAYED_DURABILITY"
    );

    private static final Set<String> SQLSERVER_FUNCTIONS = Set.of(
            "COUNT", "SUM", "AVG", "MIN", "MAX", "ROUND", "FLOOR", "CEILING", "ABS", "MOD",
            "POWER", "SQRT", "EXP", "LOG", "LOG10", "SIGN", "ACOS", "ASIN", "ATAN",
            "ATN2", "COS", "COT", "DEGREES", "RADIANS", "RAND", "SIN", "TAN", "PI",
            "RAND", "CHECKSUM", "BINARY_CHECKSUM", "CHECKSUM_AGG", "STDEV", "STDEVP",
            "VAR", "VARP", "CONCAT", "SUBSTRING", "LEFT", "RIGHT", "LEN", "DATALENGTH",
            "CHARINDEX", "PATINDEX", "REPLACE", "STUFF", "REPLICATE", "REVERSE",
            "LTRIM", "RTRIM", "UPPER", "LOWER", "FORMAT", "ASCII", "CHAR", "UNICODE",
            "NCHAR", "QUOTENAME", "SOUNDEX", "DIFFERENCE", "STR", "STRING_AGG",
            "CONCAT_WS", "TRANSLATE", "TRIM", "STRING_ESCAPE", "STRING_SPLIT",
            "GETDATE", "GETUTCDATE", "SYSDATETIME", "SYSUTCDATETIME", "SYSDATETIMEOFFSET",
            "CURRENT_TIMESTAMP", "DATEADD", "DATEDIFF", "DATEPART", "DATENAME",
            "DAY", "MONTH", "YEAR", "DATEFROMPARTS", "TIMEFROMPARTS", "DATETIME2FROMPARTS",
            "DATETIMEOFFSETFROMPARTS", "SMALLDATETIMEFROMPARTS", "ISDATE", "EOMONTH",
            "SWITCHOFFSET", "TODATETIMEOFFSET", "ISNULL", "NULLIF", "COALESCE",
            "IIF", "CHOOSE", "TRY_CAST", "TRY_CONVERT", "TRY_PARSE", "CAST", "CONVERT",
            "PARSE", "NEWID", "NEWSEQUENTIALID", "ROWGUIDCOL", "IDENTITY", "SCOPE_IDENTITY",
            "IDENT_CURRENT", "IDENT_SEED", "IDENT_INCR", "COLUMNPROPERTY", "INDEXPROPERTY",
            "OBJECTPROPERTY", "OBJECTPROPERTYEX", "DATABASEPROPERTY", "DATABASEPROPERTYEX",
            "FILEPROPERTY", "FILEGROUPPROPERTY", "TYPEPROPERTY", "CONNECTIONPROPERTY",
            "SESSIONPROPERTY", "SERVERPROPERTY", "ASSEMBLYPROPERTY", "TYPE_ID", "TYPE_NAME",
            "SCHEMA_ID", "SCHEMA_NAME", "USER_ID", "USER_NAME", "SUSER_ID", "SUSER_SNAME",
            "CURRENT_USER", "SESSION_USER", "SYSTEM_USER", "USER", "ORIGINAL_LOGIN",
            "SUSER_SID", "SUSER_SNAME", "IS_SRVROLEMEMBER", "IS_MEMBER", "IS_ROLEMEMBER",
            "HAS_DBACCESS", "HAS_PERMS_BY_NAME", "PERMISSIONS", "fn_my_permissions",
            "DB_ID", "DB_NAME", "FILE_ID", "FILE_NAME", "FILEGROUP_ID", "FILEGROUP_NAME",
            "OBJECT_ID", "OBJECT_NAME", "OBJECT_SCHEMA_NAME", "COLUMN_NAME", "INDEX_COL",
            "KEY_NAME", "PARSENAME", "QUOTENAME", "FULLTEXTCATALOGPROPERTY",
            "FULLTEXTSERVICEPROPERTY", "OBJECTPROPERTY", "INDEXPROPERTY", "STATS_DATE",
            "INDEXKEY_PROPERTY", "COLUMNPROPERTY", "DATABASEPROPERTYEX", "FILEPROPERTY",
            "FILEGROUPPROPERTY", "TYPEPROPERTY", "SESSIONPROPERTY", "CONNECTIONPROPERTY",
            "SERVERPROPERTY", "ASSEMBLYPROPERTY", "sys.dm_db_index_physical_stats",
            "sys.dm_db_index_operational_stats", "sys.dm_db_index_usage_stats",
            "sys.dm_os_wait_stats", "sys.dm_os_waiting_tasks", "sys.dm_exec_sessions",
            "sys.dm_exec_requests", "sys.dm_exec_query_stats", "sys.dm_exec_sql_text",
            "sys.dm_exec_query_plan", "sys.dm_exec_text_query_plan", "sys.dm_tran_locks",
            "sys.dm_tran_session_transactions", "sys.dm_io_virtual_file_stats",
            "sys.dm_io_pending_io_requests", "sys.dm_os_performance_counters",
            "sys.dm_os_memory_clerks", "sys.dm_os_memory_cache_counters",
            "sys.dm_os_memory_cache_hash_tables", "sys.dm_os_memory_cache_entries",
            "sys.dm_os_buffer_descriptors", "sys.dm_os_workers", "sys.dm_os_threads",
            "sys.dm_os_tasks", "sys.dm_os_schedulers", "sys.dm_os_hosts",
            "sys.dm_os_loaded_modules", "sys.dm_os_cluster_nodes", "sys.dm_os_volume_stats",
            "sys.dm_db_missing_index_details", "sys.dm_db_missing_index_groups",
            "sys.dm_db_missing_index_group_stats", "sys.dm_db_partition_stats",
            "sys.dm_db_log_space_usage", "sys.dm_db_log_info", "sys.dm_db_file_space_usage",
            "sys.dm_db_task_space_usage", "sys.dm_db_session_space_usage",
            "sys.dm_tran_active_transactions", "sys.dm_tran_database_transactions",
            "sys.dm_tran_top_version_generators", "sys.dm_tran_version_store",
            "sys.dm_tran_current_transaction", "sys.dm_tran_current_snapshot",
            "sys.fn_dblog", "sys.fn_dump_dblog", "sys.fn_physlocformatter",
            "sys.fn_PhysLocCracker", "sys.fn_VirtualFileStats", "sys.fn_VirtualLogFile",
            "sys.fn_helpcollations", "sys.fn_servershareddrives", "sys.fn_get_sql",
            "sys.fn_stmt_sql_handle_from_sql_stmt", "sys.fn_listextendedproperty",
            "sys.fn_trace_gettable", "sys.fn_trace_getinfo", "sys.fn_trace_geteventinfo",
            "sys.fn_trace_getfilterinfo", "sys.fn_map_object_keys", "sys.fn_ReportError",
            "sys.fn_ResolveComputerName", "sys.fn_MSforeachdb", "sys.fn_MSforeachtable",
            "XMLDATA", "XMLSCHEMA", "EXPLICIT", "AUTO", "PATH", "RAW", "ROOT",
            "ELEMENTS", "XSINIL", "ABSENT", "BINARY", "BASE64", "TYPE", "XML",
            "FOR", "XML", "AUTO", "RAW", "EXPLICIT", "PATH", "FOR", "JSON",
            "AUTO", "PATH", "WITHOUT_ARRAY_WRAPPER", "INCLUDE_NULL_VALUES",
            "JSON_VALUE", "JSON_QUERY", "JSON_MODIFY", "ISJSON", "JSON_OBJECT",
            "JSON_ARRAY", "OPENJSON", "WITH", "JSON_PATH", "LAX", "STRICT",
            "CROSS", "APPLY", "OUTER", "APPLY", "PIVOT", "UNPIVOT", "GROUPING",
            "GROUPING_ID", "ROLLUP", "CUBE", "GROUPING SETS", "COMPUTE", "BY",
            "COMPUTE", "ROW_NUMBER", "RANK", "DENSE_RANK", "NTILE", "LEAD",
            "LAG", "FIRST_VALUE", "LAST_VALUE", "PERCENT_RANK", "CUME_DIST",
            "PERCENTILE_CONT", "PERCENTILE_DISC", "WITHIN GROUP", "OVER",
            "PARTITION BY", "ORDER BY", "ROWS", "RANGE", "UNBOUNDED PRECEDING",
            "UNBOUNDED FOLLOWING", "CURRENT ROW", "PRECEDING", "FOLLOWING",
            "TRY_CAST", "TRY_CONVERT", "TRY_PARSE", "PARSE", "TRY_PARSE",
            "CULTURE", "USING", "DATEFIRST", "DATEFORMAT", "LANGUAGE", "STYLE"
    );

    @Override
    protected Set<String> initKeywords() {
        return SQLSERVER_KEYWORDS;
    }

    @Override
    protected Set<String> initFunctions() {
        return SQLSERVER_FUNCTIONS;
    }
}
