#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# WASM 构建脚本
# 串联 wasm-pack build → wasm-opt 体积优化 → TypeScript 类型声明生成
# ============================================================================

echo "🚀 Starting WASM build pipeline..."

# 配置变量
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CRATE_DIR="$PROJECT_ROOT/crates/renderer"
OUTPUT_DIR="$PROJECT_ROOT/pkg"
WEB_WASM_DIR="$PROJECT_ROOT/web/public/wasm"
TS_TYPES_DIR="$PROJECT_ROOT/web/src/types/wasm"
PROFILE="${PROFILE:-release}"
ENABLE_OPT="${ENABLE_OPT:-1}"
ENABLE_TS="${ENABLE_TS:-1}"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }

# 检查依赖
check_dependency() {
    if ! command -v "$1" &> /dev/null; then
        log_error "$1 is not installed. Please install it first."
        exit 1
    fi
}

echo "📋 Checking dependencies..."
check_dependency wasm-pack
if [[ "$ENABLE_OPT" -eq 1 ]]; then
    check_dependency wasm-opt
fi
if [[ "$ENABLE_TS" -eq 1 ]]; then
    check_dependency ts-node 2>/dev/null || true
fi
log_success "All dependencies found"

# 清理旧构建产物
echo "🧹 Cleaning previous build artifacts..."
rm -rf "$OUTPUT_DIR"
rm -rf "$WEB_WASM_DIR"
mkdir -p "$OUTPUT_DIR"
mkdir -p "$WEB_WASM_DIR"
mkdir -p "$TS_TYPES_DIR"
log_success "Clean complete"

# Step 1: wasm-pack build
echo "🔨 Step 1/3: Building WASM with wasm-pack (profile: $PROFILE)..."
BUILD_ARGS=(
    build
    "$CRATE_DIR"
    --out-dir "$OUTPUT_DIR"
    --out-name whiteboard
    --target web
)
if [[ "$PROFILE" == "release" ]]; then
    BUILD_ARGS+=(--release)
else
    BUILD_ARGS+=(--dev)
fi
if [[ -n "${WASM_PACK_EXTRA_ARGS:-}" ]]; then
    BUILD_ARGS+=($WASM_PACK_EXTRA_ARGS)
fi

wasm-pack "${BUILD_ARGS[@]}"
log_success "wasm-pack build complete"

# 展示体积（优化前）
if [[ -f "$OUTPUT_DIR/whiteboard_bg.wasm" ]]; then
    WASM_SIZE_BEFORE=$(wc -c < "$OUTPUT_DIR/whiteboard_bg.wasm" | tr -d ' ')
    echo "   WASM size before optimization: $(numfmt --to=iec $WASM_SIZE_BEFORE)"
fi

# Step 2: wasm-opt 体积优化
if [[ "$ENABLE_OPT" -eq 1 && -f "$OUTPUT_DIR/whiteboard_bg.wasm" ]]; then
    echo "⚡ Step 2/3: Optimizing WASM binary with binaryen wasm-opt..."
    WASM_INPUT="$OUTPUT_DIR/whiteboard_bg.wasm"
    WASM_OUTPUT="$OUTPUT_DIR/whiteboard_bg.opt.wasm"

    OPT_ARGS=(
        -O3
        --converge
        --dce
        --duplicate-function-elimination
        --duplicate-import-elimination
        --inlining-optimizing
        --type-merging
        --type-ssa
        --minify-imports-and-exports
        --minify-module
        --strip-debug
        --strip-dwarf
        --strip-target-features
    )

    if [[ "$PROFILE" == "release" ]]; then
        OPT_ARGS+=(
            --flatten
            --gufa
            --metrics
        )
    fi

    wasm-opt "${OPT_ARGS[@]}" "$WASM_INPUT" -o "$WASM_OUTPUT"

    if [[ -f "$WASM_OUTPUT" ]]; then
        mv "$WASM_OUTPUT" "$WASM_INPUT"
        WASM_SIZE_AFTER=$(wc -c < "$WASM_INPUT" | tr -d ' ')
        SAVED=$((WASM_SIZE_BEFORE - WASM_SIZE_AFTER))
        if [[ $SAVED -gt 0 ]]; then
            SAVED_PCT=$((SAVED * 100 / WASM_SIZE_BEFORE))
            echo "   WASM size after optimization:  $(numfmt --to=iec $WASM_SIZE_AFTER) (saved ${SAVED_PCT}%)"
        else
            echo "   WASM size after optimization:  $(numfmt --to=iec $WASM_SIZE_AFTER)"
        fi
        log_success "WASM optimization complete"
    else
        log_warn "WASM optimization failed, using unoptimized binary"
    fi
else
    echo "⏭️  Step 2/3: Skipping WASM optimization (ENABLE_OPT=0 or no binary)"
fi

# Step 3: 拷贝到前端 public 目录并生成 TS 类型
echo "📦 Step 3/3: Copying artifacts and generating TypeScript declarations..."

cp -f "$OUTPUT_DIR/whiteboard_bg.wasm" "$WEB_WASM_DIR/whiteboard_bg.wasm"
cp -f "$OUTPUT_DIR/whiteboard.js" "$WEB_WASM_DIR/whiteboard.js"

if [[ -f "$OUTPUT_DIR/whiteboard_bg.wasm.d.ts" ]]; then
    cp -f "$OUTPUT_DIR/whiteboard_bg.wasm.d.ts" "$TS_TYPES_DIR/whiteboard_bg.wasm.d.ts"
fi

# 生成 TypeScript 类型声明
if [[ "$ENABLE_TS" -eq 1 ]]; then
    # 生成统一的 WASM bindings 类型导出
    cat > "$TS_TYPES_DIR/index.ts" << 'EOF'
// Auto-generated WASM TypeScript type declarations
// Generated by scripts/build-wasm.sh at GENERATED_AT

export * from './whiteboard_bg.wasm';

import type {
    Viewport, LayerTree, DirtyRectManager, Vertex, MeshData,
    PathBuilder, Rasterizer, RenderContext, Artboard, SVGExport, PDFExport,
    CanvasFacade, SyncFacade, ExportFacade,
} from './whiteboard_bg.wasm';

export type WASMModule = {
    Viewport: typeof Viewport;
    LayerTree: typeof LayerTree;
    DirtyRectManager: typeof DirtyRectManager;
    Vertex: typeof Vertex;
    MeshData: typeof MeshData;
    PathBuilder: typeof PathBuilder;
    Rasterizer: typeof Rasterizer;
    RenderContext: typeof RenderContext;
    Artboard: typeof Artboard;
    SVGExport: typeof SVGExport;
    PDFExport: typeof PDFExport;
    CanvasFacade: typeof CanvasFacade;
    SyncFacade: typeof SyncFacade;
    ExportFacade: typeof ExportFacade;
    memory?: WebAssembly.Memory;
};

declare global {
    interface Window {
        __WASM_MODULE__?: WASMModule;
        __WASM_INITIALIZED__?: boolean;
    }
}
EOF
    # 替换时间戳
    sed -i.bak "s/GENERATED_AT/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/g" "$TS_TYPES_DIR/index.ts"
    rm -f "$TS_TYPES_DIR/index.ts.bak" 2>/dev/null || true
fi

log_success "Artifacts copied and types generated"

# 输出汇总
echo ""
echo "📊 Build Summary:"
echo "   Output WASM: $WEB_WASM_DIR/whiteboard_bg.wasm"
echo "   Output JS:    $WEB_WASM_DIR/whiteboard.js"
echo "   TS types:     $TS_TYPES_DIR/index.ts"
if [[ -f "$OUTPUT_DIR/whiteboard_bg.wasm" ]]; then
    FINAL_SIZE=$(wc -c < "$OUTPUT_DIR/whiteboard_bg.wasm" | tr -d ' ')
    echo "   Final size:   $(numfmt --to=iec $FINAL_SIZE)"
fi
echo ""
log_success "WASM build pipeline complete! 🎉"
