apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestration

commonLabels:
  environment: production

bases:
  - ../../base

patches:
  - path: deployment-patch.yml

replicas:
  - name: orchestration-app
    count: 4

images:
  - name: registry.cn-hangzhou.aliyuncs.com/orchestration/web
    newTag: latest
