// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.0
// source: distcomp/v1/distcomp.proto

package v1

import (
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3
	TaskStatus_TASK_STATUS_PAUSED      TaskStatus = 4
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 5
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 6
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 7
	TaskStatus_TASK_STATUS_TIMED_OUT   TaskStatus = 8
)

type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_TASK_PRIORITY_LOW         TaskPriority = 1
	TaskPriority_TASK_PRIORITY_MEDIUM      TaskPriority = 2
	TaskPriority_TASK_PRIORITY_HIGH        TaskPriority = 3
	TaskPriority_TASK_PRIORITY_CRITICAL    TaskPriority = 4
)

type ComputeStatusCode int32

const (
	ComputeStatusCode_COMPUTE_STATUS_CODE_UNSPECIFIED   ComputeStatusCode = 0
	ComputeStatusCode_COMPUTE_STATUS_CODE_SUCCESS       ComputeStatusCode = 1
	ComputeStatusCode_COMPUTE_STATUS_CODE_ERROR         ComputeStatusCode = 2
	ComputeStatusCode_COMPUTE_STATUS_CODE_TIMEOUT       ComputeStatusCode = 3
	ComputeStatusCode_COMPUTE_STATUS_CODE_CANCELLED     ComputeStatusCode = 4
	ComputeStatusCode_COMPUTE_STATUS_CODE_OUT_OF_MEMORY ComputeStatusCode = 5
	ComputeStatusCode_COMPUTE_STATUS_CODE_INVALID_INPUT ComputeStatusCode = 6
)

type WorkerStatus int32

const (
	WorkerStatus_WORKER_STATUS_UNSPECIFIED WorkerStatus = 0
	WorkerStatus_WORKER_STATUS_OFFLINE     WorkerStatus = 1
	WorkerStatus_WORKER_STATUS_IDLE        WorkerStatus = 2
	WorkerStatus_WORKER_STATUS_BUSY        WorkerStatus = 3
	WorkerStatus_WORKER_STATUS_PAUSED      WorkerStatus = 4
	WorkerStatus_WORKER_STATUS_ERROR       WorkerStatus = 5
	WorkerStatus_WORKER_STATUS_DRAINING    WorkerStatus = 6
)

type WorkerType int32

const (
	WorkerType_WORKER_TYPE_UNSPECIFIED WorkerType = 0
	WorkerType_WORKER_TYPE_CPU         WorkerType = 1
	WorkerType_WORKER_TYPE_GPU         WorkerType = 2
	WorkerType_WORKER_TYPE_TPU         WorkerType = 3
	WorkerType_WORKER_TYPE_FPGA        WorkerType = 4
	WorkerType_WORKER_TYPE_HYBRID      WorkerType = 5
)

type ParameterType int32

const (
	ParameterType_PARAMETER_TYPE_UNSPECIFIED   ParameterType = 0
	ParameterType_PARAMETER_TYPE_CONTINUOUS    ParameterType = 1
	ParameterType_PARAMETER_TYPE_DISCRETE      ParameterType = 2
	ParameterType_PARAMETER_TYPE_CATEGORICAL   ParameterType = 3
)

type FunctionType int32

const (
	FunctionType_FUNCTION_TYPE_UNSPECIFIED FunctionType = 0
	FunctionType_FUNCTION_TYPE_LINEAR      FunctionType = 1
	FunctionType_FUNCTION_TYPE_QUADRATIC   FunctionType = 2
	FunctionType_FUNCTION_TYPE_NONLINEAR   FunctionType = 3
	FunctionType_FUNCTION_TYPE_BLACKBOX    FunctionType = 4
)

type OptimizationDirection int32

const (
	OptimizationDirection_OPTIMIZATION_DIRECTION_UNSPECIFIED OptimizationDirection = 0
	OptimizationDirection_OPTIMIZATION_DIRECTION_MINIMIZE    OptimizationDirection = 1
	OptimizationDirection_OPTIMIZATION_DIRECTION_MAXIMIZE    OptimizationDirection = 2
)

type ConstraintType int32

const (
	ConstraintType_CONSTRAINT_TYPE_UNSPECIFIED        ConstraintType = 0
	ConstraintType_CONSTRAINT_TYPE_EQUALITY           ConstraintType = 1
	ConstraintType_CONSTRAINT_TYPE_INEQUALITY_LESS    ConstraintType = 2
	ConstraintType_CONSTRAINT_TYPE_INEQUALITY_GREATER ConstraintType = 3
)

type TaskConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxRetries          int32               `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Timeout             *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxParallelShards   int32               `protobuf:"varint,3,opt,name=max_parallel_shards,json=maxParallelShards,proto3" json:"max_parallel_shards,omitempty"`
	EnableCheckpointing bool                `protobuf:"varint,4,opt,name=enable_checkpointing,json=enableCheckpointing,proto3" json:"enable_checkpointing,omitempty"`
	ResourceRequirements string             `protobuf:"bytes,5,opt,name=resource_requirements,json=resourceRequirements,proto3" json:"resource_requirements,omitempty"`
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExperimentName     string                 `protobuf:"bytes,2,opt,name=experiment_name,json=experimentName,proto3" json:"experiment_name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority           TaskPriority           `protobuf:"varint,4,opt,name=priority,proto3,enum=distcomp.v1.TaskPriority" json:"priority,omitempty"`
	Status             TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=distcomp.v1.TaskStatus" json:"status,omitempty"`
	Objective          *ObjectiveFunction     `protobuf:"bytes,6,opt,name=objective,proto3" json:"objective,omitempty"`
	ParameterCombinations []*ParameterCombination `protobuf:"bytes,7,rep,name=parameter_combinations,json=parameterCombinations,proto3" json:"parameter_combinations,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deadline           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Config             *TaskConfig            `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`
	CreatedBy          string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Tags               map[string]string      `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type TaskShard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId              int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TotalShards          int32                  `protobuf:"varint,3,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	ParameterCombinations []*ParameterCombination `protobuf:"bytes,4,rep,name=parameter_combinations,json=parameterCombinations,proto3" json:"parameter_combinations,omitempty"`
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExperimentName       string                 `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName,proto3" json:"experiment_name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority             TaskPriority           `protobuf:"varint,3,opt,name=priority,proto3,enum=distcomp.v1.TaskPriority" json:"priority,omitempty"`
	Objective            *ObjectiveFunction     `protobuf:"bytes,4,opt,name=objective,proto3" json:"objective,omitempty"`
	ParameterCombinations []*ParameterCombination `protobuf:"bytes,5,rep,name=parameter_combinations,json=parameterCombinations,proto3" json:"parameter_combinations,omitempty"`
	Deadline             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Config               *TaskConfig            `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	CreatedBy            string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Tags                 map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=distcomp.v1.TaskStatus" json:"status,omitempty"`
}

type GetTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

type GetTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

type ListTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExperimentName string     `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName,proto3" json:"experiment_name,omitempty"`
	Status         TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=distcomp.v1.TaskStatus" json:"status,omitempty"`
	CreatedBy      string     `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	PageSize       int32      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string     `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

type ListTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks         []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	TotalCount    int32   `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string  `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  string     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status  TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=distcomp.v1.TaskStatus" json:"status,omitempty"`
	Message string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

type UpdateTaskStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

type ContinuousParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LowerBound   float64 `protobuf:"fixed64,1,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound   float64 `protobuf:"fixed64,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	DefaultValue float64 `protobuf:"fixed64,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	LogScale     bool    `protobuf:"varint,4,opt,name=log_scale,json=logScale,proto3" json:"log_scale,omitempty"`
}

type DiscreteParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values       []int64 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	DefaultValue int64   `protobuf:"varint,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

type CategoricalParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories   []string `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	DefaultValue string   `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        ParameterType `protobuf:"varint,2,opt,name=type,proto3,enum=distcomp.v1.ParameterType" json:"type,omitempty"`
	Description string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Parameter   isParameter_Parameter `protobuf_oneof:"parameter"`
}

type isParameter_Parameter interface {
	isParameter_Parameter()
}

type Parameter_Continuous struct {
	Continuous *ContinuousParameter `protobuf:"bytes,4,opt,name=continuous,proto3,oneof"`
}

type Parameter_Discrete struct {
	Discrete *DiscreteParameter `protobuf:"bytes,5,opt,name=discrete,proto3,oneof"`
}

type Parameter_Categorical struct {
	Categorical *CategoricalParameter `protobuf:"bytes,6,opt,name=categorical,proto3,oneof"`
}

type ParameterValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value isParameterValue_Value `protobuf_oneof:"value"`
}

type isParameterValue_Value interface {
	isParameterValue_Value()
}

type ParameterValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type ParameterValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ParameterValue_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ParameterSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parameters []*Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

type ParameterCombination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*ParameterValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

type ValidateParameterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space       *ParameterSpace       `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Combination *ParameterCombination `protobuf:"bytes,2,opt,name=combination,proto3" json:"combination,omitempty"`
}

type ValidateParameterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid  bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

type GradientRequirement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Required  bool    `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Order     int32   `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Numerical bool    `protobuf:"varint,3,opt,name=numerical,proto3" json:"numerical,omitempty"`
	Epsilon   float64 `protobuf:"fixed64,4,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
}

type Constraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       ConstraintType `protobuf:"varint,2,opt,name=type,proto3,enum=distcomp.v1.ConstraintType" json:"type,omitempty"`
	Tolerance  float64        `protobuf:"fixed64,3,opt,name=tolerance,proto3" json:"tolerance,omitempty"`
	Expression string         `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
}

type ObjectiveFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string              `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type                FunctionType        `protobuf:"varint,3,opt,name=type,proto3,enum=distcomp.v1.FunctionType" json:"type,omitempty"`
	Direction           OptimizationDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=distcomp.v1.OptimizationDirection" json:"direction,omitempty"`
	ParameterSpace      *ParameterSpace     `protobuf:"bytes,5,opt,name=parameter_space,json=parameterSpace,proto3" json:"parameter_space,omitempty"`
	Constraints         []*Constraint       `protobuf:"bytes,6,rep,name=constraints,proto3" json:"constraints,omitempty"`
	GradientRequirement *GradientRequirement `protobuf:"bytes,7,opt,name=gradient_requirement,json=gradientRequirement,proto3" json:"gradient_requirement,omitempty"`
	Expression          string              `protobuf:"bytes,8,opt,name=expression,proto3" json:"expression,omitempty"`
	Metadata            map[string]string   `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type EvaluateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId          string              `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Objective       *ObjectiveFunction  `protobuf:"bytes,2,opt,name=objective,proto3" json:"objective,omitempty"`
	Parameters      *ParameterCombination `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	ComputeGradient bool                `protobuf:"varint,4,opt,name=compute_gradient,json=computeGradient,proto3" json:"compute_gradient,omitempty"`
}

type EvaluateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId              string               `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ObjectiveValue      float64              `protobuf:"fixed64,2,opt,name=objective_value,json=objectiveValue,proto3" json:"objective_value,omitempty"`
	Gradient            []float64            `protobuf:"fixed64,3,rep,packed,name=gradient,proto3" json:"gradient,omitempty"`
	ConstraintViolations []*ConstraintViolation `protobuf:"bytes,4,rep,name=constraint_violations,json=constraintViolations,proto3" json:"constraint_violations,omitempty"`
	Feasible            bool                 `protobuf:"varint,5,opt,name=feasible,proto3" json:"feasible,omitempty"`
	ComputeTimeMs       float64              `protobuf:"fixed64,6,opt,name=compute_time_ms,json=computeTimeMs,proto3" json:"compute_time_ms,omitempty"`
	Error               string               `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

type ConstraintViolation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConstraintName string  `protobuf:"bytes,1,opt,name=constraint_name,json=constraintName,proto3" json:"constraint_name,omitempty"`
	Value          float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Violation      float64 `protobuf:"fixed64,3,opt,name=violation,proto3" json:"violation,omitempty"`
}

type ValidateObjectiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objective *ObjectiveFunction `protobuf:"bytes,1,opt,name=objective,proto3" json:"objective,omitempty"`
}

type ValidateObjectiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid  bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

type CheckpointData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Format    string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Iteration int32                  `protobuf:"varint,4,opt,name=iteration,proto3" json:"iteration,omitempty"`
}

type IntermediateState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iteration         int32                  `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	CurrentObjective   float64                `protobuf:"fixed64,2,opt,name=current_objective,json=currentObjective,proto3" json:"current_objective,omitempty"`
	CurrentGradient    []float64              `protobuf:"fixed64,3,rep,packed,name=current_gradient,json=currentGradient,proto3" json:"current_gradient,omitempty"`
	CurrentParameters  *ParameterCombination  `protobuf:"bytes,4,opt,name=current_parameters,json=currentParameters,proto3" json:"current_parameters,omitempty"`
	Metrics            map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Checkpoint         *CheckpointData        `protobuf:"bytes,6,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

type ProgressUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId             int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	CompletedCount      int32                  `protobuf:"varint,3,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"`
	TotalCount          int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Percentage          float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	EstimatedCompletion *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	RetryCount          int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	Message             string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId           string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId          int32                  `protobuf:"varint,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MemoryUsageBytes uint64                 `protobuf:"varint,5,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	CpuUsagePercent  float64                `protobuf:"fixed64,6,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	Healthy          bool                   `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
}

type ComputeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request isComputeRequest_Request `protobuf_oneof:"request"`
}

type isComputeRequest_Request interface {
	isComputeRequest_Request()
}

type ComputeRequest_Assignment struct {
	Assignment *TaskAssignment `protobuf:"bytes,1,opt,name=assignment,proto3,oneof"`
}

type ComputeRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ComputeRequest_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type ComputeRequest_Result struct {
	Result *ComputeResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type ComputeRequest_Intermediate struct {
	Intermediate *IntermediateState `protobuf:"bytes,5,opt,name=intermediate,proto3,oneof"`
}

type ComputeRequest_Error struct {
	Error *ComputeError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type ComputeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response isComputeResponse_Response `protobuf_oneof:"response"`
}

type isComputeResponse_Response interface {
	isComputeResponse_Response()
}

type ComputeResponse_Ack struct {
	Ack *TaskAssignmentAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ComputeResponse_StatusUpdate struct {
	StatusUpdate *TaskStatusUpdate `protobuf:"bytes,2,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type ComputeResponse_Cancellation struct {
	Cancellation *TaskCancellation `protobuf:"bytes,3,opt,name=cancellation,proto3,oneof"`
}

type ComputeResponse_CheckpointRequest struct {
	CheckpointRequest *CheckpointRequest `protobuf:"bytes,4,opt,name=checkpoint_request,json=checkpointRequest,proto3,oneof"`
}

type TaskAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard      *TaskShard            `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Objective  *ObjectiveFunction    `protobuf:"bytes,2,opt,name=objective,proto3" json:"objective,omitempty"`
	AssignedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
}

type TaskAssignmentAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId  int32  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Accepted bool   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  string     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId int32      `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Status  TaskStatus `protobuf:"varint,3,opt,name=status,proto3,enum=distcomp.v1.TaskStatus" json:"status,omitempty"`
	Message string     `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

type TaskCancellation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId      string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId     int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Reason      string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CancelledAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
}

type CheckpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId   int32  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Immediate bool   `protobuf:"varint,3,opt,name=immediate,proto3" json:"immediate,omitempty"`
}

type ComputeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId                string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId               int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Evaluations           []*EvaluateResponse    `protobuf:"bytes,3,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	TotalEvaluations      int32                  `protobuf:"varint,4,opt,name=total_evaluations,json=totalEvaluations,proto3" json:"total_evaluations,omitempty"`
	SuccessfulEvaluations int32                  `protobuf:"varint,5,opt,name=successful_evaluations,json=successfulEvaluations,proto3" json:"successful_evaluations,omitempty"`
	FailedEvaluations     int32                  `protobuf:"varint,6,opt,name=failed_evaluations,json=failedEvaluations,proto3" json:"failed_evaluations,omitempty"`
	StartedAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	StatusCode            ComputeStatusCode      `protobuf:"varint,9,opt,name=status_code,json=statusCode,proto3,enum=distcomp.v1.ComputeStatusCode" json:"status_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FinalCheckpoint       *CheckpointData        `protobuf:"bytes,11,opt,name=final_checkpoint,json=finalCheckpoint,proto3" json:"final_checkpoint,omitempty"`
}

type ComputeError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShardId          int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Code             ComputeStatusCode      `protobuf:"varint,3,opt,name=code,proto3,enum=distcomp.v1.ComputeStatusCode" json:"code,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StackTrace       string                 `protobuf:"bytes,5,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FailedParameters *ParameterCombination  `protobuf:"bytes,7,opt,name=failed_parameters,json=failedParameters,proto3" json:"failed_parameters,omitempty"`
}

type SubmitResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *ComputeResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

type GetShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId   string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

type GetShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard     *TaskShard         `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Objective *ObjectiveFunction `protobuf:"bytes,2,opt,name=objective,proto3" json:"objective,omitempty"`
}

type ResourceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMemoryBytes      uint64  `protobuf:"varint,1,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	AvailableMemoryBytes  uint64  `protobuf:"varint,2,opt,name=available_memory_bytes,json=availableMemoryBytes,proto3" json:"available_memory_bytes,omitempty"`
	TotalCpuCores         int32   `protobuf:"varint,3,opt,name=total_cpu_cores,json=totalCpuCores,proto3" json:"total_cpu_cores,omitempty"`
	CpuUsagePercent       float64 `protobuf:"fixed64,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	GpuCount              int32   `protobuf:"varint,5,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	GpuUsagePercent       float64 `protobuf:"fixed64,6,opt,name=gpu_usage_percent,json=gpuUsagePercent,proto3" json:"gpu_usage_percent,omitempty"`
	GpuMemoryBytes        uint64  `protobuf:"varint,7,opt,name=gpu_memory_bytes,json=gpuMemoryBytes,proto3" json:"gpu_memory_bytes,omitempty"`
	AvailableGpuMemoryBytes uint64 `protobuf:"varint,8,opt,name=available_gpu_memory_bytes,json=availableGpuMemoryBytes,proto3" json:"available_gpu_memory_bytes,omitempty"`
	DiskUsageBytes        uint64  `protobuf:"varint,9,opt,name=disk_usage_bytes,json=diskUsageBytes,proto3" json:"disk_usage_bytes,omitempty"`
	TotalDiskBytes        uint64  `protobuf:"varint,10,opt,name=total_disk_bytes,json=totalDiskBytes,proto3" json:"total_disk_bytes,omitempty"`
	NetworkBandwidthMbps  float64 `protobuf:"fixed64,11,opt,name=network_bandwidth_mbps,json=networkBandwidthMbps,proto3" json:"network_bandwidth_mbps,omitempty"`
}

type LoadInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveTasks         int32                 `protobuf:"varint,1,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	PendingTasks        int32                 `protobuf:"varint,2,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	CompletedTasks      int32                 `protobuf:"varint,3,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	FailedTasks         int32                 `protobuf:"varint,4,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	AverageTaskDurationMs float64             `protobuf:"fixed64,5,opt,name=average_task_duration_ms,json=averageTaskDurationMs,proto3" json:"average_task_duration_ms,omitempty"`
	Resources           *ResourceInfo         `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	LastUpdated         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

type WorkerCapabilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportedFunctions   []string          `protobuf:"bytes,1,rep,name=supported_functions,json=supportedFunctions,proto3" json:"supported_functions,omitempty"`
	SupportedFrameworks  []string          `protobuf:"bytes,2,rep,name=supported_frameworks,json=supportedFrameworks,proto3" json:"supported_frameworks,omitempty"`
	MaxParallelTasks     int32             `protobuf:"varint,3,opt,name=max_parallel_tasks,json=maxParallelTasks,proto3" json:"max_parallel_tasks,omitempty"`
	MaxMemoryGb          float64           `protobuf:"fixed64,4,opt,name=max_memory_gb,json=maxMemoryGb,proto3" json:"max_memory_gb,omitempty"`
	PerformanceScore     float64           `protobuf:"fixed64,5,opt,name=performance_score,json=performanceScore,proto3" json:"performance_score,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type WorkerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Type           WorkerType             `protobuf:"varint,4,opt,name=type,proto3,enum=distcomp.v1.WorkerType" json:"type,omitempty"`
	Status         WorkerStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=distcomp.v1.WorkerStatus" json:"status,omitempty"`
	Capabilities   *WorkerCapabilities    `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Load           *LoadInfo              `protobuf:"bytes,7,opt,name=load,proto3" json:"load,omitempty"`
	RegisteredAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Version        string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	Zone           string                 `protobuf:"bytes,11,opt,name=zone,proto3" json:"zone,omitempty"`
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address      string              `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type         WorkerType          `protobuf:"varint,3,opt,name=type,proto3,enum=distcomp.v1.WorkerType" json:"type,omitempty"`
	Capabilities *WorkerCapabilities `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Version      string              `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Zone         string              `protobuf:"bytes,6,opt,name=zone,proto3" json:"zone,omitempty"`
	Tags         map[string]string   `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId   string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Success    bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message    string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AssignedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
}

type UnregisterWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

type UnregisterWorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId  string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status    WorkerStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=distcomp.v1.WorkerStatus" json:"status,omitempty"`
	Load      *LoadInfo              `protobuf:"bytes,3,opt,name=load,proto3" json:"load,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message   string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acknowledged         bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DesiredStatus        WorkerStatus           `protobuf:"varint,2,opt,name=desired_status,json=desiredStatus,proto3,enum=distcomp.v1.WorkerStatus" json:"desired_status,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	NextHeartbeatDeadline *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_heartbeat_deadline,json=nextHeartbeatDeadline,proto3" json:"next_heartbeat_deadline,omitempty"`
}

type GetWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
}

type GetWorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worker *WorkerInfo `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    WorkerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=distcomp.v1.WorkerStatus" json:"status,omitempty"`
	Type      WorkerType   `protobuf:"varint,2,opt,name=type,proto3,enum=distcomp.v1.WorkerType" json:"type,omitempty"`
	Zone      string       `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	PageSize  int32        `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string       `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workers       []*WorkerInfo `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	TotalCount    int32         `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string        `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

type UpdateWorkerStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string       `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status   WorkerStatus `protobuf:"varint,2,opt,name=status,proto3,enum=distcomp.v1.WorkerStatus" json:"status,omitempty"`
	Message  string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

type UpdateWorkerStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

type WorkerStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request isWorkerStreamRequest_Request `protobuf_oneof:"request"`
}

type isWorkerStreamRequest_Request interface {
	isWorkerStreamRequest_Request()
}

type WorkerStreamRequest_Register struct {
	Register *RegisterWorkerRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerStreamRequest_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerStreamRequest_Unregister struct {
	Unregister *UnregisterWorkerRequest `protobuf:"bytes,3,opt,name=unregister,proto3,oneof"`
}

type WorkerStreamRequest_LoadUpdate struct {
	LoadUpdate *LoadInfo `protobuf:"bytes,4,opt,name=load_update,json=loadUpdate,proto3,oneof"`
}

type WorkerStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response isWorkerStreamResponse_Response `protobuf_oneof:"response"`
}

type isWorkerStreamResponse_Response interface {
	isWorkerStreamResponse_Response()
}

type WorkerStreamResponse_RegisterAck struct {
	RegisterAck *RegisterWorkerResponse `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type WorkerStreamResponse_HeartbeatAck struct {
	HeartbeatAck *HeartbeatResponse `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type WorkerStreamResponse_StatusUpdate struct {
	StatusUpdate *UpdateWorkerStatusResponse `protobuf:"bytes,3,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type WorkerStreamResponse_Command struct {
	Command *WorkerCommand `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

type WorkerCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       WorkerCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=distcomp.v1.WorkerCommand_CommandType" json:"type,omitempty"`
	WorkerId   string                   `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Message    string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	IssuedAt   *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Parameters map[string]string        `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type WorkerCommand_CommandType int32

const (
	WorkerCommand_COMMAND_TYPE_UNSPECIFIED          WorkerCommand_CommandType = 0
	WorkerCommand_COMMAND_TYPE_PAUSE                WorkerCommand_CommandType = 1
	WorkerCommand_COMMAND_TYPE_RESUME               WorkerCommand_CommandType = 2
	WorkerCommand_COMMAND_TYPE_DRAIN                WorkerCommand_CommandType = 3
	WorkerCommand_COMMAND_TYPE_SHUTDOWN             WorkerCommand_CommandType = 4
	WorkerCommand_COMMAND_TYPE_UPDATE_CAPABILITIES  WorkerCommand_CommandType = 5
)

func (x *TaskConfig) Reset()         { *x = TaskConfig{} }
func (x *TaskConfig) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskConfig) ProtoMessage()    {}
func (x *TaskConfig) ProtoReflect() protoreflect.Message { return nil }

func (x *Task) Reset()         { *x = Task{} }
func (x *Task) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Task) ProtoMessage()    {}
func (x *Task) ProtoReflect() protoreflect.Message { return nil }

func (x *TaskShard) Reset()         { *x = TaskShard{} }
func (x *TaskShard) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskShard) ProtoMessage()    {}
func (x *TaskShard) ProtoReflect() protoreflect.Message { return nil }

func (x *CreateTaskRequest) Reset()         { *x = CreateTaskRequest{} }
func (x *CreateTaskRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *CreateTaskResponse) Reset()         { *x = CreateTaskResponse{} }
func (x *CreateTaskResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateTaskResponse) ProtoMessage()    {}
func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *GetTaskRequest) Reset()         { *x = GetTaskRequest{} }
func (x *GetTaskRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetTaskRequest) ProtoMessage()    {}
func (x *GetTaskRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *GetTaskResponse) Reset()         { *x = GetTaskResponse{} }
func (x *GetTaskResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetTaskResponse) ProtoMessage()    {}
func (x *GetTaskResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *ListTasksRequest) Reset()         { *x = ListTasksRequest{} }
func (x *ListTasksRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListTasksRequest) ProtoMessage()    {}
func (x *ListTasksRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *ListTasksResponse) Reset()         { *x = ListTasksResponse{} }
func (x *ListTasksResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListTasksResponse) ProtoMessage()    {}
func (x *ListTasksResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *UpdateTaskStatusRequest) Reset()         { *x = UpdateTaskStatusRequest{} }
func (x *UpdateTaskStatusRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateTaskStatusRequest) ProtoMessage()    {}
func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *UpdateTaskStatusResponse) Reset()         { *x = UpdateTaskStatusResponse{} }
func (x *UpdateTaskStatusResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateTaskStatusResponse) ProtoMessage()    {}
func (x *UpdateTaskStatusResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *CancelTaskRequest) Reset()         { *x = CancelTaskRequest{} }
func (x *CancelTaskRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CancelTaskRequest) ProtoMessage()    {}
func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *CancelTaskResponse) Reset()         { *x = CancelTaskResponse{} }
func (x *CancelTaskResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CancelTaskResponse) ProtoMessage()    {}
func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *ContinuousParameter) Reset()         { *x = ContinuousParameter{} }
func (x *ContinuousParameter) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ContinuousParameter) ProtoMessage()    {}
func (x *ContinuousParameter) ProtoReflect() protoreflect.Message { return nil }

func (x *DiscreteParameter) Reset()         { *x = DiscreteParameter{} }
func (x *DiscreteParameter) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DiscreteParameter) ProtoMessage()    {}
func (x *DiscreteParameter) ProtoReflect() protoreflect.Message { return nil }

func (x *CategoricalParameter) Reset()         { *x = CategoricalParameter{} }
func (x *CategoricalParameter) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CategoricalParameter) ProtoMessage()    {}
func (x *CategoricalParameter) ProtoReflect() protoreflect.Message { return nil }

func (x *Parameter) Reset()         { *x = Parameter{} }
func (x *Parameter) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Parameter) ProtoMessage()    {}
func (x *Parameter) ProtoReflect() protoreflect.Message { return nil }

func (x *ParameterValue) Reset()         { *x = ParameterValue{} }
func (x *ParameterValue) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ParameterValue) ProtoMessage()    {}
func (x *ParameterValue) ProtoReflect() protoreflect.Message { return nil }

func (x *ParameterSpace) Reset()         { *x = ParameterSpace{} }
func (x *ParameterSpace) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ParameterSpace) ProtoMessage()    {}
func (x *ParameterSpace) ProtoReflect() protoreflect.Message { return nil }

func (x *ParameterCombination) Reset()         { *x = ParameterCombination{} }
func (x *ParameterCombination) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ParameterCombination) ProtoMessage()    {}
func (x *ParameterCombination) ProtoReflect() protoreflect.Message { return nil }

func (x *ValidateParameterRequest) Reset()         { *x = ValidateParameterRequest{} }
func (x *ValidateParameterRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ValidateParameterRequest) ProtoMessage()    {}
func (x *ValidateParameterRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *ValidateParameterResponse) Reset()         { *x = ValidateParameterResponse{} }
func (x *ValidateParameterResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ValidateParameterResponse) ProtoMessage()    {}
func (x *ValidateParameterResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *GradientRequirement) Reset()         { *x = GradientRequirement{} }
func (x *GradientRequirement) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GradientRequirement) ProtoMessage()    {}
func (x *GradientRequirement) ProtoReflect() protoreflect.Message { return nil }

func (x *Constraint) Reset()         { *x = Constraint{} }
func (x *Constraint) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Constraint) ProtoMessage()    {}
func (x *Constraint) ProtoReflect() protoreflect.Message { return nil }

func (x *ObjectiveFunction) Reset()         { *x = ObjectiveFunction{} }
func (x *ObjectiveFunction) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ObjectiveFunction) ProtoMessage()    {}
func (x *ObjectiveFunction) ProtoReflect() protoreflect.Message { return nil }

func (x *EvaluateRequest) Reset()         { *x = EvaluateRequest{} }
func (x *EvaluateRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*EvaluateRequest) ProtoMessage()    {}
func (x *EvaluateRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *EvaluateResponse) Reset()         { *x = EvaluateResponse{} }
func (x *EvaluateResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*EvaluateResponse) ProtoMessage()    {}
func (x *EvaluateResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *ConstraintViolation) Reset()         { *x = ConstraintViolation{} }
func (x *ConstraintViolation) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ConstraintViolation) ProtoMessage()    {}
func (x *ConstraintViolation) ProtoReflect() protoreflect.Message { return nil }

func (x *ValidateObjectiveRequest) Reset()         { *x = ValidateObjectiveRequest{} }
func (x *ValidateObjectiveRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ValidateObjectiveRequest) ProtoMessage()    {}
func (x *ValidateObjectiveRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *ValidateObjectiveResponse) Reset()         { *x = ValidateObjectiveResponse{} }
func (x *ValidateObjectiveResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ValidateObjectiveResponse) ProtoMessage()    {}
func (x *ValidateObjectiveResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *CheckpointData) Reset()         { *x = CheckpointData{} }
func (x *CheckpointData) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CheckpointData) ProtoMessage()    {}
func (x *CheckpointData) ProtoReflect() protoreflect.Message { return nil }

func (x *IntermediateState) Reset()         { *x = IntermediateState{} }
func (x *IntermediateState) String() string { return protoimpl.X.MessageStringOf(x) }
func (*IntermediateState) ProtoMessage()    {}
func (x *IntermediateState) ProtoReflect() protoreflect.Message { return nil }

func (x *ProgressUpdate) Reset()         { *x = ProgressUpdate{} }
func (x *ProgressUpdate) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ProgressUpdate) ProtoMessage()    {}
func (x *ProgressUpdate) ProtoReflect() protoreflect.Message { return nil }

func (x *Heartbeat) Reset()         { *x = Heartbeat{} }
func (x *Heartbeat) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Heartbeat) ProtoMessage()    {}
func (x *Heartbeat) ProtoReflect() protoreflect.Message { return nil }

func (x *ComputeRequest) Reset()         { *x = ComputeRequest{} }
func (x *ComputeRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ComputeRequest) ProtoMessage()    {}
func (x *ComputeRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *ComputeResponse) Reset()         { *x = ComputeResponse{} }
func (x *ComputeResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ComputeResponse) ProtoMessage()    {}
func (x *ComputeResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *TaskAssignment) Reset()         { *x = TaskAssignment{} }
func (x *TaskAssignment) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskAssignment) ProtoMessage()    {}
func (x *TaskAssignment) ProtoReflect() protoreflect.Message { return nil }

func (x *TaskAssignmentAck) Reset()         { *x = TaskAssignmentAck{} }
func (x *TaskAssignmentAck) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskAssignmentAck) ProtoMessage()    {}
func (x *TaskAssignmentAck) ProtoReflect() protoreflect.Message { return nil }

func (x *TaskStatusUpdate) Reset()         { *x = TaskStatusUpdate{} }
func (x *TaskStatusUpdate) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskStatusUpdate) ProtoMessage()    {}
func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message { return nil }

func (x *TaskCancellation) Reset()         { *x = TaskCancellation{} }
func (x *TaskCancellation) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskCancellation) ProtoMessage()    {}
func (x *TaskCancellation) ProtoReflect() protoreflect.Message { return nil }

func (x *CheckpointRequest) Reset()         { *x = CheckpointRequest{} }
func (x *CheckpointRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CheckpointRequest) ProtoMessage()    {}
func (x *CheckpointRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *ComputeResult) Reset()         { *x = ComputeResult{} }
func (x *ComputeResult) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ComputeResult) ProtoMessage()    {}
func (x *ComputeResult) ProtoReflect() protoreflect.Message { return nil }

func (x *ComputeError) Reset()         { *x = ComputeError{} }
func (x *ComputeError) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ComputeError) ProtoMessage()    {}
func (x *ComputeError) ProtoReflect() protoreflect.Message { return nil }

func (x *SubmitResultRequest) Reset()         { *x = SubmitResultRequest{} }
func (x *SubmitResultRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SubmitResultRequest) ProtoMessage()    {}
func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *SubmitResultResponse) Reset()         { *x = SubmitResultResponse{} }
func (x *SubmitResultResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SubmitResultResponse) ProtoMessage()    {}
func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *GetShardRequest) Reset()         { *x = GetShardRequest{} }
func (x *GetShardRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetShardRequest) ProtoMessage()    {}
func (x *GetShardRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *GetShardResponse) Reset()         { *x = GetShardResponse{} }
func (x *GetShardResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetShardResponse) ProtoMessage()    {}
func (x *GetShardResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *ResourceInfo) Reset()         { *x = ResourceInfo{} }
func (x *ResourceInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ResourceInfo) ProtoMessage()    {}
func (x *ResourceInfo) ProtoReflect() protoreflect.Message { return nil }

func (x *LoadInfo) Reset()         { *x = LoadInfo{} }
func (x *LoadInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (*LoadInfo) ProtoMessage()    {}
func (x *LoadInfo) ProtoReflect() protoreflect.Message { return nil }

func (x *WorkerCapabilities) Reset()         { *x = WorkerCapabilities{} }
func (x *WorkerCapabilities) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WorkerCapabilities) ProtoMessage()    {}
func (x *WorkerCapabilities) ProtoReflect() protoreflect.Message { return nil }

func (x *WorkerInfo) Reset()         { *x = WorkerInfo{} }
func (x *WorkerInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WorkerInfo) ProtoMessage()    {}
func (x *WorkerInfo) ProtoReflect() protoreflect.Message { return nil }

func (x *RegisterWorkerRequest) Reset()         { *x = RegisterWorkerRequest{} }
func (x *RegisterWorkerRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterWorkerRequest) ProtoMessage()    {}
func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *RegisterWorkerResponse) Reset()         { *x = RegisterWorkerResponse{} }
func (x *RegisterWorkerResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterWorkerResponse) ProtoMessage()    {}
func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *UnregisterWorkerRequest) Reset()         { *x = UnregisterWorkerRequest{} }
func (x *UnregisterWorkerRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UnregisterWorkerRequest) ProtoMessage()    {}
func (x *UnregisterWorkerRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *UnregisterWorkerResponse) Reset()         { *x = UnregisterWorkerResponse{} }
func (x *UnregisterWorkerResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UnregisterWorkerResponse) ProtoMessage()    {}
func (x *UnregisterWorkerResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *HeartbeatRequest) Reset()         { *x = HeartbeatRequest{} }
func (x *HeartbeatRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *HeartbeatResponse) Reset()         { *x = HeartbeatResponse{} }
func (x *HeartbeatResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *GetWorkerRequest) Reset()         { *x = GetWorkerRequest{} }
func (x *GetWorkerRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetWorkerRequest) ProtoMessage()    {}
func (x *GetWorkerRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *GetWorkerResponse) Reset()         { *x = GetWorkerResponse{} }
func (x *GetWorkerResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetWorkerResponse) ProtoMessage()    {}
func (x *GetWorkerResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *ListWorkersRequest) Reset()         { *x = ListWorkersRequest{} }
func (x *ListWorkersRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListWorkersRequest) ProtoMessage()    {}
func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *ListWorkersResponse) Reset()         { *x = ListWorkersResponse{} }
func (x *ListWorkersResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListWorkersResponse) ProtoMessage()    {}
func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *UpdateWorkerStatusRequest) Reset()         { *x = UpdateWorkerStatusRequest{} }
func (x *UpdateWorkerStatusRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateWorkerStatusRequest) ProtoMessage()    {}
func (x *UpdateWorkerStatusRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *UpdateWorkerStatusResponse) Reset()         { *x = UpdateWorkerStatusResponse{} }
func (x *UpdateWorkerStatusResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateWorkerStatusResponse) ProtoMessage()    {}
func (x *UpdateWorkerStatusResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *WorkerStreamRequest) Reset()         { *x = WorkerStreamRequest{} }
func (x *WorkerStreamRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WorkerStreamRequest) ProtoMessage()    {}
func (x *WorkerStreamRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *WorkerStreamResponse) Reset()         { *x = WorkerStreamResponse{} }
func (x *WorkerStreamResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WorkerStreamResponse) ProtoMessage()    {}
func (x *WorkerStreamResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *WorkerCommand) Reset()         { *x = WorkerCommand{} }
func (x *WorkerCommand) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WorkerCommand) ProtoMessage()    {}
func (x *WorkerCommand) ProtoReflect() protoreflect.Message { return nil }

func (*Parameter_Continuous) isParameter_Parameter() {}
func (*Parameter_Discrete) isParameter_Parameter()   {}
func (*Parameter_Categorical) isParameter_Parameter() {}

func (*ParameterValue_DoubleValue) isParameterValue_Value() {}
func (*ParameterValue_IntValue) isParameterValue_Value()    {}
func (*ParameterValue_StringValue) isParameterValue_Value() {}

func (*ComputeRequest_Assignment) isComputeRequest_Request()   {}
func (*ComputeRequest_Heartbeat) isComputeRequest_Request()    {}
func (*ComputeRequest_Progress) isComputeRequest_Request()     {}
func (*ComputeRequest_Result) isComputeRequest_Request()       {}
func (*ComputeRequest_Intermediate) isComputeRequest_Request() {}
func (*ComputeRequest_Error) isComputeRequest_Request()        {}

func (*ComputeResponse_Ack) isComputeResponse_Response()             {}
func (*ComputeResponse_StatusUpdate) isComputeResponse_Response()    {}
func (*ComputeResponse_Cancellation) isComputeResponse_Response()    {}
func (*ComputeResponse_CheckpointRequest) isComputeResponse_Response() {}

func (*WorkerStreamRequest_Register) isWorkerStreamRequest_Request()   {}
func (*WorkerStreamRequest_Heartbeat) isWorkerStreamRequest_Request()  {}
func (*WorkerStreamRequest_Unregister) isWorkerStreamRequest_Request() {}
func (*WorkerStreamRequest_LoadUpdate) isWorkerStreamRequest_Request() {}

func (*WorkerStreamResponse_RegisterAck) isWorkerStreamResponse_Response()  {}
func (*WorkerStreamResponse_HeartbeatAck) isWorkerStreamResponse_Response() {}
func (*WorkerStreamResponse_StatusUpdate) isWorkerStreamResponse_Response() {}
func (*WorkerStreamResponse_Command) isWorkerStreamResponse_Response()      {}