// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// 	protoc-gen-go-grpc v1.3.0
// 	protoc             v4.25.0
// source: distcomp/v1/distcomp.proto

package v1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const (
	TaskService_CreateTask_FullMethodName       = "/distcomp.v1.TaskService/CreateTask"
	TaskService_GetTask_FullMethodName          = "/distcomp.v1.TaskService/GetTask"
	TaskService_ListTasks_FullMethodName        = "/distcomp.v1.TaskService/ListTasks"
	TaskService_UpdateTaskStatus_FullMethodName = "/distcomp.v1.TaskService/UpdateTaskStatus"
	TaskService_CancelTask_FullMethodName       = "/distcomp.v1.TaskService/CancelTask"
	TaskService_StreamTaskStatus_FullMethodName = "/distcomp.v1.TaskService/StreamTaskStatus"
	TaskService_StreamCreateTask_FullMethodName = "/distcomp.v1.TaskService/StreamCreateTask"
)

type TaskServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*UpdateTaskStatusResponse, error)
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	StreamTaskStatus(ctx context.Context, opts ...grpc.CallOption) (TaskService_StreamTaskStatusClient, error)
	StreamCreateTask(ctx context.Context, opts ...grpc.CallOption) (TaskService_StreamCreateTaskClient, error)
}

type TaskServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	UpdateTaskStatus(context.Context, *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error)
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	StreamTaskStatus(TaskService_StreamTaskStatusServer) error
	StreamCreateTask(TaskService_StreamCreateTaskServer) error
}

type TaskService_StreamTaskStatusClient interface {
	Send(*GetTaskRequest) error
	Recv() (*Task, error)
	grpc.ClientStream
}

type TaskService_StreamTaskStatusServer interface {
	Send(*Task) error
	Recv() (*GetTaskRequest, error)
	grpc.ServerStream
}

type TaskService_StreamCreateTaskClient interface {
	Send(*CreateTaskRequest) error
	Recv() (*CreateTaskResponse, error)
	grpc.ClientStream
}

type TaskService_StreamCreateTaskServer interface {
	Send(*CreateTaskResponse) error
	Recv() (*CreateTaskRequest, error)
	grpc.ServerStream
}

const (
	ComputeService_SubmitResult_FullMethodName    = "/distcomp.v1.ComputeService/SubmitResult"
	ComputeService_GetShard_FullMethodName        = "/distcomp.v1.ComputeService/GetShard"
	ComputeService_StreamCompute_FullMethodName   = "/distcomp.v1.ComputeService/StreamCompute"
	ComputeService_StreamHeartbeat_FullMethodName = "/distcomp.v1.ComputeService/StreamHeartbeat"
	ComputeService_StreamProgress_FullMethodName  = "/distcomp.v1.ComputeService/StreamProgress"
)

type ComputeServiceClient interface {
	SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error)
	GetShard(ctx context.Context, in *GetShardRequest, opts ...grpc.CallOption) (*GetShardResponse, error)
	StreamCompute(ctx context.Context, opts ...grpc.CallOption) (ComputeService_StreamComputeClient, error)
	StreamHeartbeat(ctx context.Context, opts ...grpc.CallOption) (ComputeService_StreamHeartbeatClient, error)
	StreamProgress(ctx context.Context, opts ...grpc.CallOption) (ComputeService_StreamProgressClient, error)
}

type ComputeServiceServer interface {
	SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error)
	GetShard(context.Context, *GetShardRequest) (*GetShardResponse, error)
	StreamCompute(ComputeService_StreamComputeServer) error
	StreamHeartbeat(ComputeService_StreamHeartbeatServer) error
	StreamProgress(ComputeService_StreamProgressServer) error
}

type ComputeService_StreamComputeClient interface {
	Send(*ComputeRequest) error
	Recv() (*ComputeResponse, error)
	grpc.ClientStream
}

type ComputeService_StreamComputeServer interface {
	Send(*ComputeResponse) error
	Recv() (*ComputeRequest, error)
	grpc.ServerStream
}

type ComputeService_StreamHeartbeatClient interface {
	Send(*Heartbeat) error
	Recv() (*TaskStatusUpdate, error)
	grpc.ClientStream
}

type ComputeService_StreamHeartbeatServer interface {
	Send(*TaskStatusUpdate) error
	Recv() (*Heartbeat, error)
	grpc.ServerStream
}

type ComputeService_StreamProgressClient interface {
	Send(*ProgressUpdate) error
	Recv() (*TaskCancellation, error)
	grpc.ClientStream
}

type ComputeService_StreamProgressServer interface {
	Send(*TaskCancellation) error
	Recv() (*ProgressUpdate, error)
	grpc.ServerStream
}

const (
	WorkerService_RegisterWorker_FullMethodName       = "/distcomp.v1.WorkerService/RegisterWorker"
	WorkerService_UnregisterWorker_FullMethodName     = "/distcomp.v1.WorkerService/UnregisterWorker"
	WorkerService_Heartbeat_FullMethodName            = "/distcomp.v1.WorkerService/Heartbeat"
	WorkerService_GetWorker_FullMethodName            = "/distcomp.v1.WorkerService/GetWorker"
	WorkerService_ListWorkers_FullMethodName          = "/distcomp.v1.WorkerService/ListWorkers"
	WorkerService_UpdateWorkerStatus_FullMethodName   = "/distcomp.v1.WorkerService/UpdateWorkerStatus"
	WorkerService_StreamWorker_FullMethodName         = "/distcomp.v1.WorkerService/StreamWorker"
	WorkerService_StreamHeartbeat_FullMethodName      = "/distcomp.v1.WorkerService/StreamHeartbeat"
)

type WorkerServiceClient interface {
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	UnregisterWorker(ctx context.Context, in *UnregisterWorkerRequest, opts ...grpc.CallOption) (*UnregisterWorkerResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetWorker(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*GetWorkerResponse, error)
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	UpdateWorkerStatus(ctx context.Context, in *UpdateWorkerStatusRequest, opts ...grpc.CallOption) (*UpdateWorkerStatusResponse, error)
	StreamWorker(ctx context.Context, opts ...grpc.CallOption) (WorkerService_StreamWorkerClient, error)
	StreamHeartbeat(ctx context.Context, opts ...grpc.CallOption) (WorkerService_StreamHeartbeatClient, error)
}

type WorkerServiceServer interface {
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	UnregisterWorker(context.Context, *UnregisterWorkerRequest) (*UnregisterWorkerResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetWorker(context.Context, *GetWorkerRequest) (*GetWorkerResponse, error)
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	UpdateWorkerStatus(context.Context, *UpdateWorkerStatusRequest) (*UpdateWorkerStatusResponse, error)
	StreamWorker(WorkerService_StreamWorkerServer) error
	StreamHeartbeat(WorkerService_StreamHeartbeatServer) error
}

type WorkerService_StreamWorkerClient interface {
	Send(*WorkerStreamRequest) error
	Recv() (*WorkerStreamResponse, error)
	grpc.ClientStream
}

type WorkerService_StreamWorkerServer interface {
	Send(*WorkerStreamResponse) error
	Recv() (*WorkerStreamRequest, error)
	grpc.ServerStream
}

type WorkerService_StreamHeartbeatClient interface {
	Send(*HeartbeatRequest) error
	Recv() (*HeartbeatResponse, error)
	grpc.ClientStream
}

type WorkerService_StreamHeartbeatServer interface {
	Send(*HeartbeatResponse) error
	Recv() (*HeartbeatRequest, error)
	grpc.ServerStream
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func RegisterComputeServiceServer(s grpc.ServiceRegistrar, srv ComputeServiceServer) {
	s.RegisterService(&ComputeService_ServiceDesc, srv)
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distcomp.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskService_ListTasks_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _TaskService_UpdateTaskStatus_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _TaskService_CancelTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTaskStatus",
			Handler:       _TaskService_StreamTaskStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamCreateTask",
			Handler:       _TaskService_StreamCreateTask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "distcomp/v1/distcomp.proto",
}

var ComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distcomp.v1.ComputeService",
	HandlerType: (*ComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitResult",
			Handler:    _ComputeService_SubmitResult_Handler,
		},
		{
			MethodName: "GetShard",
			Handler:    _ComputeService_GetShard_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCompute",
			Handler:       _ComputeService_StreamCompute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamHeartbeat",
			Handler:       _ComputeService_StreamHeartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamProgress",
			Handler:       _ComputeService_StreamProgress_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "distcomp/v1/distcomp.proto",
}

var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distcomp.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _WorkerService_RegisterWorker_Handler,
		},
		{
			MethodName: "UnregisterWorker",
			Handler:    _WorkerService_UnregisterWorker_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerService_Heartbeat_Handler,
		},
		{
			MethodName: "GetWorker",
			Handler:    _WorkerService_GetWorker_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _WorkerService_ListWorkers_Handler,
		},
		{
			MethodName: "UpdateWorkerStatus",
			Handler:    _WorkerService_UpdateWorkerStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWorker",
			Handler:       _WorkerService_StreamWorker_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamHeartbeat",
			Handler:       _WorkerService_StreamHeartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "distcomp/v1/distcomp.proto",
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTaskStatus(ctx, req.(*UpdateTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_StreamTaskStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).StreamTaskStatus(&taskServiceStreamTaskStatusServer{stream})
}

type taskServiceStreamTaskStatusServer struct {
	grpc.ServerStream
}

func (x *taskServiceStreamTaskStatusServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

func (x *taskServiceStreamTaskStatusServer) Recv() (*GetTaskRequest, error) {
	m := new(GetTaskRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TaskService_StreamCreateTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).StreamCreateTask(&taskServiceStreamCreateTaskServer{stream})
}

type taskServiceStreamCreateTaskServer struct {
	grpc.ServerStream
}

func (x *taskServiceStreamCreateTaskServer) Send(m *CreateTaskResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *taskServiceStreamCreateTaskServer) Recv() (*CreateTaskRequest, error) {
	m := new(CreateTaskRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputeService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).SubmitResult(ctx, req.(*SubmitResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GetShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GetShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GetShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GetShard(ctx, req.(*GetShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_StreamCompute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServiceServer).StreamCompute(&computeServiceStreamComputeServer{stream})
}

type computeServiceStreamComputeServer struct {
	grpc.ServerStream
}

func (x *computeServiceStreamComputeServer) Send(m *ComputeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computeServiceStreamComputeServer) Recv() (*ComputeRequest, error) {
	m := new(ComputeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputeService_StreamHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServiceServer).StreamHeartbeat(&computeServiceStreamHeartbeatServer{stream})
}

type computeServiceStreamHeartbeatServer struct {
	grpc.ServerStream
}

func (x *computeServiceStreamHeartbeatServer) Send(m *TaskStatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computeServiceStreamHeartbeatServer) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputeService_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServiceServer).StreamProgress(&computeServiceStreamProgressServer{stream})
}

type computeServiceStreamProgressServer struct {
	grpc.ServerStream
}

func (x *computeServiceStreamProgressServer) Send(m *TaskCancellation) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computeServiceStreamProgressServer) Recv() (*ProgressUpdate, error) {
	m := new(ProgressUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WorkerService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_UnregisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).UnregisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_UnregisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).UnregisterWorker(ctx, req.(*UnregisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetWorker(ctx, req.(*GetWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_UpdateWorkerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).UpdateWorkerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_UpdateWorkerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).UpdateWorkerStatus(ctx, req.(*UpdateWorkerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StreamWorker_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).StreamWorker(&workerServiceStreamWorkerServer{stream})
}

type workerServiceStreamWorkerServer struct {
	grpc.ServerStream
}

func (x *workerServiceStreamWorkerServer) Send(m *WorkerStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerServiceStreamWorkerServer) Recv() (*WorkerStreamRequest, error) {
	m := new(WorkerStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WorkerService_StreamHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).StreamHeartbeat(&workerServiceStreamHeartbeatServer{stream})
}

type workerServiceStreamHeartbeatServer struct {
	grpc.ServerStream
}

func (x *workerServiceStreamHeartbeatServer) Send(m *HeartbeatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerServiceStreamHeartbeatServer) Recv() (*HeartbeatRequest, error) {
	m := new(HeartbeatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CreateTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*UpdateTaskStatusResponse, error) {
	out := new(UpdateTaskStatusResponse)
	err := c.cc.Invoke(ctx, TaskService_UpdateTaskStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CancelTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) StreamTaskStatus(ctx context.Context, opts ...grpc.CallOption) (TaskService_StreamTaskStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[0], TaskService_StreamTaskStatus_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceStreamTaskStatusClient{stream}
	return x, nil
}

type taskServiceStreamTaskStatusClient struct {
	grpc.ClientStream
}

func (x *taskServiceStreamTaskStatusClient) Send(m *GetTaskRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *taskServiceStreamTaskStatusClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taskServiceClient) StreamCreateTask(ctx context.Context, opts ...grpc.CallOption) (TaskService_StreamCreateTaskClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[1], TaskService_StreamCreateTask_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceStreamCreateTaskClient{stream}
	return x, nil
}

type taskServiceStreamCreateTaskClient struct {
	grpc.ClientStream
}

func (x *taskServiceStreamCreateTaskClient) Send(m *CreateTaskRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *taskServiceStreamCreateTaskClient) Recv() (*CreateTaskResponse, error) {
	m := new(CreateTaskResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}

func (UnimplementedTaskServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}

func (UnimplementedTaskServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}

func (UnimplementedTaskServiceServer) UpdateTaskStatus(context.Context, *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTaskStatus not implemented")
}

func (UnimplementedTaskServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}

func (UnimplementedTaskServiceServer) StreamTaskStatus(TaskService_StreamTaskStatusServer) error {
	return status.Error(codes.Unimplemented, "method StreamTaskStatus not implemented")
}

func (UnimplementedTaskServiceServer) StreamCreateTask(TaskService_StreamCreateTaskServer) error {
	return status.Error(codes.Unimplemented, "method StreamCreateTask not implemented")
}

func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

type computeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeServiceClient(cc grpc.ClientConnInterface) ComputeServiceClient {
	return &computeServiceClient{cc}
}

func (c *computeServiceClient) SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error) {
	out := new(SubmitResultResponse)
	err := c.cc.Invoke(ctx, ComputeService_SubmitResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GetShard(ctx context.Context, in *GetShardRequest, opts ...grpc.CallOption) (*GetShardResponse, error) {
	out := new(GetShardResponse)
	err := c.cc.Invoke(ctx, ComputeService_GetShard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) StreamCompute(ctx context.Context, opts ...grpc.CallOption) (ComputeService_StreamComputeClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[0], ComputeService_StreamCompute_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceStreamComputeClient{stream}
	return x, nil
}

type computeServiceStreamComputeClient struct {
	grpc.ClientStream
}

func (x *computeServiceStreamComputeClient) Send(m *ComputeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computeServiceStreamComputeClient) Recv() (*ComputeResponse, error) {
	m := new(ComputeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computeServiceClient) StreamHeartbeat(ctx context.Context, opts ...grpc.CallOption) (ComputeService_StreamHeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[1], ComputeService_StreamHeartbeat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceStreamHeartbeatClient{stream}
	return x, nil
}

type computeServiceStreamHeartbeatClient struct {
	grpc.ClientStream
}

func (x *computeServiceStreamHeartbeatClient) Send(m *Heartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computeServiceStreamHeartbeatClient) Recv() (*TaskStatusUpdate, error) {
	m := new(TaskStatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computeServiceClient) StreamProgress(ctx context.Context, opts ...grpc.CallOption) (ComputeService_StreamProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[2], ComputeService_StreamProgress_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceStreamProgressClient{stream}
	return x, nil
}

type computeServiceStreamProgressClient struct {
	grpc.ClientStream
}

func (x *computeServiceStreamProgressClient) Send(m *ProgressUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computeServiceStreamProgressClient) Recv() (*TaskCancellation, error) {
	m := new(TaskCancellation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type UnimplementedComputeServiceServer struct{}

func (UnimplementedComputeServiceServer) SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}

func (UnimplementedComputeServiceServer) GetShard(context.Context, *GetShardRequest) (*GetShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShard not implemented")
}

func (UnimplementedComputeServiceServer) StreamCompute(ComputeService_StreamComputeServer) error {
	return status.Error(codes.Unimplemented, "method StreamCompute not implemented")
}

func (UnimplementedComputeServiceServer) StreamHeartbeat(ComputeService_StreamHeartbeatServer) error {
	return status.Error(codes.Unimplemented, "method StreamHeartbeat not implemented")
}

func (UnimplementedComputeServiceServer) StreamProgress(ComputeService_StreamProgressServer) error {
	return status.Error(codes.Unimplemented, "method StreamProgress not implemented")
}

func (UnimplementedComputeServiceServer) mustEmbedUnimplementedComputeServiceServer() {}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_RegisterWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) UnregisterWorker(ctx context.Context, in *UnregisterWorkerRequest, opts ...grpc.CallOption) (*UnregisterWorkerResponse, error) {
	out := new(UnregisterWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_UnregisterWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetWorker(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*GetWorkerResponse, error) {
	out := new(GetWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) UpdateWorkerStatus(ctx context.Context, in *UpdateWorkerStatusRequest, opts ...grpc.CallOption) (*UpdateWorkerStatusResponse, error) {
	out := new(UpdateWorkerStatusResponse)
	err := c.cc.Invoke(ctx, WorkerService_UpdateWorkerStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListWorkers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StreamWorker(ctx context.Context, opts ...grpc.CallOption) (WorkerService_StreamWorkerClient, error) {
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_StreamWorker_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &workerServiceStreamWorkerClient{stream}
	return x, nil
}

type workerServiceStreamWorkerClient struct {
	grpc.ClientStream
}

func (x *workerServiceStreamWorkerClient) Send(m *WorkerStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerServiceStreamWorkerClient) Recv() (*WorkerStreamResponse, error) {
	m := new(WorkerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerServiceClient) StreamHeartbeat(ctx context.Context, opts ...grpc.CallOption) (WorkerService_StreamHeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[1], WorkerService_StreamHeartbeat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &workerServiceStreamHeartbeatClient{stream}
	return x, nil
}

type workerServiceStreamHeartbeatClient struct {
	grpc.ClientStream
}

func (x *workerServiceStreamHeartbeatClient) Send(m *HeartbeatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerServiceStreamHeartbeatClient) Recv() (*HeartbeatResponse, error) {
	m := new(HeartbeatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}

func (UnimplementedWorkerServiceServer) UnregisterWorker(context.Context, *UnregisterWorkerRequest) (*UnregisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterWorker not implemented")
}

func (UnimplementedWorkerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}

func (UnimplementedWorkerServiceServer) GetWorker(context.Context, *GetWorkerRequest) (*GetWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorker not implemented")
}

func (UnimplementedWorkerServiceServer) UpdateWorkerStatus(context.Context, *UpdateWorkerStatusRequest) (*UpdateWorkerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkerStatus not implemented")
}

func (UnimplementedWorkerServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}

func (UnimplementedWorkerServiceServer) StreamWorker(WorkerService_StreamWorkerServer) error {
	return status.Error(codes.Unimplemented, "method StreamWorker not implemented")
}

func (UnimplementedWorkerServiceServer) StreamHeartbeat(WorkerService_StreamHeartbeatServer) error {
	return status.Error(codes.Unimplemented, "method StreamHeartbeat not implemented")
}

func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
