CREATE TABLE IF NOT EXISTS `device` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `device_key` VARCHAR(128) NOT NULL COMMENT '设备唯一标识',
  `device_name` VARCHAR(128) DEFAULT NULL COMMENT '设备名称',
  `device_type` VARCHAR(64) DEFAULT NULL COMMENT '设备类型',
  `product_key` VARCHAR(64) DEFAULT NULL COMMENT '产品密钥',
  `firmware_version` VARCHAR(64) DEFAULT NULL COMMENT '固件版本',
  `status` VARCHAR(32) NOT NULL DEFAULT 'inactive' COMMENT '设备状态:inactive/active/offline/online',
  `auth_type` VARCHAR(32) DEFAULT 'token' COMMENT '认证类型:token/certificate',
  `auth_secret` VARCHAR(512) DEFAULT NULL COMMENT '认证密钥',
  `metadata` JSON DEFAULT NULL COMMENT '元数据',
  `last_online_at` DATETIME DEFAULT NULL COMMENT '最后上线时间',
  `activated_at` DATETIME DEFAULT NULL COMMENT '激活时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_device_key` (`device_key`),
  KEY `idx_status` (`status`),
  KEY `idx_product_key` (`product_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备表';

CREATE TABLE IF NOT EXISTS `rule` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `rule_id` VARCHAR(64) NOT NULL COMMENT '规则ID',
  `rule_name` VARCHAR(128) DEFAULT NULL COMMENT '规则名称',
  `description` VARCHAR(512) DEFAULT NULL COMMENT '规则描述',
  `trigger_type` VARCHAR(32) NOT NULL COMMENT '触发类型:timer/event/data',
  `trigger_config` JSON DEFAULT NULL COMMENT '触发配置',
  `condition_expression` TEXT DEFAULT NULL COMMENT '条件表达式',
  `action_type` VARCHAR(32) NOT NULL COMMENT '动作类型:command/notify/mqtt',
  `action_config` JSON DEFAULT NULL COMMENT '动作配置',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_id` (`rule_id`),
  KEY `idx_trigger_type` (`trigger_type`),
  KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='规则表';

CREATE TABLE IF NOT EXISTS `rule_execution` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `run_id` VARCHAR(64) NOT NULL COMMENT '运行实例ID',
  `rule_id` VARCHAR(64) NOT NULL COMMENT '规则ID',
  `device_key` VARCHAR(128) DEFAULT NULL COMMENT '设备标识',
  `phase` VARCHAR(32) NOT NULL COMMENT '执行阶段:pending/executing/completed/failed',
  `progress` DECIMAL(5,2) DEFAULT 0.00 COMMENT '执行进度',
  `trigger_data` JSON DEFAULT NULL COMMENT '触发数据',
  `result_data` JSON DEFAULT NULL COMMENT '执行结果',
  `error_detail` TEXT DEFAULT NULL COMMENT '错误详情',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_run_id` (`run_id`),
  KEY `idx_rule_id` (`rule_id`),
  KEY `idx_phase` (`phase`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='规则执行记录表';

CREATE TABLE IF NOT EXISTS `firmware` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `firmware_id` VARCHAR(64) NOT NULL COMMENT '固件ID',
  `firmware_name` VARCHAR(128) DEFAULT NULL COMMENT '固件名称',
  `product_key` VARCHAR(64) NOT NULL COMMENT '产品密钥',
  `version` VARCHAR(64) NOT NULL COMMENT '固件版本',
  `file_path` VARCHAR(512) DEFAULT NULL COMMENT '文件路径',
  `file_size` BIGINT DEFAULT 0 COMMENT '文件大小',
  `md5` VARCHAR(64) DEFAULT NULL COMMENT 'MD5校验值',
  `signature` VARCHAR(512) DEFAULT NULL COMMENT '数字签名',
  `diff_from_version` VARCHAR(64) DEFAULT NULL COMMENT '差分升级源版本',
  `diff_file_path` VARCHAR(512) DEFAULT NULL COMMENT '差分文件路径',
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '状态:draft/published/retired',
  `release_notes` TEXT DEFAULT NULL COMMENT '发布说明',
  `published_at` DATETIME DEFAULT NULL COMMENT '发布时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_firmware_id` (`firmware_id`),
  UNIQUE KEY `uk_product_version` (`product_key`, `version`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='固件表';

CREATE TABLE IF NOT EXISTS `ota_job` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `job_id` VARCHAR(64) NOT NULL COMMENT '升级任务ID',
  `job_name` VARCHAR(128) DEFAULT NULL COMMENT '任务名称',
  `firmware_id` VARCHAR(64) NOT NULL COMMENT '固件ID',
  `product_key` VARCHAR(64) NOT NULL COMMENT '产品密钥',
  `target_version` VARCHAR(64) NOT NULL COMMENT '目标版本',
  `upgrade_type` VARCHAR(32) NOT NULL DEFAULT 'full' COMMENT '升级类型:full/diff',
  `gray_scale_strategy` VARCHAR(32) DEFAULT 'batch' COMMENT '灰度策略:batch/percentage',
  `gray_scale_config` JSON DEFAULT NULL COMMENT '灰度配置',
  `current_batch` INT DEFAULT 0 COMMENT '当前批次',
  `total_batches` INT DEFAULT 1 COMMENT '总批次数',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态:pending/running/success/failed/rolledback',
  `rollback_firmware_id` VARCHAR(64) DEFAULT NULL COMMENT '回滚固件ID',
  `auto_rollback_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否自动回滚',
  `success_rate_threshold` DECIMAL(5,2) DEFAULT 90.00 COMMENT '成功率阈值',
  `scheduled_at` DATETIME DEFAULT NULL COMMENT '计划执行时间',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_id` (`job_id`),
  KEY `idx_firmware_id` (`firmware_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OTA升级任务表';

CREATE TABLE IF NOT EXISTS `ota_device_upgrade` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `job_id` VARCHAR(64) NOT NULL COMMENT '升级任务ID',
  `device_key` VARCHAR(128) NOT NULL COMMENT '设备标识',
  `batch_number` INT DEFAULT 0 COMMENT '批次号',
  `current_version` VARCHAR(64) DEFAULT NULL COMMENT '当前版本',
  `target_version` VARCHAR(64) DEFAULT NULL COMMENT '目标版本',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态:pending/downloading/upgrading/success/failed/rollback',
  `progress` INT DEFAULT 0 COMMENT '升级进度',
  `error_code` VARCHAR(64) DEFAULT NULL COMMENT '错误码',
  `error_message` VARCHAR(512) DEFAULT NULL COMMENT '错误信息',
  `retry_count` INT DEFAULT 0 COMMENT '重试次数',
  `download_started_at` DATETIME DEFAULT NULL COMMENT '下载开始时间',
  `upgrade_started_at` DATETIME DEFAULT NULL COMMENT '升级开始时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_device` (`job_id`, `device_key`),
  KEY `idx_device_key` (`device_key`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备升级记录表';

CREATE TABLE IF NOT EXISTS `data_stream` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `stream_id` VARCHAR(64) NOT NULL COMMENT '数据流ID',
  `stream_name` VARCHAR(128) DEFAULT NULL COMMENT '数据流名称',
  `device_key` VARCHAR(128) NOT NULL COMMENT '设备标识',
  `data_type` VARCHAR(32) NOT NULL COMMENT '数据类型:telemetry/event/attribute',
  `aggregation_type` VARCHAR(32) DEFAULT 'none' COMMENT '聚合类型:none/avg/sum/count/min/max',
  `aggregation_window` VARCHAR(32) DEFAULT '1m' COMMENT '聚合窗口:1m/5m/15m/1h',
  `fields_config` JSON DEFAULT NULL COMMENT '字段配置',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  `last_aggregated_at` DATETIME DEFAULT NULL COMMENT '最后聚合时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stream_id` (`stream_id`),
  KEY `idx_device_key` (`device_key`),
  KEY `idx_aggregation_type` (`aggregation_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据流配置表';

CREATE TABLE IF NOT EXISTS `data_aggregation_result` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `result_id` VARCHAR(64) NOT NULL COMMENT '结果ID',
  `stream_id` VARCHAR(64) NOT NULL COMMENT '数据流ID',
  `device_key` VARCHAR(128) NOT NULL COMMENT '设备标识',
  `aggregation_type` VARCHAR(32) NOT NULL COMMENT '聚合类型',
  `window_start` DATETIME NOT NULL COMMENT '窗口开始时间',
  `window_end` DATETIME NOT NULL COMMENT '窗口结束时间',
  `metrics` JSON NOT NULL COMMENT '聚合指标',
  `sample_count` INT DEFAULT 0 COMMENT '样本数量',
  `uploaded` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已上传',
  `uploaded_at` DATETIME DEFAULT NULL COMMENT '上传时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_result_id` (`result_id`),
  KEY `idx_stream_window` (`stream_id`, `window_start`),
  KEY `idx_uploaded` (`uploaded`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据聚合结果表';

CREATE TABLE IF NOT EXISTS `device_shadow` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `device_key` VARCHAR(128) NOT NULL COMMENT '设备标识',
  `desired` JSON DEFAULT NULL COMMENT '期望状态',
  `reported` JSON DEFAULT NULL COMMENT '实际状态',
  `delta` JSON DEFAULT NULL COMMENT '状态差异',
  `version` INT NOT NULL DEFAULT 1 COMMENT '版本号(乐观锁)',
  `last_sync_at` DATETIME DEFAULT NULL COMMENT '最后同步时间',
  `last_desired_update_at` DATETIME DEFAULT NULL COMMENT '最后期望状态更新时间',
  `last_reported_update_at` DATETIME DEFAULT NULL COMMENT '最后实际状态更新时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_device_key` (`device_key`),
  KEY `idx_version` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备影子表';

CREATE TABLE IF NOT EXISTS `shadow_operation_log` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `log_id` VARCHAR(64) NOT NULL COMMENT '日志ID',
  `device_key` VARCHAR(128) NOT NULL COMMENT '设备标识',
  `operation_type` VARCHAR(32) NOT NULL COMMENT '操作类型:desired_update/reported_update/sync',
  `before_state` JSON DEFAULT NULL COMMENT '操作前状态',
  `after_state` JSON DEFAULT NULL COMMENT '操作后状态',
  `change_set` JSON DEFAULT NULL COMMENT '变更集',
  `operator` VARCHAR(64) DEFAULT NULL COMMENT '操作者',
  `version` INT DEFAULT NULL COMMENT '版本号',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_log_id` (`log_id`),
  KEY `idx_device_key` (`device_key`),
  KEY `idx_operation_type` (`operation_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='影子操作日志表';

CREATE TABLE IF NOT EXISTS `ai_model` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `model_id` VARCHAR(64) NOT NULL COMMENT '模型ID',
  `model_name` VARCHAR(128) DEFAULT NULL COMMENT '模型名称',
  `model_type` VARCHAR(32) NOT NULL COMMENT '模型类型:classification/detection/segmentation/custom',
  `version` VARCHAR(64) NOT NULL DEFAULT '1.0' COMMENT '模型版本',
  `format` VARCHAR(32) NOT NULL COMMENT '模型格式:onnx/tflite/pytorch',
  `file_path` VARCHAR(512) DEFAULT NULL COMMENT '模型文件路径',
  `file_size` BIGINT DEFAULT 0 COMMENT '文件大小',
  `input_spec` JSON DEFAULT NULL COMMENT '输入规格',
  `output_spec` JSON DEFAULT NULL COMMENT '输出规格',
  `metadata` JSON DEFAULT NULL COMMENT '元数据',
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '状态:draft/deployed/retired',
  `deployed_at` DATETIME DEFAULT NULL COMMENT '部署时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_model_id` (`model_id`),
  KEY `idx_model_type` (`model_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI模型表';

CREATE TABLE IF NOT EXISTS `inference_task` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `task_id` VARCHAR(64) NOT NULL COMMENT '任务ID',
  `model_id` VARCHAR(64) NOT NULL COMMENT '模型ID',
  `device_key` VARCHAR(128) DEFAULT NULL COMMENT '执行设备标识',
  `task_type` VARCHAR(32) NOT NULL COMMENT '任务类型:realtime/batch/scheduled',
  `input_data` JSON DEFAULT NULL COMMENT '输入数据',
  `input_data_path` VARCHAR(512) DEFAULT NULL COMMENT '输入数据路径',
  `priority` INT DEFAULT 5 COMMENT '优先级(1-10,10最高)',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态:pending/queued/running/completed/failed',
  `progress` INT DEFAULT 0 COMMENT '进度',
  `result_data` JSON DEFAULT NULL COMMENT '推理结果',
  `result_data_path` VARCHAR(512) DEFAULT NULL COMMENT '结果存储路径',
  `inference_latency_ms` BIGINT DEFAULT 0 COMMENT '推理耗时(ms)',
  `error_detail` TEXT DEFAULT NULL COMMENT '错误详情',
  `scheduled_at` DATETIME DEFAULT NULL COMMENT '计划执行时间',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_model_id` (`model_id`),
  KEY `idx_device_key` (`device_key`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='推理任务表';

CREATE TABLE IF NOT EXISTS `protocol_driver` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `driver_id` VARCHAR(64) NOT NULL COMMENT '驱动ID',
  `driver_name` VARCHAR(128) DEFAULT NULL COMMENT '驱动名称',
  `protocol_type` VARCHAR(32) NOT NULL COMMENT '协议类型:modbus/opcua/mqtt/s7/cip',
  `version` VARCHAR(64) NOT NULL DEFAULT '1.0' COMMENT '驱动版本',
  `driver_class` VARCHAR(512) NOT NULL COMMENT '驱动实现类',
  `config_schema` JSON DEFAULT NULL COMMENT '配置Schema',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  `loaded` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已加载',
  `loaded_at` DATETIME DEFAULT NULL COMMENT '加载时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_driver_id` (`driver_id`),
  KEY `idx_protocol_type` (`protocol_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='协议驱动表';

CREATE TABLE IF NOT EXISTS `protocol_adapter` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `adapter_id` VARCHAR(64) NOT NULL COMMENT '适配器ID',
  `adapter_name` VARCHAR(128) DEFAULT NULL COMMENT '适配器名称',
  `driver_id` VARCHAR(64) NOT NULL COMMENT '驱动ID',
  `device_key` VARCHAR(128) DEFAULT NULL COMMENT '绑定设备标识',
  `connection_config` JSON DEFAULT NULL COMMENT '连接配置',
  `data_mapping` JSON DEFAULT NULL COMMENT '数据映射配置',
  `status` VARCHAR(32) NOT NULL DEFAULT 'stopped' COMMENT '状态:stopped/running/error',
  `last_connected_at` DATETIME DEFAULT NULL COMMENT '最后连接时间',
  `error_detail` VARCHAR(512) DEFAULT NULL COMMENT '错误详情',
  `reconnect_count` INT DEFAULT 0 COMMENT '重连次数',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_adapter_id` (`adapter_id`),
  KEY `idx_driver_id` (`driver_id`),
  KEY `idx_device_key` (`device_key`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='协议适配器表';

CREATE TABLE IF NOT EXISTS `offline_cache_data` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `cache_id` VARCHAR(64) NOT NULL COMMENT '缓存ID',
  `data_type` VARCHAR(32) NOT NULL COMMENT '数据类型:telemetry/event/aggregation',
  `device_key` VARCHAR(128) DEFAULT NULL COMMENT '设备标识',
  `payload` JSON NOT NULL COMMENT '数据负载',
  `priority` INT DEFAULT 5 COMMENT '优先级(1-10)',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态:pending/synced/failed',
  `retry_count` INT DEFAULT 0 COMMENT '重试次数',
  `max_retries` INT DEFAULT 3 COMMENT '最大重试次数',
  `synced_at` DATETIME DEFAULT NULL COMMENT '同步时间',
  `error_detail` VARCHAR(512) DEFAULT NULL COMMENT '错误详情',
  `expires_at` DATETIME DEFAULT NULL COMMENT '过期时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cache_id` (`cache_id`),
  KEY `idx_status` (`status`),
  KEY `idx_device_key` (`device_key`),
  KEY `idx_priority` (`priority`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='离线缓存数据表';

CREATE TABLE IF NOT EXISTS `network_status` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `network_id` VARCHAR(64) NOT NULL COMMENT '网络状态ID',
  `status` VARCHAR(32) NOT NULL COMMENT '状态:online/offline/degraded',
  `latency_ms` INT DEFAULT 0 COMMENT '延迟(ms)',
  `packet_loss_rate` DECIMAL(5,2) DEFAULT 0.00 COMMENT '丢包率',
  `bandwidth_upload` BIGINT DEFAULT 0 COMMENT '上传带宽(bps)',
  `bandwidth_download` BIGINT DEFAULT 0 COMMENT '下载带宽(bps)',
  `is_connected` TINYINT NOT NULL DEFAULT 1 COMMENT '是否连接',
  `last_check_at` DATETIME DEFAULT NULL COMMENT '最后检测时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_network_id` (`network_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网络状态表';

CREATE TABLE IF NOT EXISTS `metric_snapshot` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `snapshot_id` VARCHAR(64) NOT NULL COMMENT '快照ID',
  `timestamp` DATETIME NOT NULL COMMENT '时间戳',
  `metrics` JSON NOT NULL COMMENT '指标数据',
  `dimensions` JSON DEFAULT NULL COMMENT '维度数据',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_id` (`snapshot_id`),
  KEY `idx_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='指标快照表';
