-- NFTIndexer Core Schema Migration V1
-- Core Entity Tables

CREATE TABLE `core_entity` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `ent_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '实体业务ID',
    `type` VARCHAR(64) NOT NULL COMMENT '实体类型',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态',
    `attributes` JSON COMMENT '属性JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_type_status` (`type`, `status`),
    INDEX `idx_ent_id` (`ent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='核心实体表';

CREATE TABLE `config_definition` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `config_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '配置ID',
    `namespace` VARCHAR(64) NOT NULL COMMENT '命名空间',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    `parameters` JSON COMMENT '参数JSON',
    `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    `applied_at` DATETIME COMMENT '应用时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version_lock` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_namespace` (`namespace`),
    INDEX `idx_config_id` (`config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配置定义表';

CREATE TABLE `run_instance` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `run_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '运行实例ID',
    `entity_id` VARCHAR(64) NOT NULL COMMENT '关联实体ID',
    `phase` VARCHAR(32) NOT NULL DEFAULT 'initializing' COMMENT '执行阶段',
    `progress` DECIMAL(5,4) NOT NULL DEFAULT 0.0 COMMENT '进度0-1',
    `started_at` DATETIME COMMENT '开始时间',
    `completed_at` DATETIME COMMENT '完成时间',
    `error_detail` TEXT COMMENT '错误详情',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_entity_id` (`entity_id`),
    INDEX `idx_phase` (`phase`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运行实例表';

CREATE TABLE `stats_snapshot` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `snapshot_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '快照ID',
    `timestamp` DATETIME NOT NULL COMMENT '快照时间',
    `metrics` JSON COMMENT '指标JSON',
    `dimensions` JSON COMMENT '维度JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统计快照表';

-- Cross-Chain Bridge Module Tables
CREATE TABLE `cross_chain_bridge` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `bridge_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '跨链桥接ID',
    `source_chain` VARCHAR(64) NOT NULL COMMENT '源链',
    `target_chain` VARCHAR(64) NOT NULL COMMENT '目标链',
    `source_token` VARCHAR(128) NOT NULL COMMENT '源代币地址',
    `target_token` VARCHAR(128) COMMENT '目标代币地址',
    `source_token_id` DECIMAL(78,0) COMMENT '源代币ID',
    `target_token_id` DECIMAL(78,0) COMMENT '目标代币ID',
    `source_tx_hash` VARCHAR(128) COMMENT '源交易哈希',
    `target_tx_hash` VARCHAR(128) COMMENT '目标交易哈希',
    `sender` VARCHAR(128) NOT NULL COMMENT '发送者地址',
    `recipient` VARCHAR(128) NOT NULL COMMENT '接收者地址',
    `amount` DECIMAL(78,0) NOT NULL DEFAULT 1 COMMENT '数量',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态',
    `message_proof` TEXT COMMENT '消息证明',
    `merkle_proof` TEXT COMMENT '默克尔证明',
    `metadata` JSON COMMENT '元数据JSON',
    `source_confirmations` INT NOT NULL DEFAULT 0 COMMENT '源链确认数',
    `required_confirmations` INT NOT NULL DEFAULT 15 COMMENT '所需确认数',
    `locked_at` DATETIME COMMENT '锁定时间',
    `minted_at` DATETIME COMMENT '铸造时间',
    `completed_at` DATETIME COMMENT '完成时间',
    `error_detail` TEXT COMMENT '错误详情',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_status` (`status`),
    INDEX `idx_source_chain` (`source_chain`),
    INDEX `idx_target_chain` (`target_chain`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨链桥接表';

CREATE TABLE `cross_chain_message` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `message_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '消息ID',
    `bridge_id` VARCHAR(64) NOT NULL COMMENT '关联桥接ID',
    `source_chain` VARCHAR(64) NOT NULL COMMENT '源链',
    `target_chain` VARCHAR(64) NOT NULL COMMENT '目标链',
    `message_type` VARCHAR(64) NOT NULL COMMENT '消息类型',
    `payload_hash` VARCHAR(128) NOT NULL COMMENT '负载哈希',
    `payload` TEXT NOT NULL COMMENT '负载数据',
    `signature` TEXT COMMENT '签名',
    `signers` JSON COMMENT '签名者列表JSON',
    `signature_count` INT NOT NULL DEFAULT 0 COMMENT '签名数量',
    `required_signatures` INT NOT NULL DEFAULT 2 COMMENT '所需签名数',
    `status` VARCHAR(32) NOT NULL DEFAULT 'submitted' COMMENT '状态',
    `submitted_at` DATETIME COMMENT '提交时间',
    `verified_at` DATETIME COMMENT '验证时间',
    `executed_at` DATETIME COMMENT '执行时间',
    `proof_data` JSON COMMENT '证明数据JSON',
    `error_detail` TEXT COMMENT '错误详情',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_bridge_id` (`bridge_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨链消息表';

-- Transaction Module Tables
CREATE TABLE `transaction_record` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `tx_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '交易记录ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `from_address` VARCHAR(128) COMMENT '发送地址',
    `to_address` VARCHAR(128) COMMENT '接收地址',
    `contract_address` VARCHAR(128) COMMENT '合约地址',
    `method_name` VARCHAR(128) COMMENT '方法名',
    `value` DECIMAL(78,0) NOT NULL DEFAULT 0 COMMENT '转账金额',
    `gas_limit` DECIMAL(78,0) NOT NULL COMMENT 'Gas限制',
    `gas_price` DECIMAL(78,0) COMMENT 'Gas价格',
    `priority_fee` DECIMAL(78,0) COMMENT '优先费',
    `max_fee_per_gas` DECIMAL(78,0) COMMENT '最大Gas费用',
    `nonce` DECIMAL(78,0) COMMENT 'Nonce',
    `data` TEXT COMMENT '交易数据',
    `signed_tx` TEXT COMMENT '已签名交易',
    `tx_hash` VARCHAR(128) COMMENT '交易哈希',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态',
    `confirmations` INT NOT NULL DEFAULT 0 COMMENT '确认数',
    `gas_used` DECIMAL(78,0) COMMENT '已用Gas',
    `actual_gas_price` DECIMAL(78,0) COMMENT '实际Gas价格',
    `transaction_fee` DECIMAL(78,0) COMMENT '交易费用',
    `error_detail` TEXT COMMENT '错误详情',
    `raw_response` TEXT COMMENT '原始响应',
    `submitted_at` DATETIME COMMENT '提交时间',
    `confirmed_at` DATETIME COMMENT '确认时间',
    `failed_at` DATETIME COMMENT '失败时间',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_chain_id` (`chain_id`),
    INDEX `idx_tx_hash` (`tx_hash`),
    INDEX `idx_status` (`status`),
    INDEX `idx_from_address` (`from_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易记录表';

-- Multi-Sig Wallet Module Tables
CREATE TABLE `multi_sig_wallet` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `wallet_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '钱包ID',
    `name` VARCHAR(128) NOT NULL COMMENT '钱包名称',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `wallet_address` VARCHAR(128) NOT NULL COMMENT '钱包地址',
    `threshold` INT NOT NULL DEFAULT 2 COMMENT '签名阈值',
    `total_signers` INT NOT NULL DEFAULT 3 COMMENT '签名者总数',
    `signers` JSON NOT NULL COMMENT '签名者列表JSON',
    `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    `created_by` VARCHAR(128) COMMENT '创建人',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_chain_id` (`chain_id`),
    INDEX `idx_wallet_address` (`wallet_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多签钱包表';

CREATE TABLE `multi_sig_proposal` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `proposal_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '提案ID',
    `wallet_id` VARCHAR(64) NOT NULL COMMENT '关联钱包ID',
    `title` VARCHAR(256) NOT NULL COMMENT '提案标题',
    `description` TEXT COMMENT '提案描述',
    `transaction_data` TEXT NOT NULL COMMENT '交易数据',
    `to_address` VARCHAR(128) NOT NULL COMMENT '目标地址',
    `value` DECIMAL(78,0) NOT NULL DEFAULT 0 COMMENT '转账金额',
    `nonce` DECIMAL(78,0) NOT NULL COMMENT 'Nonce',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `required_signatures` INT NOT NULL DEFAULT 2 COMMENT '所需签名数',
    `current_signatures` INT NOT NULL DEFAULT 0 COMMENT '当前签名数',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态',
    `created_by` VARCHAR(128) COMMENT '创建人',
    `executed_by` VARCHAR(128) COMMENT '执行人',
    `tx_hash` VARCHAR(128) COMMENT '执行交易哈希',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL COMMENT '创建时间',
    `expires_at` DATETIME COMMENT '过期时间',
    `executed_at` DATETIME COMMENT '执行时间',
    `rejection_reason` TEXT COMMENT '拒绝原因',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_wallet_id` (`wallet_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多签提案表';

CREATE TABLE `multi_sig_signature` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `signature_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '签名ID',
    `proposal_id` VARCHAR(64) NOT NULL COMMENT '关联提案ID',
    `signer_address` VARCHAR(128) NOT NULL COMMENT '签名者地址',
    `signature` TEXT NOT NULL COMMENT '签名数据',
    `signature_index` INT NOT NULL COMMENT '签名索引',
    `status` VARCHAR(32) NOT NULL DEFAULT 'valid' COMMENT '状态',
    `signed_at` DATETIME NOT NULL COMMENT '签名时间',
    `signed_by` VARCHAR(128) COMMENT '签名人',
    `signature_type` VARCHAR(32) COMMENT '签名类型',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_proposal_id` (`proposal_id`),
    INDEX `idx_signer_address` (`signer_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多签签名表';

-- HD Wallet Module Tables
CREATE TABLE `hd_wallet` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `wallet_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '钱包ID',
    `name` VARCHAR(128) NOT NULL COMMENT '钱包名称',
    `mnemonic` TEXT NOT NULL COMMENT '助记词',
    `passphrase` VARCHAR(256) COMMENT '密码',
    `root_path` VARCHAR(64) NOT NULL COMMENT '根路径',
    `chain_code` VARCHAR(256) COMMENT '链码',
    `public_key` VARCHAR(256) COMMENT '公钥',
    `fingerprint` VARCHAR(64) COMMENT '指纹',
    `created_by` VARCHAR(128) COMMENT '创建人',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='HD钱包表';

CREATE TABLE `derived_address` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `address_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '地址ID',
    `wallet_id` VARCHAR(64) NOT NULL COMMENT '关联钱包ID',
    `address` VARCHAR(128) NOT NULL COMMENT '派生地址',
    `derivation_path` VARCHAR(64) NOT NULL COMMENT '派生路径',
    `index` INT NOT NULL COMMENT '派生索引',
    `public_key` VARCHAR(256) COMMENT '公钥',
    `private_key` TEXT COMMENT '私钥',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    `tags` JSON COMMENT '标签JSON',
    `label` VARCHAR(128) COMMENT '标签',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_wallet_id` (`wallet_id`),
    INDEX `idx_address` (`address`),
    INDEX `idx_chain_id` (`chain_id`),
    INDEX `idx_label` (`label`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='派生地址表';

CREATE TABLE `address_book` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `entry_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '条目ID',
    `address` VARCHAR(128) NOT NULL COMMENT '地址',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `label` VARCHAR(128) COMMENT '标签',
    `category` VARCHAR(64) COMMENT '分类',
    `description` TEXT COMMENT '描述',
    `tags` JSON COMMENT '标签JSON',
    `created_by` VARCHAR(128) COMMENT '创建人',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_address` (`address`),
    INDEX `idx_chain_id` (`chain_id`),
    INDEX `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='地址簿表';

-- Gas Estimation Module Tables
CREATE TABLE `gas_estimate` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `estimate_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '预估ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `base_fee` DECIMAL(78,0) COMMENT '基础费用',
    `priority_fee_low` DECIMAL(78,0) COMMENT '低优先级费',
    `priority_fee_medium` DECIMAL(78,0) COMMENT '中优先级费',
    `priority_fee_high` DECIMAL(78,0) COMMENT '高优先级费',
    `max_fee_low` DECIMAL(78,0) COMMENT '低最大费用',
    `max_fee_medium` DECIMAL(78,0) COMMENT '中最大费用',
    `max_fee_high` DECIMAL(78,0) COMMENT '高最大费用',
    `gas_limit` DECIMAL(78,0) COMMENT 'Gas限制',
    `estimated_cost_low` DECIMAL(78,0) COMMENT '低预估成本',
    `estimated_cost_medium` DECIMAL(78,0) COMMENT '中预估成本',
    `estimated_cost_high` DECIMAL(78,0) COMMENT '高预估成本',
    `block_number` INT COMMENT '区块号',
    `timestamp` DATETIME NOT NULL COMMENT '时间戳',
    `historical_data` JSON COMMENT '历史数据JSON',
    `network_status` JSON COMMENT '网络状态JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_chain_id` (`chain_id`),
    INDEX `idx_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gas预估表';

CREATE TABLE `gas_history` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `history_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '历史ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `block_number` INT NOT NULL COMMENT '区块号',
    `base_fee` DECIMAL(78,0) COMMENT '基础费用',
    `gas_used` DECIMAL(78,0) COMMENT '已用Gas',
    `gas_limit` DECIMAL(78,0) COMMENT 'Gas限制',
    `gas_utilization` DECIMAL(10,6) COMMENT 'Gas利用率',
    `priority_fee_min` DECIMAL(78,0) COMMENT '最小优先费',
    `priority_fee_avg` DECIMAL(78,0) COMMENT '平均优先费',
    `priority_fee_max` DECIMAL(78,0) COMMENT '最大优先费',
    `block_time` DATETIME NOT NULL COMMENT '区块时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_chain_id` (`chain_id`),
    INDEX `idx_block_number` (`block_number`),
    INDEX `idx_block_time` (`block_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gas历史表';

-- Contract Event Listener Module Tables
CREATE TABLE `contract_event_listener` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `listener_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '监听器ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `contract_address` VARCHAR(128) NOT NULL COMMENT '合约地址',
    `event_name` VARCHAR(128) NOT NULL COMMENT '事件名',
    `event_signature` VARCHAR(256) NOT NULL COMMENT '事件签名',
    `abi` TEXT COMMENT 'ABI',
    `callback_url` VARCHAR(512) COMMENT '回调URL',
    `callback_type` VARCHAR(32) NOT NULL DEFAULT 'http' COMMENT '回调类型',
    `filter_topics` JSON COMMENT '过滤主题JSON',
    `from_block` INT COMMENT '起始区块',
    `to_block` INT COMMENT '结束区块',
    `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    `last_processed_block` INT COMMENT '最后处理区块',
    `last_processed_at` DATETIME COMMENT '最后处理时间',
    `config` JSON COMMENT '配置JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_chain_id` (`chain_id`),
    INDEX `idx_contract_address` (`contract_address`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合约事件监听器表';

CREATE TABLE `contract_event_log` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `log_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '日志ID',
    `listener_id` VARCHAR(64) NOT NULL COMMENT '关联监听器ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `contract_address` VARCHAR(128) NOT NULL COMMENT '合约地址',
    `transaction_hash` VARCHAR(128) NOT NULL COMMENT '交易哈希',
    `log_index` INT NOT NULL COMMENT '日志索引',
    `block_number` INT NOT NULL COMMENT '区块号',
    `block_hash` VARCHAR(128) NOT NULL COMMENT '区块哈希',
    `block_time` DATETIME NOT NULL COMMENT '区块时间',
    `event_name` VARCHAR(128) COMMENT '事件名',
    `event_signature` VARCHAR(256) COMMENT '事件签名',
    `topics` JSON COMMENT '主题JSON',
    `decoded_data` JSON COMMENT '解码数据JSON',
    `raw_data` TEXT COMMENT '原始数据',
    `status` VARCHAR(32) NOT NULL DEFAULT 'new' COMMENT '状态',
    `processed_at` DATETIME COMMENT '处理时间',
    `callback_response` TEXT COMMENT '回调响应',
    `callback_attempts` INT NOT NULL DEFAULT 0 COMMENT '回调尝试次数',
    `error_detail` TEXT COMMENT '错误详情',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_listener_id` (`listener_id`),
    INDEX `idx_tx_hash` (`transaction_hash`),
    INDEX `idx_block_number` (`block_number`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合约事件日志表';

-- ZKP Module Tables
CREATE TABLE `zkp_circuit` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `circuit_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '电路ID',
    `circuit_name` VARCHAR(128) NOT NULL COMMENT '电路名称',
    `circuit_type` VARCHAR(64) NOT NULL COMMENT '电路类型',
    `proving_key` TEXT COMMENT '证明密钥',
    `verification_key` TEXT NOT NULL COMMENT '验证密钥',
    `compiled_circuit` TEXT COMMENT '编译后电路',
    `source_code` TEXT COMMENT '源代码',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本',
    `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    `compiled_at` DATETIME COMMENT '编译时间',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_circuit_name` (`circuit_name`),
    INDEX `idx_circuit_type` (`circuit_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZKP电路表';

CREATE TABLE `zkp_proof` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `proof_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '证明ID',
    `circuit_id` VARCHAR(64) NOT NULL COMMENT '关联电路ID',
    `circuit_name` VARCHAR(128) NOT NULL COMMENT '电路名称',
    `proof_data` TEXT NOT NULL COMMENT '证明数据',
    `public_inputs` TEXT COMMENT '公开输入',
    `verification_key` TEXT COMMENT '验证密钥',
    `verified` TINYINT COMMENT '是否验证通过',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态',
    `submitted_at` DATETIME NOT NULL COMMENT '提交时间',
    `verified_at` DATETIME COMMENT '验证时间',
    `verification_time_ms` BIGINT COMMENT '验证耗时毫秒',
    `error_detail` TEXT COMMENT '错误详情',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_circuit_id` (`circuit_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZKP证明表';

-- Chain Indexer Module Tables
CREATE TABLE `chain_indexer_state` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `state_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '状态ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `indexer_name` VARCHAR(128) NOT NULL COMMENT '索引器名称',
    `last_indexed_block` INT NOT NULL DEFAULT 0 COMMENT '最后索引区块',
    `last_finalized_block` INT COMMENT '最后确认区块',
    `status` VARCHAR(32) NOT NULL DEFAULT 'running' COMMENT '状态',
    `last_indexed_at` DATETIME COMMENT '最后索引时间',
    `last_finalized_at` DATETIME COMMENT '最后确认时间',
    `total_blocks_indexed` BIGINT NOT NULL DEFAULT 0 COMMENT '总索引区块数',
    `total_transactions_indexed` BIGINT NOT NULL DEFAULT 0 COMMENT '总索引交易数',
    `total_logs_indexed` BIGINT NOT NULL DEFAULT 0 COMMENT '总索引日志数',
    `error_detail` TEXT COMMENT '错误详情',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    UNIQUE KEY `uk_chain_indexer` (`chain_id`, `indexer_name`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='链索引器状态表';

CREATE TABLE `chain_block` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `block_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '区块ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `block_number` INT NOT NULL COMMENT '区块号',
    `block_hash` VARCHAR(128) NOT NULL COMMENT '区块哈希',
    `parent_hash` VARCHAR(128) COMMENT '父哈希',
    `miner` VARCHAR(128) COMMENT '矿工',
    `difficulty` DECIMAL(78,0) COMMENT '难度',
    `total_difficulty` DECIMAL(78,0) COMMENT '总难度',
    `gas_limit` DECIMAL(78,0) COMMENT 'Gas限制',
    `gas_used` DECIMAL(78,0) COMMENT '已用Gas',
    `block_time` DATETIME NOT NULL COMMENT '区块时间',
    `transaction_count` INT NOT NULL DEFAULT 0 COMMENT '交易数量',
    `log_count` INT NOT NULL DEFAULT 0 COMMENT '日志数量',
    `status` VARCHAR(32) NOT NULL DEFAULT 'indexed' COMMENT '状态',
    `indexed_at` DATETIME NOT NULL COMMENT '索引时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    UNIQUE KEY `uk_chain_block` (`chain_id`, `block_number`),
    INDEX `idx_block_hash` (`block_hash`),
    INDEX `idx_block_time` (`block_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='链区块表';

CREATE TABLE `chain_transaction` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `tx_index_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '交易索引ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `tx_hash` VARCHAR(128) NOT NULL COMMENT '交易哈希',
    `block_number` INT NOT NULL COMMENT '区块号',
    `block_hash` VARCHAR(128) NOT NULL COMMENT '区块哈希',
    `transaction_index` INT NOT NULL COMMENT '交易索引',
    `from_address` VARCHAR(128) COMMENT '发送地址',
    `to_address` VARCHAR(128) COMMENT '接收地址',
    `contract_address` VARCHAR(128) COMMENT '合约地址',
    `value` DECIMAL(78,0) NOT NULL DEFAULT 0 COMMENT '转账金额',
    `gas_price` DECIMAL(78,0) COMMENT 'Gas价格',
    `gas_limit` DECIMAL(78,0) COMMENT 'Gas限制',
    `gas_used` DECIMAL(78,0) COMMENT '已用Gas',
    `nonce` DECIMAL(78,0) COMMENT 'Nonce',
    `method_name` VARCHAR(128) COMMENT '方法名',
    `method_signature` VARCHAR(256) COMMENT '方法签名',
    `input_data` JSON COMMENT '输入数据JSON',
    `raw_input` TEXT COMMENT '原始输入',
    `status` VARCHAR(32) NOT NULL DEFAULT 'success' COMMENT '状态',
    `error_reason` TEXT COMMENT '错误原因',
    `block_time` DATETIME NOT NULL COMMENT '区块时间',
    `indexed_at` DATETIME NOT NULL COMMENT '索引时间',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    INDEX `idx_tx_hash` (`tx_hash`),
    INDEX `idx_block_number` (`block_number`),
    INDEX `idx_from_address` (`from_address`),
    INDEX `idx_to_address` (`to_address`),
    INDEX `idx_contract_address` (`contract_address`),
    INDEX `idx_block_time` (`block_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='链交易表';

CREATE TABLE `nft_metadata` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    `metadata_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '元数据ID',
    `chain_id` VARCHAR(64) NOT NULL COMMENT '链ID',
    `contract_address` VARCHAR(128) NOT NULL COMMENT '合约地址',
    `token_id` DECIMAL(78,0) NOT NULL COMMENT '代币ID',
    `token_uri` TEXT COMMENT '代币URI',
    `name` VARCHAR(256) COMMENT '名称',
    `description` TEXT COMMENT '描述',
    `image` TEXT COMMENT '图片URL',
    `animation_url` TEXT COMMENT '动画URL',
    `external_url` TEXT COMMENT '外部URL',
    `attributes` JSON COMMENT '属性JSON',
    `properties` JSON COMMENT '特性JSON',
    `raw_metadata` TEXT COMMENT '原始元数据',
    `metadata_hash` VARCHAR(128) COMMENT '元数据哈希',
    `standard` VARCHAR(32) COMMENT '标准ERC721/ERC1155',
    `owner` VARCHAR(128) COMMENT '所有者',
    `creator` VARCHAR(128) COMMENT '创建者',
    `minter` VARCHAR(128) COMMENT '铸造者',
    `supply` DECIMAL(78,0) DEFAULT 1 COMMENT '供应量',
    `status` VARCHAR(32) NOT NULL DEFAULT 'indexed' COMMENT '状态',
    `minted_at` DATETIME COMMENT '铸造时间',
    `last_updated_at` DATETIME COMMENT '最后更新时间',
    `indexed_at` DATETIME NOT NULL COMMENT '索引时间',
    `error_detail` TEXT COMMENT '错误详情',
    `metadata` JSON COMMENT '元数据JSON',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    UNIQUE KEY `uk_nft_token` (`chain_id`, `contract_address`, `token_id`),
    INDEX `idx_owner` (`owner`),
    INDEX `idx_name` (`name`),
    INDEX `idx_standard` (`standard`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NFT元数据表';
