CREATE TABLE IF NOT EXISTS resource (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    entity_id VARCHAR(64) NOT NULL COMMENT '实体ID',
    type VARCHAR(32) NOT NULL COMMENT '资源类型',
    status VARCHAR(32) NOT NULL COMMENT '资源状态',
    attributes JSON COMMENT '属性信息',
    config_id VARCHAR(64) COMMENT '配置ID',
    namespace VARCHAR(64) COMMENT '命名空间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_entity_id (entity_id),
    INDEX idx_status (status),
    INDEX idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源表';

CREATE TABLE IF NOT EXISTS config (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    config_id VARCHAR(64) NOT NULL COMMENT '配置ID',
    namespace VARCHAR(64) NOT NULL COMMENT '命名空间',
    version INT NOT NULL COMMENT '版本号',
    parameters JSON COMMENT '参数配置',
    enabled TINYINT DEFAULT 1 COMMENT '是否启用',
    applied_at DATETIME COMMENT '应用时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    UNIQUE KEY uk_config_namespace_version (config_id, namespace, version),
    INDEX idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置表';

CREATE TABLE IF NOT EXISTS run_instance (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    run_id VARCHAR(64) NOT NULL COMMENT '运行实例ID',
    entity_id VARCHAR(64) NOT NULL COMMENT '实体ID',
    phase VARCHAR(32) NOT NULL COMMENT '运行阶段',
    progress DECIMAL(5,4) DEFAULT 0 COMMENT '进度',
    started_at DATETIME COMMENT '开始时间',
    completed_at DATETIME COMMENT '完成时间',
    error_detail TEXT COMMENT '错误详情',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_run_id (run_id),
    INDEX idx_entity_id (entity_id),
    INDEX idx_phase (phase)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运行实例表';

CREATE TABLE IF NOT EXISTS snapshot (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    snapshot_id VARCHAR(64) NOT NULL COMMENT '快照ID',
    timestamp DATETIME NOT NULL COMMENT '时间戳',
    metrics JSON COMMENT '指标数据',
    dimensions JSON COMMENT '维度信息',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_snapshot_id (snapshot_id),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统计快照表';

CREATE TABLE IF NOT EXISTS device_shadow (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    shadow_version INT DEFAULT 1 COMMENT '影子版本',
    desired_state JSON COMMENT '期望状态',
    reported_state JSON COMMENT '上报状态',
    delta_state JSON COMMENT '差异状态',
    last_sync_time DATETIME COMMENT '最后同步时间',
    sync_status VARCHAR(32) DEFAULT 'PENDING' COMMENT '同步状态',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    UNIQUE KEY uk_device_id (device_id),
    INDEX idx_sync_status (sync_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备影子表';

CREATE TABLE IF NOT EXISTS data_aggregation (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    aggregation_id VARCHAR(64) NOT NULL COMMENT '聚合ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    aggregation_type VARCHAR(32) NOT NULL COMMENT '聚合类型',
    time_window VARCHAR(32) NOT NULL COMMENT '时间窗口',
    data_points_count INT DEFAULT 0 COMMENT '数据点数量',
    aggregated_data JSON COMMENT '聚合数据',
    start_time DATETIME COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    upload_status VARCHAR(32) DEFAULT 'PENDING' COMMENT '上传状态',
    upload_time DATETIME COMMENT '上传时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_aggregation_id (aggregation_id),
    INDEX idx_device_id (device_id),
    INDEX idx_upload_status (upload_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据聚合表';

CREATE TABLE IF NOT EXISTS ai_model (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    model_id VARCHAR(64) NOT NULL COMMENT '模型ID',
    model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    model_version VARCHAR(32) NOT NULL COMMENT '模型版本',
    model_type VARCHAR(32) COMMENT '模型类型',
    model_path VARCHAR(256) COMMENT '模型路径',
    model_size BIGINT COMMENT '模型大小',
    model_config JSON COMMENT '模型配置',
    deploy_status VARCHAR(32) DEFAULT 'IDLE' COMMENT '部署状态',
    deployed_devices INT DEFAULT 0 COMMENT '已部署设备数',
    deployed_at DATETIME COMMENT '部署时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    UNIQUE KEY uk_model_version (model_id, model_version),
    INDEX idx_deploy_status (deploy_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型表';

CREATE TABLE IF NOT EXISTS inference_task (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    task_id VARCHAR(64) NOT NULL COMMENT '任务ID',
    model_id VARCHAR(64) NOT NULL COMMENT '模型ID',
    model_name VARCHAR(128) COMMENT '模型名称',
    model_version VARCHAR(32) COMMENT '模型版本',
    device_id VARCHAR(64) COMMENT '设备ID',
    task_status VARCHAR(32) DEFAULT 'PENDING' COMMENT '任务状态',
    priority INT DEFAULT 5 COMMENT '优先级',
    input_data JSON COMMENT '输入数据',
    inference_result JSON COMMENT '推理结果',
    inference_duration BIGINT COMMENT '推理耗时(ms)',
    scheduled_time DATETIME COMMENT '调度时间',
    start_time DATETIME COMMENT '开始时间',
    completed_time DATETIME COMMENT '完成时间',
    error_message TEXT COMMENT '错误信息',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_task_id (task_id),
    INDEX idx_model_id (model_id),
    INDEX idx_task_status (task_status),
    INDEX idx_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推理任务表';

CREATE TABLE IF NOT EXISTS protocol_driver (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    driver_id VARCHAR(64) NOT NULL COMMENT '驱动ID',
    protocol_type VARCHAR(32) NOT NULL COMMENT '协议类型',
    driver_name VARCHAR(128) NOT NULL COMMENT '驱动名称',
    driver_version VARCHAR(32) COMMENT '驱动版本',
    driver_class VARCHAR(256) COMMENT '驱动类名',
    driver_path VARCHAR(256) COMMENT '驱动路径',
    connection_params JSON COMMENT '连接参数',
    load_status VARCHAR(32) DEFAULT 'UNLOADED' COMMENT '加载状态',
    loaded_at DATETIME COMMENT '加载时间',
    enabled TINYINT DEFAULT 1 COMMENT '是否启用',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    UNIQUE KEY uk_protocol_driver (protocol_type, driver_name),
    INDEX idx_load_status (load_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='协议驱动表';

CREATE TABLE IF NOT EXISTS data_forward_rule (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    rule_id VARCHAR(64) NOT NULL COMMENT '规则ID',
    rule_name VARCHAR(128) NOT NULL COMMENT '规则名称',
    source_protocol VARCHAR(32) NOT NULL COMMENT '源协议',
    target_protocol VARCHAR(32) NOT NULL COMMENT '目标协议',
    source_topic VARCHAR(256) COMMENT '源主题',
    target_topic VARCHAR(256) COMMENT '目标主题',
    data_mapping JSON COMMENT '数据映射',
    forward_mode VARCHAR(32) DEFAULT 'SYNC' COMMENT '转发模式',
    qos INT DEFAULT 0 COMMENT '服务质量',
    enabled TINYINT DEFAULT 1 COMMENT '是否启用',
    last_forward_time DATETIME COMMENT '最后转发时间',
    forward_count BIGINT DEFAULT 0 COMMENT '转发次数',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_rule_id (rule_id),
    INDEX idx_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据转发规则表';

CREATE TABLE IF NOT EXISTS firmware_package (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    firmware_id VARCHAR(64) NOT NULL COMMENT '固件ID',
    firmware_name VARCHAR(128) NOT NULL COMMENT '固件名称',
    firmware_version VARCHAR(32) NOT NULL COMMENT '固件版本',
    device_model VARCHAR(64) NOT NULL COMMENT '设备型号',
    package_type VARCHAR(32) DEFAULT 'FULL' COMMENT '包类型',
    package_path VARCHAR(256) COMMENT '包路径',
    package_size BIGINT COMMENT '包大小',
    package_md5 VARCHAR(32) COMMENT '包MD5',
    delta_from_version VARCHAR(32) COMMENT '差分源版本',
    delta_package_path VARCHAR(256) COMMENT '差分包路径',
    delta_package_size BIGINT COMMENT '差分包大小',
    update_params JSON COMMENT '升级参数',
    release_notes TEXT COMMENT '发布说明',
    release_status VARCHAR(32) DEFAULT 'DRAFT' COMMENT '发布状态',
    released_at DATETIME COMMENT '发布时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    UNIQUE KEY uk_firmware_version (device_model, firmware_version),
    INDEX idx_release_status (release_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='固件包表';

CREATE TABLE IF NOT EXISTS upgrade_task (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    task_id VARCHAR(64) NOT NULL COMMENT '任务ID',
    firmware_id VARCHAR(64) NOT NULL COMMENT '固件ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    upgrade_status VARCHAR(32) DEFAULT 'PENDING' COMMENT '升级状态',
    upgrade_phase VARCHAR(32) DEFAULT 'INIT' COMMENT '升级阶段',
    progress INT DEFAULT 0 COMMENT '进度',
    grayscale_group VARCHAR(32) COMMENT '灰度分组',
    retry_count INT DEFAULT 0 COMMENT '重试次数',
    max_retries INT DEFAULT 3 COMMENT '最大重试次数',
    scheduled_time DATETIME COMMENT '计划时间',
    start_time DATETIME COMMENT '开始时间',
    completed_time DATETIME COMMENT '完成时间',
    error_message TEXT COMMENT '错误信息',
    rollback_reason TEXT COMMENT '回滚原因',
    rollback_time DATETIME COMMENT '回滚时间',
    original_version VARCHAR(32) COMMENT '原版本',
    target_version VARCHAR(32) COMMENT '目标版本',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_task_id (task_id),
    INDEX idx_device_id (device_id),
    INDEX idx_upgrade_status (upgrade_status),
    INDEX idx_grayscale_group (grayscale_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='升级任务表';

CREATE TABLE IF NOT EXISTS offline_data_cache (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    cache_id VARCHAR(64) NOT NULL COMMENT '缓存ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    data_type VARCHAR(32) NOT NULL COMMENT '数据类型',
    data_content JSON COMMENT '数据内容',
    data_size BIGINT COMMENT '数据大小',
    cache_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '缓存时间',
    sync_status VARCHAR(32) DEFAULT 'PENDING' COMMENT '同步状态',
    sync_attempts INT DEFAULT 0 COMMENT '同步尝试次数',
    last_sync_attempt DATETIME COMMENT '最后同步尝试时间',
    sync_time DATETIME COMMENT '同步时间',
    expire_time DATETIME COMMENT '过期时间',
    priority INT DEFAULT 5 COMMENT '优先级',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_cache_id (cache_id),
    INDEX idx_device_id (device_id),
    INDEX idx_sync_status (sync_status),
    INDEX idx_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='离线数据缓存表';

CREATE TABLE IF NOT EXISTS device_info (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    device_name VARCHAR(128) COMMENT '设备名称',
    device_type VARCHAR(32) COMMENT '设备类型',
    device_model VARCHAR(64) COMMENT '设备型号',
    manufacturer VARCHAR(128) COMMENT '制造商',
    serial_number VARCHAR(128) COMMENT '序列号',
    firmware_version VARCHAR(32) COMMENT '固件版本',
    hardware_version VARCHAR(32) COMMENT '硬件版本',
    device_secret VARCHAR(256) COMMENT '设备密钥',
    device_cert TEXT COMMENT '设备证书',
    status VARCHAR(32) DEFAULT 'INACTIVE' COMMENT '设备状态',
    device_labels JSON COMMENT '设备标签',
    device_config JSON COMMENT '设备配置',
    activated_at DATETIME COMMENT '激活时间',
    last_online_time DATETIME COMMENT '最后在线时间',
    last_heartbeat_time DATETIME COMMENT '最后心跳时间',
    heartbeat_interval INT DEFAULT 60 COMMENT '心跳间隔',
    ip_address VARCHAR(64) COMMENT 'IP地址',
    location VARCHAR(256) COMMENT '位置',
    auth_method VARCHAR(32) DEFAULT 'SECRET' COMMENT '认证方式',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    UNIQUE KEY uk_device_id (device_id),
    UNIQUE KEY uk_serial_number (serial_number),
    INDEX idx_status (status),
    INDEX idx_device_type (device_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备信息表';

CREATE TABLE IF NOT EXISTS rule_definition (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    rule_id VARCHAR(64) NOT NULL COMMENT '规则ID',
    rule_name VARCHAR(128) NOT NULL COMMENT '规则名称',
    rule_type VARCHAR(32) COMMENT '规则类型',
    rule_description TEXT COMMENT '规则描述',
    trigger_condition JSON COMMENT '触发条件',
    action_definition JSON COMMENT '动作定义',
    execution_mode VARCHAR(32) DEFAULT 'ASYNC' COMMENT '执行模式',
    priority INT DEFAULT 5 COMMENT '优先级',
    enabled TINYINT DEFAULT 1 COMMENT '是否启用',
    trigger_count BIGINT DEFAULT 0 COMMENT '触发次数',
    last_triggered_at DATETIME COMMENT '最后触发时间',
    last_execution_result VARCHAR(32) COMMENT '最后执行结果',
    last_error_message TEXT COMMENT '最后错误信息',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    version INT DEFAULT 1 COMMENT '乐观锁版本',
    INDEX idx_rule_id (rule_id),
    INDEX idx_enabled (enabled),
    INDEX idx_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='规则定义表';
