CREATE TABLE device (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    device_name VARCHAR(128) COMMENT '设备名称',
    device_type VARCHAR(64) COMMENT '设备类型',
    product_key VARCHAR(64) COMMENT '产品Key',
    device_secret VARCHAR(128) COMMENT '设备密钥',
    status VARCHAR(32) NOT NULL DEFAULT 'INACTIVE' COMMENT '设备状态',
    firmware_version VARCHAR(64) COMMENT '固件版本',
    hardware_version VARCHAR(64) COMMENT '硬件版本',
    ip_address VARCHAR(64) COMMENT 'IP地址',
    region VARCHAR(64) COMMENT '区域',
    last_heartbeat_at DATETIME COMMENT '最后心跳时间',
    activated_at DATETIME COMMENT '激活时间',
    deactivated_at DATETIME COMMENT '注销时间',
    attributes JSON COMMENT '属性',
    tags JSON COMMENT '标签',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_device_id (device_id),
    KEY idx_status (status),
    KEY idx_product_key (product_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备表';

CREATE TABLE device_auth (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    session_id VARCHAR(64) COMMENT '会话ID',
    token VARCHAR(256) COMMENT '访问令牌',
    refresh_token VARCHAR(256) COMMENT '刷新令牌',
    expires_at DATETIME COMMENT '过期时间',
    last_authenticated_at DATETIME COMMENT '最后认证时间',
    auth_method VARCHAR(32) COMMENT '认证方式',
    client_ip VARCHAR(64) COMMENT '客户端IP',
    user_agent VARCHAR(512) COMMENT '用户代理',
    revoked TINYINT(1) DEFAULT 0 COMMENT '是否吊销',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_device_id (device_id),
    KEY idx_token (token),
    KEY idx_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备认证表';

CREATE TABLE config_definition (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    config_id VARCHAR(64) NOT NULL COMMENT '配置ID',
    namespace VARCHAR(64) NOT NULL COMMENT '命名空间',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    parameters JSON COMMENT '配置参数',
    enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用',
    applied_at DATETIME COMMENT '应用时间',
    applied_by VARCHAR(64) COMMENT '应用人',
    description VARCHAR(512) COMMENT '描述',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_config_version (config_id, namespace, version),
    KEY idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配置定义表';

CREATE TABLE run_instance (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    run_id VARCHAR(64) NOT NULL COMMENT '运行实例ID',
    entity_id VARCHAR(64) COMMENT '关联实体ID',
    entity_type VARCHAR(64) COMMENT '关联实体类型',
    phase VARCHAR(32) COMMENT '执行阶段',
    status VARCHAR(32) COMMENT '执行状态',
    progress DOUBLE COMMENT '进度',
    config_snapshot JSON COMMENT '配置快照',
    started_at DATETIME COMMENT '开始时间',
    completed_at DATETIME COMMENT '完成时间',
    error_detail TEXT COMMENT '错误详情',
    trace_id VARCHAR(64) COMMENT '链路追踪ID',
    result_data JSON COMMENT '结果数据',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_run_id (run_id),
    KEY idx_entity (entity_id, entity_type),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运行实例表';

CREATE TABLE metrics_snapshot (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    snapshot_id VARCHAR(64) NOT NULL COMMENT '快照ID',
    timestamp DATETIME NOT NULL COMMENT '时间戳',
    metrics JSON COMMENT '指标数据',
    dimensions JSON COMMENT '维度数据',
    metric_type VARCHAR(32) COMMENT '指标类型',
    window_size_ms BIGINT COMMENT '窗口大小(毫秒)',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_snapshot_id (snapshot_id),
    KEY idx_timestamp (timestamp),
    KEY idx_metric_type (metric_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='指标快照表';

CREATE TABLE offline_data (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    data_id VARCHAR(64) NOT NULL COMMENT '数据ID',
    device_id VARCHAR(64) COMMENT '设备ID',
    data_type VARCHAR(32) COMMENT '数据类型',
    payload JSON COMMENT '数据内容',
    collected_at DATETIME NOT NULL COMMENT '采集时间',
    synced TINYINT(1) DEFAULT 0 COMMENT '是否已同步',
    synced_at DATETIME COMMENT '同步时间',
    sync_attempts INT DEFAULT 0 COMMENT '同步尝试次数',
    sync_error TEXT COMMENT '同步错误',
    checksum VARCHAR(64) COMMENT '校验和',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_data_id (data_id),
    KEY idx_device_synced (device_id, synced),
    KEY idx_synced (synced)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='离线数据表';

CREATE TABLE firmware (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    firmware_id VARCHAR(64) NOT NULL COMMENT '固件ID',
    product_key VARCHAR(64) COMMENT '产品Key',
    version VARCHAR(64) NOT NULL COMMENT '固件版本',
    file_name VARCHAR(256) COMMENT '文件名',
    file_url VARCHAR(512) COMMENT '文件URL',
    file_size BIGINT COMMENT '文件大小(字节)',
    md5 VARCHAR(64) COMMENT 'MD5校验',
    signature VARCHAR(256) COMMENT '数字签名',
    diff_from_version VARCHAR(64) COMMENT '差分来源版本',
    diff_file_size BIGINT COMMENT '差分文件大小',
    diff_file_url VARCHAR(512) COMMENT '差分文件URL',
    description VARCHAR(512) COMMENT '描述',
    release_notes TEXT COMMENT '发布说明',
    active TINYINT(1) DEFAULT 1 COMMENT '是否激活',
    released_at DATETIME COMMENT '发布时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_firmware_id (firmware_id),
    UNIQUE KEY uk_product_version (product_key, version),
    KEY idx_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='固件表';

CREATE TABLE ota_job (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    job_id VARCHAR(64) NOT NULL COMMENT 'OTA任务ID',
    firmware_id VARCHAR(64) COMMENT '固件ID',
    target_version VARCHAR(64) COMMENT '目标版本',
    rollout_strategy VARCHAR(32) COMMENT '发布策略',
    batch_size INT COMMENT '批次大小',
    current_batch INT DEFAULT 0 COMMENT '当前批次',
    total_batches INT COMMENT '总批次',
    success_count INT DEFAULT 0 COMMENT '成功数量',
    failed_count INT DEFAULT 0 COMMENT '失败数量',
    total_devices INT COMMENT '设备总数',
    auto_rollback TINYINT(1) DEFAULT 1 COMMENT '自动回滚',
    failure_threshold DOUBLE COMMENT '失败阈值',
    scheduled_at DATETIME COMMENT '计划时间',
    started_at DATETIME COMMENT '开始时间',
    completed_at DATETIME COMMENT '完成时间',
    status VARCHAR(32) COMMENT '任务状态',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_job_id (job_id),
    KEY idx_status (status),
    KEY idx_firmware_id (firmware_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OTA任务表';

CREATE TABLE ota_device (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    job_id VARCHAR(64) NOT NULL COMMENT 'OTA任务ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    batch_number INT COMMENT '批次号',
    upgrade_status VARCHAR(32) COMMENT '升级状态',
    current_version VARCHAR(64) COMMENT '当前版本',
    target_version VARCHAR(64) COMMENT '目标版本',
    progress DOUBLE COMMENT '进度',
    started_at DATETIME COMMENT '开始时间',
    completed_at DATETIME COMMENT '完成时间',
    error_detail TEXT COMMENT '错误详情',
    rollback_required TINYINT(1) DEFAULT 0 COMMENT '是否需要回滚',
    rollback_started_at DATETIME COMMENT '回滚开始时间',
    rollback_completed_at DATETIME COMMENT '回滚完成时间',
    rollback_error TEXT COMMENT '回滚错误',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_job_device (job_id, device_id),
    KEY idx_device_id (device_id),
    KEY idx_status (upgrade_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OTA设备表';

CREATE TABLE device_shadow (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    desired_state JSON COMMENT '期望状态',
    reported_state JSON COMMENT '实际状态',
    delta_state JSON COMMENT '差异状态',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    desired_updated_at DATETIME COMMENT '期望状态更新时间',
    reported_updated_at DATETIME COMMENT '实际状态更新时间',
    last_sync_error TEXT COMMENT '最后同步错误',
    sync_pending TINYINT(1) DEFAULT 0 COMMENT '是否有待同步',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_device_id (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备影子表';

CREATE TABLE inference_model (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    model_id VARCHAR(64) NOT NULL COMMENT '模型ID',
    model_name VARCHAR(128) COMMENT '模型名称',
    model_version VARCHAR(64) COMMENT '模型版本',
    model_type VARCHAR(64) COMMENT '模型类型',
    model_format VARCHAR(32) COMMENT '模型格式',
    model_size BIGINT COMMENT '模型大小(字节)',
    model_url VARCHAR(512) COMMENT '模型URL',
    md5 VARCHAR(64) COMMENT 'MD5校验',
    input_schema JSON COMMENT '输入Schema',
    output_schema JSON COMMENT '输出Schema',
    labels JSON COMMENT '标签',
    target_device_memory_mb INT COMMENT '目标设备内存(MB)',
    average_latency_ms DOUBLE COMMENT '平均延迟(毫秒)',
    accuracy DOUBLE COMMENT '准确率',
    active TINYINT(1) DEFAULT 1 COMMENT '是否激活',
    deployed_at DATETIME COMMENT '部署时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_model_id (model_id),
    KEY idx_model_type (model_type),
    KEY idx_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='推理模型表';

CREATE TABLE inference_task (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    task_id VARCHAR(64) NOT NULL COMMENT '任务ID',
    model_id VARCHAR(64) COMMENT '模型ID',
    device_id VARCHAR(64) COMMENT '设备ID',
    status VARCHAR(32) COMMENT '任务状态',
    input_data JSON COMMENT '输入数据',
    output_data JSON COMMENT '输出数据',
    confidence DOUBLE COMMENT '置信度',
    inference_time_ms BIGINT COMMENT '推理耗时(毫秒)',
    scheduled_at DATETIME COMMENT '调度时间',
    started_at DATETIME COMMENT '开始时间',
    completed_at DATETIME COMMENT '完成时间',
    error_detail TEXT COMMENT '错误详情',
    priority INT DEFAULT 0 COMMENT '优先级',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_task_id (task_id),
    KEY idx_device_status (device_id, status),
    KEY idx_model_id (model_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='推理任务表';

CREATE TABLE aggregation_window (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    window_id VARCHAR(64) NOT NULL COMMENT '窗口ID',
    device_id VARCHAR(64) COMMENT '设备ID',
    metric_name VARCHAR(64) COMMENT '指标名称',
    window_start_ms BIGINT COMMENT '窗口开始时间(毫秒)',
    window_end_ms BIGINT COMMENT '窗口结束时间(毫秒)',
    window_size_ms BIGINT COMMENT '窗口大小(毫秒)',
    record_count BIGINT COMMENT '记录数量',
    min_value DOUBLE COMMENT '最小值',
    max_value DOUBLE COMMENT '最大值',
    avg_value DOUBLE COMMENT '平均值',
    sum_value DOUBLE COMMENT '总和',
    variance DOUBLE COMMENT '方差',
    std_dev DOUBLE COMMENT '标准差',
    percentiles JSON COMMENT '百分位数',
    aggregated_at DATETIME COMMENT '聚合时间',
    uploaded TINYINT(1) DEFAULT 0 COMMENT '是否已上传',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_window_id (window_id),
    KEY idx_device_metric (device_id, metric_name),
    KEY idx_window_time (window_start_ms, window_end_ms),
    KEY idx_uploaded (uploaded)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='聚合窗口表';

CREATE TABLE raw_data_point (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    point_id VARCHAR(64) NOT NULL COMMENT '数据点ID',
    device_id VARCHAR(64) COMMENT '设备ID',
    metric_name VARCHAR(64) COMMENT '指标名称',
    metric_value DOUBLE COMMENT '指标值',
    unit VARCHAR(32) COMMENT '单位',
    collected_at DATETIME NOT NULL COMMENT '采集时间',
    tags JSON COMMENT '标签',
    aggregated TINYINT(1) DEFAULT 0 COMMENT '是否已聚合',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_point_id (point_id),
    KEY idx_device_metric (device_id, metric_name),
    KEY idx_collected_at (collected_at),
    KEY idx_aggregated (aggregated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='原始数据表';

CREATE TABLE request_log (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    trace_id VARCHAR(64) COMMENT '链路追踪ID',
    span_id VARCHAR(32) COMMENT '跨度ID',
    parent_span_id VARCHAR(32) COMMENT '父跨度ID',
    service_name VARCHAR(64) COMMENT '服务名称',
    request_method VARCHAR(16) COMMENT '请求方法',
    request_path VARCHAR(512) COMMENT '请求路径',
    response_status INT COMMENT '响应状态码',
    duration_ms BIGINT COMMENT '耗时(毫秒)',
    client_ip VARCHAR(64) COMMENT '客户端IP',
    user_agent VARCHAR(512) COMMENT '用户代理',
    request_headers JSON COMMENT '请求头',
    request_body TEXT COMMENT '请求体',
    response_body TEXT COMMENT '响应体',
    error_message TEXT COMMENT '错误信息',
    start_time DATETIME COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_trace_id (trace_id),
    KEY idx_request_path (request_path),
    KEY idx_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='请求日志表';

CREATE TABLE backup_record (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    backup_id VARCHAR(64) NOT NULL COMMENT '备份ID',
    backup_type VARCHAR(32) COMMENT '备份类型',
    backup_scope VARCHAR(32) COMMENT '备份范围',
    storage_path VARCHAR(512) COMMENT '存储路径',
    file_size BIGINT COMMENT '文件大小(字节)',
    md5 VARCHAR(64) COMMENT 'MD5校验',
    status VARCHAR(32) COMMENT '备份状态',
    started_at DATETIME COMMENT '开始时间',
    completed_at DATETIME COMMENT '完成时间',
    error_detail TEXT COMMENT '错误详情',
    retention_days INT COMMENT '保留天数',
    encrypted TINYINT(1) DEFAULT 0 COMMENT '是否加密',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_backup_id (backup_id),
    KEY idx_status (status),
    KEY idx_backup_type (backup_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='备份记录表';
