import { execa, execaSync } from 'execa';
import which from 'which';
import ora from 'ora';
import simpleGit, { SimpleGit } from 'simple-git';
import type { PackageManagerType, ProjectConfig } from './types.js';

const PM_CHECK_ORDER: PackageManagerType[] = ['pnpm', 'yarn', 'npm'];

export function detectPackageManagers(): PackageManagerType[] {
  const available: PackageManagerType[] = [];

  for (const pm of PM_CHECK_ORDER) {
    try {
      which.sync(pm);
      available.push(pm);
    } catch {
      // not available
    }
  }

  if (available.length === 0) {
    available.push('npm');
  }

  return available;
}

export function getFastestPackageManager(): PackageManagerType {
  const available = detectPackageManagers();
  return available[0] ?? 'npm';
}

export class PackageManager {
  private pm: PackageManagerType;
  cwd: string;

  constructor(pm: PackageManagerType, cwd: string) {
    this.pm = pm;
    this.cwd = cwd;
  }

  async installDependencies(): Promise<void> {
    const spinner = ora(`使用 ${this.pm} 安装依赖...`).start();

    try {
      const args: string[] = [];

      if (this.pm === 'pnpm') {
        args.push('install', '--prefer-offline');
      } else if (this.pm === 'yarn') {
        args.push('install', '--prefer-offline');
      } else {
        args.push('install', '--prefer-offline', '--no-audit');
      }

      await execa(this.pm, args, {
        cwd: this.cwd,
        stdio: 'ignore',
      });

      spinner.succeed(`依赖安装完成 (${this.pm})`);
    } catch (error) {
      spinner.fail(`依赖安装失败: ${(error as Error).message}`);
      throw error;
    }
  }

  async runScript(script: string, args: string[] = []): Promise<void> {
    const pmArgs = this.pm === 'npm' ? ['run', script, ...args] : [script, ...args];
    await execa(this.pm, pmArgs, { cwd: this.cwd, stdio: 'inherit' });
  }

  getType(): PackageManagerType {
    return this.pm;
  }
}

export async function initGitRepo(config: ProjectConfig): Promise<void> {
  const spinner = ora('初始化 Git 仓库...').start();

  try {
    const git: SimpleGit = simpleGit(config.targetDir);

    await git.init();
    await git.add(['.']);
    await git.commit(`chore: initial commit from create-solo-project

Project: ${config.projectName}
Framework: ${config.framework}
Generated by create-solo-project v1.0.0`);

    if (config.gitRemoteUrl && config.gitRemoteUrl.trim()) {
      await git.addRemote('origin', config.gitRemoteUrl.trim());
      spinner.succeed('Git 仓库初始化完成,已添加远程仓库');
    } else {
      spinner.succeed('Git 仓库初始化完成');
    }
  } catch (error) {
    spinner.fail(`Git 初始化失败: ${(error as Error).message}`);
  }
}

export function isGitAvailable(): boolean {
  try {
    execaSync('git', ['--version']);
    return true;
  } catch {
    return false;
  }
}
