apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: log-analytics
namePrefix: la-

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - log-agent-daemonset.yaml
  - stream-pipeline-deployment.yaml
  - pattern-detector-deployment.yaml
  - metrics-aggregator-deployment.yaml
  - storage-index-deployment.yaml
  - api-server-deployment.yaml
  - api-server-service.yaml
  - api-server-hpa.yaml
  - metrics-service.yaml
  - ingress.yaml
  - kafka-strimzi.yaml
  - postgres-cloudnative.yaml

commonLabels:
  app.kubernetes.io/part-of: log-analytics
  app.kubernetes.io/managed-by: kustomize
