apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  labels:
    app: log-analytics
type: Opaque
data:
  postgres-password: cG9zdGdyZXNfcGFzc3dvcmQ=
  minio-access-key: bWluaW9hZG1pbg==
  minio-secret-key: bWluaW9hZG1pbl9wYXNzd29yZA==
  smtp-password: c210cF9wYXNzd29yZA==
