CREATE TABLE scheduled_tasks (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    task_type VARCHAR(64) NOT NULL,
    cron_expression VARCHAR(128),
    fixed_delay BIGINT,
    fixed_rate BIGINT,
    target_service VARCHAR(128),
    target_method VARCHAR(128),
    parameters JSON,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    priority INT DEFAULT 0,
    max_retries INT DEFAULT 3,
    retry_interval INT DEFAULT 60000,
    last_execution_time DATETIME,
    next_execution_time DATETIME,
    created_by VARCHAR(64),
    namespace VARCHAR(64),
    labels JSON,
    config_id VARCHAR(64),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    INDEX idx_task_status (status),
    INDEX idx_next_execution (next_execution_time),
    INDEX idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE task_executions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(64) NOT NULL,
    phase VARCHAR(32) NOT NULL,
    progress DOUBLE PRECISION DEFAULT 0,
    started_at DATETIME NOT NULL,
    completed_at DATETIME,
    status VARCHAR(32) NOT NULL,
    error_detail TEXT,
    error_message VARCHAR(1024),
    stack_trace TEXT,
    result JSON,
    retry_count INT DEFAULT 0,
    scheduled_by VARCHAR(64),
    executed_by VARCHAR(64),
    duration_ms BIGINT,
    context JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    INDEX idx_task_id (task_id),
    INDEX idx_status (status),
    INDEX idx_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE config_definitions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    config_id VARCHAR(64) NOT NULL,
    namespace VARCHAR(64) NOT NULL,
    version INT NOT NULL,
    parameters JSON,
    enabled BOOLEAN NOT NULL DEFAULT true,
    applied_at DATETIME,
    applied_by VARCHAR(64),
    description TEXT,
    labels JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_config_version (config_id, version),
    INDEX idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE metrics_snapshots (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    snapshot_id VARCHAR(64) NOT NULL UNIQUE,
    timestamp DATETIME NOT NULL,
    metrics JSON,
    dimensions JSON,
    source VARCHAR(128),
    namespace VARCHAR(64),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    INDEX idx_timestamp (timestamp),
    INDEX idx_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notifications (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    notification_id VARCHAR(64) NOT NULL UNIQUE,
    type VARCHAR(32) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(512),
    content TEXT,
    template_params JSON,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    retry_count INT DEFAULT 0,
    max_retries INT DEFAULT 3,
    sent_at DATETIME,
    delivered_at DATETIME,
    error_message TEXT,
    trace_id VARCHAR(64),
    metadata JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    INDEX idx_status (status),
    INDEX idx_trace_id (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE trace_spans (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_id VARCHAR(64) NOT NULL,
    span_id VARCHAR(64) NOT NULL,
    parent_span_id VARCHAR(64),
    service_name VARCHAR(128) NOT NULL,
    operation_name VARCHAR(255) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME,
    duration_micros BIGINT,
    status VARCHAR(32),
    tags JSON,
    baggage JSON,
    kind VARCHAR(32),
    host VARCHAR(128),
    process_id VARCHAR(64),
    sampled BOOLEAN DEFAULT false,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    INDEX idx_trace_id (trace_id),
    INDEX idx_service_name (service_name),
    INDEX idx_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
