[package]
name = "risk-control"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
sqlx.workspace = true
image.workspace = true
reqwest.workspace = true
async-trait.workspace = true
dashmap.workspace = true
shared.workspace = true
common.workspace = true
models.workspace = true
