apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "log-agent.fullname" . }}-config
  labels:
    {{- include "log-agent.labels" . | nindent 4 }}
data:
  default.toml: |
    [agent]
    batch_size = {{ .Values.config.agent.batch_size }}
    flush_interval_ms = {{ .Values.config.agent.flush_interval_ms }}
    channel_buffer_size = {{ .Values.config.agent.channel_buffer_size }}

    [agent.metrics]
    host = {{ .Values.config.agent.metrics.host | quote }}
    port = {{ .Values.config.agent.metrics.port }}
    path = {{ .Values.config.agent.metrics.path | quote }}
  {{ .Values.config.env }}.toml: |
    [agent]
    downstream_url = {{ .Values.config.agent.downstream_url | quote }}
    batch_size = {{ .Values.config.agent.batch_size }}
    flush_interval_ms = {{ .Values.config.agent.flush_interval_ms }}
    channel_buffer_size = {{ .Values.config.agent.channel_buffer_size }}

    [agent.kubernetes]
    enabled = {{ .Values.config.agent.kubernetes.enabled }}
    node_name = "${NODE_NAME}"
    pod_log_dir = "/var/log/pods"
    api_enrichment = {{ .Values.config.agent.kubernetes.api_enrichment }}

    [agent.metrics]
    host = {{ .Values.config.agent.metrics.host | quote }}
    port = {{ .Values.config.agent.metrics.port }}
    path = {{ .Values.config.agent.metrics.path | quote }}
